### ISSUE TITLE
Hide the call button for public rooms

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2183] opened 2019-09-13 04:53 UTC
**Is your feature request related to a problem? Please describe.**
It could be an issue if you make a room 100% public, to have a huge button that says "call" :) - some random human or a bot may click that.

**Describe the solution you'd like**
Add an option to disable calling for such public rooms or disable it by default.

**Comment by nickvergessen** [comment] 2019-09-16 10:32
Duplicate of https://github.com/nextcloud/spreed/issues/1282

**Closed by nickvergessen** 2019-09-16 10:32 UTC
Labels: 0. Needs triage, enhancement
