### ISSUE TITLE
Chat in sidebar doesn't update correctly

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4540] opened 2020-11-05 11:22 UTC
Not sure if this is a Talk issue or more a general server/sidebar issue. Feel free to move it to another repository.

When I open a file which is not yet shared and go to the chat tab I see this:

![image](https://user-images.githubusercontent.com/1589737/98234730-2223ea80-1f61-11eb-966f-b10254901921.png)

Now I click on "share file" which lead me to the share dialog, I share the file and go back to the chat tab.

I would now expect that I can start chatting directly, but I still see the same as on the screenshot above. Only after closing the sidebar and opening it again I can start chatting. The chat tab should update automatically, either triggered by the share operation or by switching back to the chat tab.

**Comment by PVince81** [comment] 2020-11-05 11:28
Confirmed as this has annoyed me as well.

Need to see after https://github.com/nextcloud/spreed/pull/4291 is merged as it integrates with modified/new APIs from the files app. If that bit is not enough, might need extra handling.

**Comment by danxuliu** [comment] 2020-11-10 08:35
The bug is in the Files app, and it is caused by the `FileInfo` object not being properly updated after a file is shared. You can see that too in the Files app itself; after a file is shared the _Shared_ text is not shown for that file in the file list until the list is reloaded.

It is a regression introduced in Nextcloud 18 if I recall correctly, when the sharing tab was moved to Vue.

**Comment by nickvergessen** [comment] 2020-11-12 09:35
> It is a regression introduced in Nextcloud 18

No, this bug is there since ages, more like ownCloud times

**Comment by danxuliu** [comment] 2020-11-19 17:10
> > It is a regression introduced in Nextcloud 18
>
> No, this bug is there since ages, more like ownCloud times

No, it is a regression introduced in Nextcloud 18. In Nextcloud 17 the `FileInfo` object is properly updated when a file is shared, so the _Shared_ text is immediately shown for that file in the file list without having to reload. And as the `FileInfo` object is properly updated with Talk 7 the _Share this file_ / _Join this conversation_ button in the _Chat_ tab of the Files app sidebar works as expected.

**Comment by nickvergessen** [comment] 2020-11-26 15:09
Never the less it's something that needs fixing in Server? Is it already fixed with the new sidebar thingy?

**Comment by danxuliu** [comment] 2020-11-27 07:53
> Never the less it's something that needs fixing in Server?

Yes.

> Is it already fixed with the new sidebar thingy?

No :-(

**Comment by nickvergessen** [comment] 2020-11-27 13:50
So closing here.

**Closed by nickvergessen** 2020-11-27 13:50 UTC
Labels: 1. to develop, bug, feature: chat  💬
