### ISSUE TITLE
[Feature Idea] Moderationtools for Groupcalls

### ISSUE THREAD

**Issue by newhinton** [nextcloud/spreed#1519] opened 2019-02-07 11:13 UTC
If you have a group call, let's say a meeting. Currently, there is no way to really control the participants if there is an heated argument or debate. 

While it isn't necessarily part of talk's scope to calm such a group, muting all participants except a speaker could greatly help to keep such calls orderly. 

Mainly this would require: 

The ability to set a conversation to "managed"

A "managed" call is different only in the way that the one who created the call has the ability to mute/unmute the participants from his side of the call for everyone. (I am thinking of audio only here)

This could be greatly improved with an "I want to Talk" indicator, so that the manager can orderly give speaking power to a caller. 

This could be further improved by adding the ability to hand over the "manager" role to a different user

I had the idea because a friend of mine mentioned that a meeting over talk would quickly collapse because nobody would keep order in such a call, and i agree with her. That does not mean that this is truly a good idea, any comments on how good/bad this feature would be?

**Comment by nickvergessen** [comment] 2019-02-07 12:39
Duplicate of #282 , agreed?

**Comment by newhinton** [comment] 2019-02-07 13:03
it overlaps heavily, but i think the issue-description of #282 lacks the moderation part, where a single person has control over all the users. If that is not lost with this ticket, i would agree :)

**Comment by nickvergessen** [comment] 2019-02-07 13:16
Well moderators are the creators of the room, (and promoted persons) so that matches exactly your case.

**Closed by nickvergessen** 2019-02-07 13:16 UTC
Labels: 0. Needs triage, enhancement
