### ISSUE TITLE
Exporting Conversations

### ISSUE THREAD

**Issue by gecegezen** [nextcloud/spreed#6677] opened 2021-12-08 21:39 UTC
**Is your feature request related to a problem? Please describe.**
We have many long conversations on project groups. As a sysadmin, I'd like to delete few hefty ones after project's closure in order to keep my database unbloated. However, our project managers do not want me to delete these, since they contain many important information that might be referred later. So, I looked for a way to export conversations. Unfortunately, I could not find an easy way keeping all formatting elements. 

**Describe the solution you'd like**
An export option that stores an HTML output of the conversation keeping all formatting elements beginning from first ever message. In other words, a complete HTML dump (or may be pdf but not necessarily) is needed. Ability to making it restricted to admin group is also important, I would not like everybody to dump whole conversations from anywhere.

**Describe alternatives you've considered**
Couldn't find an alternative, I fiddled with MYSQL db but retrieving messages and other elements and reformatting them is beyond my scope. I would really appreciate it if you consider implementing this feature request. 

**Additional context**
-- None --

**Comment by nickvergessen** [comment] 2021-12-11 22:39
Duplicate of #232

**Closed by nickvergessen** 2021-12-11 22:39 UTC
Labels: 0. Needs triage, enhancement
