### ISSUE TITLE
Unmute option for moderator to request others to speak

### ISSUE THREAD

**Issue by HasanZahir1992** [nextcloud/spreed#6496] opened 2021-11-13 09:08 UTC
**Is your feature request related to a problem? Please describe.**
in nextcloud talk application the moderators dosent have the option the request others to unmute them and talk 

**Describe the solution you'd like**
an option that will allow the moderators to request others to speak 

**Describe alternatives you've considered**

**Additional context**

**Comment by nickvergessen** [comment] 2021-11-13 09:57
Duplicate of #4566

**Closed** 2021-11-17 15:03 UTC
Labels: 0. Needs triage, enhancement
