### ISSUE TITLE
Nextcloud 21.0.1 Test Talk Error no working ice candidates

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/spreed#5617] opened 2021-05-17 19:26 UTC
## Steps to reproduce
1.  Go into admin tab
2. talk
3. test this server

### Expected behaviour
On Nextcloud 20.0.8 on talk version 10.1.2 it works fine and when i click on test this server comes back with no issues
### Actual behaviour
Tell us what happens instead
On Nextcloud 21.0.1 on Talk version 11.2.1 once i click on Test this server after a bit comes back as No working ice candidates

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.2.1 

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
Yes
**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
Yes

### Coturn Config
<details>

```
listening-port=80
tls-listening-port=443
fingerprint
use-auth-secret
static-auth-secret=NA
realm=turn.domain.com
cert=/etc/ssl/domain.crt
pkey=/etc/ssl/domain.key
cipher-list="ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"
no-tlsv1
no-tlsv1_1
total-quota=0
bps-capacity=0
stale-nonce
no-multicast-peers
listening-ip=X.X.X.X
listening-ip=X.X.X.X
relay-ip=X.X.X.X
log-file=/var/log/coturn.log
no-stdout-log
simple-log
no-cli
cli-password=NA
```
</details>

### These browser logs are when running the test from Nextcloud 21 
<details>

```
Received candidates (3) [{…}, {…}, {…}]0: address: "66.158.36.56"component: "1"foundation: "2211000572"port: "54540"priority: "25108735"protocol: "udp"type: "relay"__proto__: Object1: address: "66.158.36.56"component: "1"foundation: "2639822217"port: "64659"priority: "8331007"protocol: "udp"type: "relay"__proto__: Object2: address: "66.158.36.56"component: "1"foundation: "2639822217"port: "62184"priority: "8331263"protocol: "udp"type: "relay"__proto__: Objectlength: 3__proto__: Array(0)
```
</details>

### Coturn Logs when test via nextcloud 21
<details>

```
46: IPv4. tcp or tls connected to: 66.158.36.34:11110
46: IPv4. tcp or tls connected to: 66.158.36.34:11111
46: IPv4. tcp or tls connected to: 66.158.36.34:11112
46: session 001000000000000002: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
46: session 003000000000000005: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
46: IPv4. Local relay addr: 66.158.36.56:59280
46: session 001000000000000002: new, realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, lifetime=600
46: session 001000000000000002: realm <turn.axtsolutions.com> user <1621279485:turn-test-user>: incoming packet ALLOCATE processed, success
46: session 002000000000000002: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
46: IPv4. Local relay addr: 66.158.36.56:64607
46: session 003000000000000005: new, realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
46: session 003000000000000005: realm <turn.axtsolutions.com> user <1621279485:turn-test-user>: incoming packet ALLOCATE processed, success
46: IPv4. Local relay addr: 66.158.36.56:57816
46: session 002000000000000002: new, realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
46: session 002000000000000002: realm <turn.axtsolutions.com> user <1621279485:turn-test-user>: incoming packet ALLOCATE processed, success
56: session 001000000000000002: refreshed, realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, lifetime=0
56: session 002000000000000002: refreshed, realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, lifetime=0, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
56: session 003000000000000005: refreshed, realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, lifetime=0, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
56: session 001000000000000002: realm <turn.axtsolutions.com> user <1621279485:turn-test-user>: incoming packet REFRESH processed, success
56: session 003000000000000005: realm <turn.axtsolutions.com> user <1621279485:turn-test-user>: incoming packet REFRESH processed, success
56: session 002000000000000002: realm <turn.axtsolutions.com> user <1621279485:turn-test-user>: incoming packet REFRESH processed, success
56: session 001000000000000002: TCP socket closed remotely 66.158.36.34:11110
56: session 001000000000000002: usage: realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, rp=3, rb=292, sp=3, sb=336
56: session 003000000000000005: TLS/TCP socket disconnected: 66.158.36.34:11112
56: session 002000000000000002: TLS/TCP socket disconnected: 66.158.36.34:11111
56: session 002000000000000002: usage: realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, rp=3, rb=292, sp=3, sb=336
56: session 003000000000000005: usage: realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>, rp=3, rb=292, sp=3, sb=336
56: session 002000000000000002: closed (2nd stage), user <1621279485:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11111, reason: TLS/TCP socket buffer operation error (callback)
56: session 003000000000000005: closed (2nd stage), user <1621279485:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11112, reason: TLS/TCP socket buffer operation error (callback)
56: session 001000000000000002: closed (2nd stage), user <1621279485:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11110, reason: TCP connection closed by client (callback)
56: session 003000000000000005: delete: realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>
56: session 002000000000000002: delete: realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>
56: session 001000000000000002: delete: realm=<turn.axtsolutions.com>, username=<1621279485:turn-test-user>
56: IPv4. tcp or tls connected to: 66.158.36.34:11126
56: IPv4. tcp or tls connected to: 66.158.36.34:11127
56: IPv4. tcp or tls connected to: 66.158.36.34:11128
56: session 000000000000000001: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
56: session 001000000000000003: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
56: session 002000000000000003: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
56: IPv4. Local relay addr: 66.158.36.56:59915
56: IPv4. Local relay addr: 66.158.36.56:51024
56: session 001000000000000003: new, realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
56: session 000000000000000001: new, realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, lifetime=600
56: session 000000000000000001: realm <turn.axtsolutions.com> user <1621279496:turn-test-user>: incoming packet ALLOCATE processed, success
56: session 001000000000000003: realm <turn.axtsolutions.com> user <1621279496:turn-test-user>: incoming packet ALLOCATE processed, success
56: IPv4. Local relay addr: 66.158.36.56:54839
56: session 002000000000000003: new, realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, lifetime=600, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
56: session 002000000000000003: realm <turn.axtsolutions.com> user <1621279496:turn-test-user>: incoming packet ALLOCATE processed, success
66: session 002000000000000003: refreshed, realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, lifetime=0, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
66: session 001000000000000003: refreshed, realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, lifetime=0, cipher=ECDHE-RSA-AES256-GCM-SHA384, method=TLSv1.2
66: session 002000000000000003: realm <turn.axtsolutions.com> user <1621279496:turn-test-user>: incoming packet REFRESH processed, success
66: session 000000000000000001: refreshed, realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, lifetime=0
66: session 000000000000000001: realm <turn.axtsolutions.com> user <1621279496:turn-test-user>: incoming packet REFRESH processed, success
66: session 001000000000000003: realm <turn.axtsolutions.com> user <1621279496:turn-test-user>: incoming packet REFRESH processed, success
66: session 000000000000000001: TCP socket closed remotely 66.158.36.34:11126
66: session 000000000000000001: usage: realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, rp=3, rb=292, sp=3, sb=336
66: session 001000000000000003: TLS/TCP socket disconnected: 66.158.36.34:11128
66: session 001000000000000003: usage: realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, rp=3, rb=292, sp=3, sb=336
66: session 002000000000000003: TLS/TCP socket disconnected: 66.158.36.34:11127
66: session 002000000000000003: usage: realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>, rp=3, rb=292, sp=3, sb=336
66: session 000000000000000001: closed (2nd stage), user <1621279496:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11126, reason: TCP connection closed by client (callback)
66: session 002000000000000003: closed (2nd stage), user <1621279496:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11127, reason: TLS/TCP socket buffer operation error (callback)
66: session 002000000000000003: delete: realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>
66: session 000000000000000001: delete: realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>
66: session 001000000000000003: closed (2nd stage), user <1621279496:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11128, reason: TLS/TCP socket buffer operation error (callback)
66: session 001000000000000003: delete: realm=<turn.axtsolutions.com>, username=<1621279496:turn-test-user>

```
</details>

### Coturn Logs from Nextcloud 20.0.8
<details>

```
122: session 003000000000000006: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
122: IPv4. Local relay addr: 66.158.36.56:54342
122: session 003000000000000006: new, realm=<turn.axtsolutions.com>, username=<1621279562:turn-test-user>, lifetime=600
122: session 003000000000000006: realm <turn.axtsolutions.com> user <1621279562:turn-test-user>: incoming packet ALLOCATE processed, success
132: session 003000000000000006: refreshed, realm=<turn.axtsolutions.com>, username=<1621279562:turn-test-user>, lifetime=0
132: session 003000000000000006: realm <turn.axtsolutions.com> user <1621279562:turn-test-user>: incoming packet REFRESH processed, success
132: session 003000000000000006: TCP socket closed remotely 66.158.36.34:11324
132: session 003000000000000006: usage: realm=<turn.axtsolutions.com>, username=<1621279562:turn-test-user>, rp=3, rb=292, sp=3, sb=336
132: session 003000000000000006: closed (2nd stage), user <1621279562:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11324, reason: TCP connection closed by client (callback)
132: session 003000000000000006: delete: realm=<turn.axtsolutions.com>, username=<1621279562:turn-test-user>
149: IPv4. tcp or tls connected to: 66.158.36.34:11347
149: session 001000000000000004: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
149: IPv4. Local relay addr: 66.158.36.56:64969
149: session 001000000000000004: new, realm=<turn.axtsolutions.com>, username=<1621279588:turn-test-user>, lifetime=600
149: session 001000000000000004: realm <turn.axtsolutions.com> user <1621279588:turn-test-user>: incoming packet ALLOCATE processed, success
159: session 001000000000000004: refreshed, realm=<turn.axtsolutions.com>, username=<1621279588:turn-test-user>, lifetime=0
159: session 001000000000000004: realm <turn.axtsolutions.com> user <1621279588:turn-test-user>: incoming packet REFRESH processed, success
159: session 001000000000000004: TCP socket closed remotely 66.158.36.34:11347
159: session 001000000000000004: usage: realm=<turn.axtsolutions.com>, username=<1621279588:turn-test-user>, rp=3, rb=292, sp=3, sb=336
159: session 001000000000000004: closed (2nd stage), user <1621279588:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11347, reason: TCP connection closed by client (callback)
159: session 001000000000000004: delete: realm=<turn.axtsolutions.com>, username=<1621279588:turn-test-user>
160: IPv4. tcp or tls connected to: 66.158.36.34:11348
160: session 000000000000000002: realm <turn.axtsolutions.com> user <>: incoming packet message processed, error 401: Unauthorized
160: IPv4. Local relay addr: 66.158.36.56:52523
160: session 000000000000000002: new, realm=<turn.axtsolutions.com>, username=<1621279600:turn-test-user>, lifetime=600
160: session 000000000000000002: realm <turn.axtsolutions.com> user <1621279600:turn-test-user>: incoming packet ALLOCATE processed, success
170: session 000000000000000002: refreshed, realm=<turn.axtsolutions.com>, username=<1621279600:turn-test-user>, lifetime=0
170: session 000000000000000002: realm <turn.axtsolutions.com> user <1621279600:turn-test-user>: incoming packet REFRESH processed, success
170: session 000000000000000002: TCP socket closed remotely 66.158.36.34:11348
170: session 000000000000000002: usage: realm=<turn.axtsolutions.com>, username=<1621279600:turn-test-user>, rp=3, rb=292, sp=3, sb=336
170: session 000000000000000002: closed (2nd stage), user <1621279600:turn-test-user> realm <turn.axtsolutions.com> origin <>, local 66.158.36.55:443, remote 66.158.36.34:11348, reason: TCP connection closed by client (callback)
170: session 000000000000000002: delete: realm=<turn.axtsolutions.com>, username=<1621279600:turn-test-user>
```
</details>

**Comment by andyxheli** [comment] 2021-05-17 19:48
### These browser logs are when running the test from Nextcloud 21 
<details>

```
Received candidates (3) [{…}, {…}, {…}]0: address: "66.158.36.56"component: "1"foundation: "2211000572"port: "54540"priority: "25108735"protocol: "udp"type: "relay"__proto__: Object1: address: "66.158.36.56"component: "1"foundation: "2639822217"port: "64659"priority: "8331007"protocol: "udp"type: "relay"__proto__: Object2: address: "66.158.36.56"component: "1"foundation: "2639822217"port: "62184"priority: "8331263"protocol: "udp"type: "relay"__proto__: Objectlength: 3__proto__: Array(0)
```
</details>

**Comment by acsfer** [comment] 2021-05-18 15:14
Duplicate of https://github.com/nextcloud/spreed/issues/5563

**Closed by acsfer** 2021-05-18 15:14 UTC
Labels: 0. Needs triage, bug
