### ISSUE TITLE
Multiuser voice/video option to mute other participants

### ISSUE THREAD

**Issue by Luticus** [nextcloud/spreed#1862] opened 2019-05-26 15:16 UTC
**Is your feature request related to a problem? Please describe.**
Not a technical one really.  Basically this would prevent people from been annoying or abusing the chat room.

**Describe the solution you'd like**
Users should have the option to mute/hide video for other people in the voice/video chat.  This way if a person is being annoying they can be muted.  Basically if someone is being annoying or has horrible feed back you should be able to block their stream from playing.  This should be on a per user basis.  So if I'm in a room with person A, B and C, and I mute B I should still hear A and C but not B and person A and C should still hear B.

**Describe alternatives you've considered**
Currently I don't think there are any, maybe removing them from the room?

**Additional context**

**Comment by nickvergessen** [comment] 2019-06-20 09:48
Duplicate of #282

**Closed by nickvergessen** 2019-06-20 09:48 UTC
Labels: 0. Needs triage, enhancement
