### ISSUE TITLE
Indicator for read position

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/spreed#1788] opened 2019-05-08 10:08 UTC
**Is your feature request related to a problem? Please describe.**
I left the browser open while doing something else, chat is going on. What did i miss in the conversation? 

**Describe the solution you'd like**
Show an indicator for new messages that happened while you were not active.

IRCCloud does it like this:
![D0844F44-5B79-4F50-B4BE-EC95347B0F97](https://user-images.githubusercontent.com/1250540/57367611-9ec9e300-7189-11e9-8f8a-43a9f409c799.png)

**Additional context**
Possibly related to #798. Should messages that occurred while i tabbed out be considered unread?

**Comment by nickvergessen** [comment] 2019-05-08 10:14
There is no issue yet, but work was done already in the past:
https://github.com/nextcloud/spreed/pull/1214

**Comment by georgehrke** [comment] 2019-05-08 10:42
Just to be sure my main point is understood:
This issue probably consists of two sub issues:
- show a read marker, as being implemented in #1214 
- Don't mark messages as read, just because the browser is open. At least for me, the chat app is open all the time between 9 to 5 on my third screen. Most of the time, i will be looking at my other screens while working and not pay attention to the chat. Hence, messages should only be marked as read, when there is focus on the window. The same holds true when using tabs in your browser. Messages should only be marked as read when the chat is in the currently visible tab, not in a background tab.

**Comment by call-me-matt** [comment] 2020-07-30 05:24
I was waiting for this, too, as I don't want to read the conversations backwards until I find the point where I left last time. Really like the way telegram handles that: the chat window remains at the indicator, but also tells you how many messages are unread and offers a direct jump to the end of the conversation:

![grafik](https://user-images.githubusercontent.com/34400929/88883882-a6b1ef00-d235-11ea-9514-f13dd2b21594.png)

**Comment by nickvergessen** [comment] 2021-01-13 14:30
Actually a duplicate of #1164

**Closed by nickvergessen** 2021-01-13 14:30 UTC
Labels: 1. to develop, enhancement, feature: api 🛠️, feature: chat  💬, feature: frontend 🖌️
