### ISSUE TITLE
Firefox - screen sharing shows black screen when starting for second time

### ISSUE THREAD

**Issue by Peterede** [nextcloud/spreed#1361] opened 2018-12-11 01:20 UTC
## Steps to reproduce
1. In Firefox browser connect call and start screen sharing
2. Stop screen sharing then start it again
3. black screen is shown on peer screens where screen sharing should be

### Expected behaviour
Screen should be shown

### Actual behaviour
Black screen is shown

## Browser
Firefox
**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox

**Browser version:** 63.0.3

### Browser log
No errors are reported in the browser log

## Spreed app
3.2.4

**Comment by brtptrs** [comment] 2018-12-12 16:09
I can confirm this problem

**Comment by brtptrs** [comment] 2018-12-14 11:51
I've just testet this with NC15 and Talk 5.0 and the problem still exists. On has to refresh the browser to be able to share a second window.

**Comment by nickvergessen** [comment] 2019-01-28 13:48
We will revisit this, after moving to a new WebRTC library ( #1063 ).
Maybe that fixes it already.

**Comment by brtptrs** [comment] 2019-04-09 16:20
NC16 with Talk 5.99.10 still has this problem.

**Comment by rspierenburg** [comment] 2019-04-17 12:30
I can confirm this as well.

**Comment by danxuliu** [comment] 2019-04-17 17:18
I could not reproduce this with Firefox 52 nor Firefox 66, with or without MCU, on _master_ with #1730 and #1738 already merged, nor on _stable15-1571-fix-sharing-own-screen-when-other-peer-is-sharing-the-screen_ (#1740).

Please test again in a few days once those pull requests are merged :-)

**Comment by brtptrs** [comment] 2019-04-26 07:42
I have just tried it with NC16 + Talk 6 + FF 66 + Ubuntu and the problem unfortunately is still there.

**Comment by danxuliu** [comment] 2019-04-27 16:32
I have been testing in different ways on a server installed from scratch with Nextcloud 16 and Talk 6.0 and I could not reproduce the issue.

@brtptrs Could you try again after performing a hard refresh of Talk in your browser? Just open Talk and then hold _Ctrl_ and press _F5_. This will reload the page and ensure that you are using the latest JavaScript files sent by the server and not the ones in your browser cache (which could be the ones from a previous Talk version in which the issue was not fixed). Thanks!

**Comment by brtptrs** [comment] 2019-04-29 07:42
@danxuliu I've tried deleting all caches but the problem remains. 
Just to make sure the problem is clear:
The black-screen is on the browsers of the remote viewers, independent of which, chrome users also see the black screen.
Only if the person sharing his/her screen is on FF the problem turns up. The person sharing the screen does not have the problem. That makes it worse, if I'm sharing my screen to me everything looks fine.
When sharing the screen from Chrome to FF all is well.
I've tried it from different machines with different browsers.
We can set up a talk session to test this if that would help.

**Comment by danxuliu** [comment] 2019-04-29 16:55
@brtptrs 
>  We can set up a talk session to test this if that would help.

Yes, that would be very helpful. Please create a public conversation in your server and [send me a mail](https://github.com/nextcloud/spreed/blob/master/js/filesplugin.js#L3) with the URL (or just post it here if you prefer, of course ;-) ); for the time being there is no need for you to worry about being in the conversation, I will try to see if I can reproduce the problem in your server by myself ;-) Thanks!

**Comment by brtptrs** [comment] 2019-05-06 14:24
@danxuliu I've sent you a URL by mail

**Comment by danxuliu** [comment] 2019-08-02 11:39
Oops, I forgot to update this; **brtptrs**' issue was a different one, and I have checked again now that the pull requests mentioned in https://github.com/nextcloud/spreed/issues/1361#issuecomment-484182619 are merged and I can not reproduce the problem any more. Therefore I will close this issue; feel free to reopen if I missed something ;-)

**Closed by danxuliu** 2019-08-02 11:39 UTC
Labels: bug, feature: webrtc 🚡

**Comment by mtadeunet** [comment] 2020-01-23 12:15
@danxuliu what was @brtptrs issue? I'm experiencing the same problem.

**Comment by danxuliu** [comment] 2020-03-13 09:08
@mtadeunet Sorry, the mention slipped by. Unless you are a Talk customer (in which case please use the support system) using a very old HPB version (in which case please update to the latest one) brtptrs' issue can not be the same as yours, even if it they seem similar ;-)

Please open a new issue describing the problem you are facing with as much detail as possible (specially a list of steps to reproduce the problem). Thanks!
