### ISSUE TITLE
audio record and save

### ISSUE THREAD

**Issue by yehudaclinton** [nextcloud/spreed#2014] opened 2019-07-18 13:41 UTC
There should be an option to automatically record a conference and have it saved to a specific folder.

Like what [zoom](https://zoommeetingdownload.com/zoom/how-to-record-a-zoom-meeting/) has.

**Comment by nickvergessen** [comment] 2019-07-18 13:53
Duplicate of https://github.com/nextcloud/spreed/issues/1232

**Closed by nickvergessen** 2019-07-18 13:53 UTC
Labels: 0. Needs triage, enhancement
