### ISSUE TITLE
Bug on NextCloud 18.0.3

### ISSUE THREAD

**Issue by CreatAddict** [nextcloud/spreed#3385] opened 2020-04-23 15:57 UTC
## Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Debian 10

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.3

**Nextcloud Version:** 18.0.3

**List of activated apps:**

<details>
```
:~# /usr/bin/sudo -u www-data /usr/bin/php /var/www/html/nextcloud/occ app:install spreed
PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535, because the name is already in use in /var/www/html/nextcloud/apps/spreed/lib/Migration/Version2000Date20170707093535.php on line 127
```
</details>

**Comment by acsfer** [comment] 2020-04-23 16:14
Duplicate of https://github.com/nextcloud/spreed/issues/2806

**Closed by acsfer** 2020-04-23 16:14 UTC
Labels: 0. Needs triage, bug
