### ISSUE TITLE
Set guest name on calling URL

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/spreed#4128] opened 2020-09-08 10:10 UTC
Hello.

I want to embed a public group chat (using it's URL) in a software. It's a "help" chat.
My wish was to ask the user first what username he want and then open the URL with the guest name as parameter (e.g. like "?guestname=myname") or something. Ist that already possible in some ways? If not, this is the feature request to it.

**Comment by nickvergessen** [comment] 2020-09-08 11:29
Sounds like a duplicate of #855

**Closed** 2020-09-09 07:18 UTC
Labels: 0. Needs triage, enhancement

**Comment by Pilzinsel64** [comment] 2020-09-09 11:52
Basically yes. I already was thinking about this.

But in my situation I would ask the user for a name (or use his username of PC) BEFORE opening the browser (so in my program). So my wish was to be able to already set a custom username while opening the webbrowser.

E.g. instead of calling this URL:
https://pilzinsel64.com/pilzcloud/call/q4cuy7fx
Call this URL to start the call with the Name "Pilzinsel64" as example:
https://pilzinsel64.com/pilzcloud/call/q4cuy7fx?guestname=Pilzinsel64

If the user is already logged in, the "guestname" parameter could be ignored.
