### ISSUE TITLE
How moderator can disable or hide (guest, user, group) webcam, mic, screen icons?

### ISSUE THREAD

**Issue by mohdsalman86** [nextcloud/spreed#3146] opened 2020-03-24 17:17 UTC
Can we do only one-way direction over several peers through nextcloud talk? I mean, all peers (guests, users,groups) can only view/watch/listen to the moderator!

or is there any way to hide webcam,mic, screen share icons from (guests, users, groups) side?
<img width="184" alt="Screen Shot 2020-03-24 at 8 15 39 PM" src="https://user-images.githubusercontent.com/10356405/77456546-6f0ce380-6e0c-11ea-873d-f3f8edbcf1e9.png">

Thanks

**Comment by nickvergessen** [comment] 2020-03-24 17:39
Hi @mohdsalman86

At the moment this is not yet implemented but it is on our roadmap (see issue #282 ) . If you need this urgently in your business you can consider contacting our [sales team](https://nextcloud.com/enterprise/buy/) to accelerate its development.
If you are in a hurry as home user, you can get involved! See [nextcloud.com/contribute](https://nextcloud.com/contribute)

cheers

**Comment by nickvergessen** [comment] 2020-03-24 17:39
Duplicate of #282

**Closed by nickvergessen** 2020-03-24 17:39 UTC
Labels: 0. Needs triage, enhancement

**Comment by nickvergessen** [comment] 2020-03-24 17:43
Okay, well only half a duplicate of #282 because that only allows you to mute the participant at the moment, but they can unmute again.

But I guess #3104 has you covered too

**Comment by mohdsalman86** [comment] 2020-03-24 19:58
@nickvergessen  Thank you for your quick response, so can I customize the code by myself!

**Comment by nickvergessen** [comment] 2020-03-25 15:46
Or you customize it on the repository and send a pull request, so everyone can benefit from your work! :sunglasses: 
If you need any help feel free to ping me on questions
