### ISSUE TITLE
Blank screen after 8.0.9 update

### ISSUE THREAD

**Issue by juliusbr** [nextcloud/spreed#3548] opened 2020-05-14 06:35 UTC
## Steps to reproduce
Update Talk from 8.0.8 to 8.0.9

### Expected behaviour
Talk works fine and shows in Browser

### Actual behaviour
Can't open Talk in Browser, it shows only a white screen. Also the Talk admin settings show text, but the fields (for eg inport your tun server) are missing

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows 10 1909

**Browser name:** Firefox, But Edge has the same Problem

**Browser version:** 76.0.1

### Browser log

<details>

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. addStylesClient.js:220:17
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions granted App.vue:242
Die Ressource von "https://***REMOVED SENSITIVE VALUE***" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff). spreed
Laden fehlgeschlagen für das <script> mit der Quelle "https://***REMOVED SENSITIVE VALUE***/apps/spreed/js/talk.js?v=309d701c-0". spreed:47:1

</details>

## Talk app

**Talk app version:** 8.0.9

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Linux 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64

**Web server:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.1.44

**PHP version:**
7.2.24-0ubuntu0.18.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud Version:** 18.0.4 - 18.0.4.2

**List of activated apps:**

<details>

Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - analytics: 2.3.1
 - apporder: 0.9.0
 - bookmarks: 3.0.13
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - cookbook: 0.6.5
 - dav: 1.14.0
 - deck: 1.0.0
 - documentserver_community: 0.1.5
 - drawio: 0.9.5
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_automatedtagging: 1.8.2
 - files_downloadactivity: 1.7.0
 - files_linkeditor: 1.0.13
 - files_mindmap: 0.0.21
 - files_pdfviewer: 1.7.0
 - files_photospheres: 1.0.8
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - keeweb: 0.6.2
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.3.4
 - maps: 0.1.6
 - metadata: 0.11.1
 - music: 0.14.0
 - news: 14.1.7
 - nextcloud_announcements: 1.7.0
 - notes: 3.3.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocr: 6.0.40
 - ocsms: 2.1.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - phonetrack: 0.6.2
 - photos: 1.0.0
 - polls: 1.4.3
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - radio: 0.6.6
 - recommendations: 0.6.0
 - sensorlogger: 0.1.2
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - social: 0.2.101
 - socialsharing_email: 2.0.0
 - spreed: 8.0.9
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - tasks: 0.13.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_email: 1.0.1
 - twofactor_nextcloud_notification: 2.3.0
 - twofactor_totp: 4.1.3
 - twofactor_u2f: 5.1.0
 - unsplash: 1.1.5
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - weather: 1.7.2
 - workflow_pdf_converter: 1.3.1
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - emlviewer
 - encryption
 - files_external
 - ojsxc
 - qownnotesapi
 - ransomware_detection
 - user_ldap

</details>

**Nextcloud configuration:**

<details>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "default_language": "de",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "memcache.distributed": "\\OC\\Memcache\\Memcached",
    "memcached_servers": [
        [
            "localhost",
            11211
        ]
    ],
    "app_install_overwrite": [
        "keeweb",
        "social",
        "ocsms",
        "weather"
    ],
    "enable_previews": true,
    "preview_max_x": 4096,
    "preview_max_y": 4096,
    "theme": "",
    "loglevel": 2,
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "has_rebuilt_cache": true,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Font",
        "OC\\Preview\\SVG",
        "OC\\Preview\\MKV",
        "OC\\Preview\\MP4",
        "OC\\Preview\\AVI",
        "OC\\Preview\\Image",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF"
    ]
}

</details>

### Server log (data/nextcloud.log)
<details>
</details>

**Comment by gabooh** [comment] 2020-05-14 06:49
Probably a duplicate of #3532

**Comment by nickvergessen** [comment] 2020-05-14 06:50
Yeah

**Closed by nickvergessen** 2020-05-14 06:50 UTC
Labels: 0. Needs triage, bug
