### ISSUE TITLE
4:3 Aspect Ratio

### ISSUE THREAD

**Issue by llamallama** [nextcloud/spreed#3407] opened 2020-04-28 00:07 UTC
## Steps to reproduce
1. Start a Nextcloud Talk session
2. Note that all video windows are using a 4:3 aspect ratio
3. There is no way to change this

### Expected behaviour
It should use the resolution of the webcam which is usually 16:9.

### Actual behaviour
It uses a 4:3 aspect ratio

## Browser
Firefox 75
Chrome  81.0.4044

**Microphone available:** yes/no
Yes

**Camera available:** yes/no
Yes

**Operating system:** Windows/Ubuntu/...
Linux Mint

**Browser name:** Firefox/Chrome/...
Chrome/Firefox

**Browser version:** 50.1/55/...
Firefox 75
Chrome  81.0.4044

### Browser log

<details>
```
19:53:14.018 Navigating away, leaving conversation App.vue:196
19:53:14.245 Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:803620
19:53:14.828 JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
19:53:14.894 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
19:53:15.000 Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
19:53:15.007 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
19:53:15.475 Setting current user App.vue:289
19:53:15.758 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 5 globals.js:66:15
19:53:25.727 Current participant found CallButton.vue:92
19:53:26.445 Current participant found CallButton.vue:92
19:53:26.516 Joined 
{…}
​
config: Object { url: "https://cloud.xxxxxxxxxx.xxx/ocs/v2.php/apps/spreed/api/v1/room/xxxxxxxx/participants/active", method: "post", data: "{}", … }
​
data: Object { ocs: {…} }
​
headers: Object { "cache-control": "no-cache, no-store, must-revalidate", "content-encoding": "gzip", "content-security-policy": "default-src 'none';base-uri 'none';manifest-src 'self'", … }
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
status: 200
​
statusText: "OK"
​
<prototype>: Object { … }
signaling.js:212:12
19:53:27.274 Current participant found 3 CallButton.vue:92
19:53:27.772 Current participant found 2 CallButton.vue:92
19:53:29.547 Joining call CallButton.vue:162
19:53:31.862 localMediaStarted webrtc.js:803:10
19:53:32.243 The request has been canceled 
Object { message: undefined }
MessagesList.vue:459
19:53:31.864 Empty string passed to getElementById(). simplewebrtc.js:348:18
19:53:33.081 Current participant found CallButton.vue:92
19:54:03.727 Current participant found CallButton.vue:92
19:54:34.269 Current participant found CallButton.vue:92
19:55:04.919 Current participant found CallButton.vue:92
19:55:35.516 Current participant found
```

</details>

## Talk app

**Talk app version:** 8.0.8

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: RancherOS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.17

**Nextcloud Version:** 18.0.3

**List of activated apps:**

<details>
```
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - passwords: 2020.4.1
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "app.mail.smtp.timeout": 20,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxxxxx.xxx",
            "rancher1",
            "rancher2"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "installed": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "overwrite.cli.url": "https:\/\/cloud.xxxxxxxxx.xxx",
        "overwriteprotocol": "https",
        "overwritehost": "cloud.xxxxxxxxx.xxx",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enable_email": "no",
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "2.10.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "81"
        },
        "bruteforcesettings": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "ajax",
            "enterpriseLogoChecked": "yes",
            "global_cache_gc_lastrun": "1436532758",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1400721453.341",
            "lastcron": "1588031989",
            "lastupdateResult": "{\"version\":\"18.0.4.2\",\"versionstring\":\"Nextcloud 18.0.4\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-18.0.4.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/18\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=18.0.4\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1587997102",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_mozilla_sync": "mozilla_sync\/appinfo\/remote.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "shareapi_allow_links": "yes",
            "shareapi_allow_public_upload": "yes",
            "shareapi_allow_resharing": "yes",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "298",
            "backgroundwatcher_previous_folder": "785",
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "files_external": {
            "\/InstantUpload": "1442245067",
            "\/owncloud": "1442245067",
            "allow_user_mounting": "no",
            "enabled": "yes",
            "google::705855484989-g8v6a5i72bq85fta41466260752cId": "6776",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_markdown": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.0.3",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.1.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "levels": "11111",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "no",
            "installed_version": "1.3.4",
            "signed": "true",
            "types": ""
        },
        "mozilla_sync": {
            "enabled": "no",
            "installed_version": "1.4",
            "types": ""
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.11",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "news": {
            "enabled": "no",
            "installed_version": "13.1.6",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.3.2",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "enabled": "no",
            "installed_version": "4.1.4",
            "skey": "1495808936160",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "passwords": {
            "SSEv1ServerKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "enabled": "yes",
            "installed_version": "2020.4.1",
            "legacy_api_checkpoint": "1587860560",
            "legacy_last_used": "1582300454",
            "migration\/customFields": "2020.2.0",
            "passwords\/localdb\/type": "hibp",
            "survey\/server\/mode": "2",
            "survey\/server\/notification": "1582224027",
            "survey\/server\/week": "17",
            "types": "",
            "users\/deleted": "[]"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "3.5.2",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "https:\/\/office.rancher.xxxxxxxxx.xxx"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "8.0.8",
            "project_access_invalidated": "1",
            "signaling_servers": "***REMOVED SENSITIVE VALUE***",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "turn_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "last_report": "{\"id\":\"ocdf7c66e1cc\",\"items\":[[\"server\",\"version\",\"18.0.2.2\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.3.16\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.4.12\"],[\"database\",\"size\",99516416],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"activity\",\"2.11.0\"],[\"apps\",\"admin_audit\",\"1.8.0\"],[\"apps\",\"audioplayer\",\"disabled\"],[\"apps\",\"bruteforcesettings\",\"disabled\"],[\"apps\",\"calendar\",\"2.0.2\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"contacts\",\"3.2.0\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"documents\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"federation\",\"1.8.0\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"files_downloadactivity\",\"disabled\"],[\"apps\",\"files_external\",\"1.9.0\"],[\"apps\",\"files_markdown\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"files_versions\",\"disabled\"],[\"apps\",\"files_videoplayer\",\"1.7.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"mozilla_sync\",\"disabled\"],[\"apps\",\"music\",\"disabled\"],[\"apps\",\"news\",\"disabled\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"notes\",\"disabled\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"onlyoffice\",\"disabled\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"passwords\",\"2020.3.1\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"recommendations\",\"disabled\"],[\"apps\",\"richdocuments\",\"disabled\"],[\"apps\",\"search_lucene\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"spreed\",\"8.0.5\"],[\"apps\",\"support\",\"1.1.0\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"tasks\",\"0.12.1\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"theming\",\"1.9.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"user_ldap\",\"disabled\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"stats\",\"num_files\",66335],[\"stats\",\"num_users\",3],[\"stats\",\"num_storages\",27],[\"stats\",\"num_storages_local\",7],[\"stats\",\"num_storages_home\",3],[\"stats\",\"num_storages_other\",17],[\"stats\",\"num_comments\",40],[\"stats\",\"num_comment_markers\",1],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",6],[\"files_sharing\",\"num_shares_user\",1],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",5],[\"files_sharing\",\"num_shares_link_no_password\",5],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",1],[\"files_sharing\",\"permissions_3_1\",\"3\"],[\"files_sharing\",\"permissions_3_4\",\"1\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"files_sharing\",\"permissions_0_31\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1586706804",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.12.2",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "updatenotification": {
            "audioplayer": "2.9.0",
            "bruteforcesettings": "1.0.3",
            "calendar": "2.0.3",
            "contacts": "3.3.0",
            "core": "18.0.4.2",
            "enabled": "yes",
            "files_markdown": "1.0.1",
            "files_rightclick": "0.15.1",
            "installed_version": "1.8.0",
            "mail": "0.7.6",
            "passwords": "2020.4.1",
            "richdocuments": "3.5.2",
            "spreed": "8.0.8",
            "tasks": "0.12.1",
            "theming": "1.4.5",
            "types": "",
            "update_check_errors": "1"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_ldap": {
            "enabled": "no",
            "installed_version": "0.5.0",
            "ocsid": "166061",
            "s01has_memberof_filter_support": "0",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "(objectClass=groupOfNames)",
            "s01ldap_attributes_for_user_search": "(objectClass=posixAccount)",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "dc=poopy,dc=poo",
            "s01ldap_base_groups": "cn=groups,cn=accounts,dc=poopy,dc=poo",
            "s01ldap_base_users": "cn=users,cn=accounts,dc=poopy,dc=poo",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_display_name": "displayname",
            "s01ldap_dn": "uid=owncloud,cn=sysaccounts,cn=etc,dc=poopy,dc=poo",
            "s01ldap_email_attr": "",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(&(|(objectclass=posixGroup)))",
            "s01ldap_group_filter_mode": "1",
            "s01ldap_group_member_assoc_attribute": "memberUid",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "posixGroup",
            "s01ldap_host": "ldap:\/\/freeipa.poopy.poo",
            "s01ldap_login_filter": "uid=%uid",
            "s01ldap_login_filter_mode": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_nocase": "0",
            "s01ldap_override_main_server": "0",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "389",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "1",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "",
            "s01ldap_userlist_filter": "(objectclass=posixAccount)",
            "s02has_memberof_filter_support": "0",
            "s02home_folder_naming_rule": "",
            "s02last_jpegPhoto_lookup": "0",
            "s02ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s02ldap_attributes_for_group_search": "",
            "s02ldap_attributes_for_user_search": "",
            "s02ldap_backup_host": "",
            "s02ldap_backup_port": "",
            "s02ldap_base": "cn=users,cn=accounts,dc=poopy,dc=poo",
            "s02ldap_base_groups": "",
            "s02ldap_base_users": "",
            "s02ldap_cache_ttl": "600",
            "s02ldap_configuration_active": "0",
            "s02ldap_display_name": "displayname",
            "s02ldap_dn": "uid=owncloud,cn=sysaccounts,cn=etc,dc=poopy,dc=poo",
            "s02ldap_email_attr": "",
            "s02ldap_experienced_admin": "0",
            "s02ldap_expert_username_attr": "",
            "s02ldap_expert_uuid_group_attr": "",
            "s02ldap_expert_uuid_user_attr": "",
            "s02ldap_group_display_name": "cn",
            "s02ldap_group_filter": "",
            "s02ldap_group_filter_mode": "0",
            "s02ldap_group_member_assoc_attribute": "uniqueMember",
            "s02ldap_groupfilter_groups": "",
            "s02ldap_groupfilter_objectclass": "",
            "s02ldap_host": "ldap:\/\/freeipa.poopy.poo",
            "s02ldap_login_filter": "",
            "s02ldap_login_filter_mode": "0",
            "s02ldap_loginfilter_attributes": "",
            "s02ldap_loginfilter_email": "0",
            "s02ldap_loginfilter_username": "1",
            "s02ldap_nested_groups": "0",
            "s02ldap_nocase": "0",
            "s02ldap_override_main_server": "",
            "s02ldap_paging_size": "500",
            "s02ldap_port": "",
            "s02ldap_quota_attr": "",
            "s02ldap_quota_def": "",
            "s02ldap_tls": "1",
            "s02ldap_turn_off_cert_check": "0",
            "s02ldap_user_filter_mode": "0",
            "s02ldap_userfilter_groups": "",
            "s02ldap_userfilter_objectclass": "",
            "s02ldap_userlist_filter": "",
            "types": "authentication"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Not relevant here
```
</details>

**Comment by nickvergessen** [comment] 2020-05-04 10:57
I'm not sure we can actually influence this. In Talk 8 we currently just tell the browser "give me the video please" and take what it gives us.

**Comment by biva** [comment] 2020-05-08 13:02
I think we should keep only 1 issue to track this problem and that this one is a duplicate of #1806, don't you think @llamallama ?

**Comment by llamallama** [comment] 2020-05-08 13:21
Sounds good to me @biva

**Comment by nickvergessen** [comment] 2020-05-08 13:37
Yeah sorry I lost the overview about the 250+ issues a bit. I'm currently going through the list to close some of them

**Closed** 2020-05-08 13:37 UTC
Labels: 1. to develop, bug, feature: WebRTC 🚡, feature: call 👥, needs info
