### ISSUE TITLE
Auto-Add new user from circle / group to a chat

### ISSUE THREAD

**Issue by MaxHillebrand** [nextcloud/spreed#5376] opened 2021-03-17 17:19 UTC
**Is your feature request related to a problem? Please describe.**

If first I add users to a circles / groups, and then I create a new chat, I can invite this circle / group to the chat.
But if I add a new user to that circle / group later, it is not automatically added to the chat.

**Describe the solution you'd like**

If I add a user to a circle/group, then that user should automatically be added to all the chat groups that the circle/group was invited to previously.

**Comment by nickvergessen** [comment] 2021-03-17 17:40
Work in progress: https://github.com/nextcloud/spreed/pull/4810

Duplicate of #1329

**Closed by nickvergessen** 2021-03-17 17:40 UTC
Labels: 0. Needs triage, enhancement
