### ISSUE TITLE
Bug: Browser notification fails to dismiss, keeps showing up

### ISSUE THREAD

**Issue by dillfrescott** [nextcloud/spreed#9143] opened 2023-03-23 01:19 UTC
![Screenshot 2023-03-22 211806](https://user-images.githubusercontent.com/56714680/227074077-23cfeb7a-926c-433a-a1ee-6c36bda19a90.png)

Yes I get it already!!!! I'm using Brave! How do I get this message to stop showing up!

**Comment by nickvergessen** [comment] 2023-03-23 04:50
Duplicate of #8966

**Closed** 2023-03-23 04:50 UTC
