### ISSUE TITLE
Ability to export conversation to text file

### ISSUE THREAD

**Issue by mapson01** [nextcloud/spreed#1234] opened 2018-10-02 13:48 UTC
Talk it is not only for collaboration but also the chat conversation is a "minutes of the meeting",. In fact all conversation along time is a "log". When finish the activity the moderator can "close" the chat and before delete it, copy and paste all conversation to a file and an archive "of who say what", converted to PDF and certified signed as a proof of authenticity. Do this task manually is annoying, a export button will  help a lot. It is no seem to be a difficult task, all conversation texts are in database, the idea is to simple export in a CVS format. something like time,user,text.
Chat is more than chat, it is a powerful tool 

Thanks to read it, just a thought. 
cheers

**Comment by nickvergessen** [comment] 2018-10-02 15:06
Duplicate of #232

**Closed by nickvergessen** 2018-10-02 15:06 UTC
