### ISSUE TITLE
Read receipt list info and delivered to list info for group chats (like WhatsApp "Info" function)

### ISSUE THREAD

**Issue by inet-cologne** [nextcloud/spreed#12934] opened 2024-08-10 10:11 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)
Nextcloud 29.0.4
Nextcloud Talk 19.0.7
Nextcloud Talk iOS-App 19.0.8
**Is your feature request related to a problem? Please describe.**
In Nextcloud Talk group chat I'd like to see to whom my message is delivered to but more important who already read the message (message receipt).

**Describe the solution you'd like**
A very important feature I would like to have in **Nextcloud Talk group chats** is to get the read status on user level.
- message delivered to list
- message read from list
I'd like to have the possibility to see which users of a group chat received and which of the users of a group chat read my message.

**Describe alternatives you've considered**
An icon to click to receive the status information.

**Additional context**
We use a group chat to inform band members and discuss details on upcoming schedules. So we have to take care that all messages were delivered correctly and read by the band mates without the need to answer on every single information which make it unreadable any more.
It's like whatsapp "info" function with "delivered to" list and "read from" list in the context menu of a message.

I didn't find anything like my request in the forum or here on Github.

**Comment by SystemKeeper** [comment] 2024-08-10 10:57
Duplicate of https://github.com/nextcloud/spreed/issues/8128

**Closed by SystemKeeper** 2024-08-10 10:57 UTC
Labels: 0. Needs triage, enhancement

**Comment by inet-cologne** [comment] 2024-08-10 11:59
@SystemKeeper : thank's a lot for pointing out the duplicate entry!
