### ISSUE TITLE
Nextcloud Talk can't handle more than 1 guest at the time

### ISSUE THREAD

**Issue by Svarto** [nextcloud/spreed#746] opened 2018-03-24 13:10 UTC
## Steps to reproduce
1. Install Nextcloud Talk
2. Connect to COTURN server on external VPS installed with strukturag/docker-webrtc-turnserver
3. Call in from LAN and have 2 or more guests join via Group Call share link

### Expected behaviour
Both guests and host being able to hear eachother and have a conversation.

### Actual behaviour
Either the current call gets interrupted and everything breaks down, or only the 2 guests can hear eachother but the host can only hear and communicate with the first guest (i.e. he can't hear the new person).

## Browser Firefox

**Microphone available:** yes

**Camera available:** no

**Operating system:** Windows

**Browser name:** Firefox

**Browser version:** 59.0.1 (64-bit)

### Browser log

<details>
ICE failed, your TURN server appears to be broken, see about:webrtc for more details 
connectivityError event received simplewebrtc.js:18115:4 
SimpleWebRTC/< https://nextcloud.svarto-server.com/custom_apps/spreed/js/simplewebrtc.js:18115:4 [100]</WildEmitter.mixin/prototype.emit https://nextcloud.svarto-server.com/custom_apps/spreed/js/simplewebrtc.js:17524:6 [102]</Peer.prototype.handleMessage https://nextcloud.svarto-server.com/custom_apps/spreed/js/simplewebrtc.js:17743:4 SimpleWebRTC/</< https://nextcloud.svarto-server.com/custom_apps/spreed/js/simplewebrtc.js:18041:8 SimpleWebRTC/< https://nextcloud.svarto-server.com/custom_apps/spreed/js/simplewebrtc.js:18038:5 SignalingBase.prototype._trigger https://nextcloud.svarto-server.com/custom_apps/spreed/js/signaling.js:46:4 InternalSignaling.prototype._startPullingMessages/this.pullMessagesRequest<.success</< https://nextcloud.svarto-server.com/custom_apps/spreed/js/signaling.js:431:8 each https://nextcloud.svarto-server.com/core/vendor/core.js:2:2880 InternalSignaling.prototype._startPullingMessages/this.pullMessagesRequest<.success< https://nextcloud.svarto-server.com/custom_apps/spreed/js/signaling.js:422:5 j https://nextcloud.svarto-server.com/core/vendor/core.js:2:26920 fireWith https://nextcloud.svarto-server.com/core/vendor/core.js:2:27738 x https://nextcloud.svarto-server.com/core/vendor/core.js:4:11251 b/< https://nextcloud.svarto-server.com/core/vendor/core.js:4:14765
</details>

## Spreed app

**Spreed app version: 3.1.0

**Custom TURN server configured: yes

**Custom STUN server configured: yes

## Server configuration

**Operating system**: Debian.

**Web server:** Apache

**Database:** MySQL

**PHP version: 7.0

**Nextcloud Version: 13.0.1

**List of activated apps:**

<details>
 PDF viewer
Activity
Collaborative tags
Comments
Deleted files
External storage support
Federation
File sharing
First run wizard
Gallery
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
Share by mail
Talk
Tasks
Text editor
Theming
Update notification
Usage survey
Versions
Video player
Auditing / Logging
Default encryption module
External user support
LDAP user and group backend 
</details>

**Nextcloud configuration:**

<details>
Docker image, no changes in the config from standard
</details>

### Turnserver log
<details>
Mar 24 12:58:48 Debianwebhost turnserver: 1031: session 001000000000000030: new, realm=<myturnserver>, username=<1521982722>, lifetime=600
Mar 24 12:58:48 Debianwebhost turnserver: 1031: session 001000000000000030: realm <myturnserver> user <1521982722>: incoming packet ALLOCATE processed, success
Mar 24 12:58:49 Debianwebhost turnserver: 1032: IPv4. tcp or tls connected to: 212.51.149.199:12093
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000032: realm <myturnserver> user <>: incoming packet message processed, error 401: Unauthorized
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000032: realm <myturnserver> user <1521981703>: incoming packet ALLOCATE processed, error 486: Allocation Bandwidth Quota Reached
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000032: realm <myturnserver> user <1521981703>: incoming packet message processed, error 486: Allocation Bandwidth Quota Reached
Mar 24 12:58:49 Debianwebhost turnserver: 1032: IPv4. tcp or tls connected to: 213.55.184.204:46257
Mar 24 12:58:49 Debianwebhost turnserver: 1032: IPv4. tcp or tls connected to: 213.55.184.204:40287
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000033: realm <myturnserver> user <>: incoming packet message processed, error 401: Unauthorized
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000034: realm <myturnserver> user <>: incoming packet BINDING processed, success
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000033: realm <myturnserver> user <1521981832>: incoming packet ALLOCATE processed, error 486: Allocation Bandwidth Quota Reached
Mar 24 12:58:49 Debianwebhost turnserver: 1032: session 000000000000000033: realm <myturnserver> user <1521981832>: incoming packet message processed, error 486: Allocation Bandwidth Quota Reached
Mar 24 12:58:50 Debianwebhost turnserver: 1033: session 000000000000000029: refreshed, realm=<myturnserver>, username=<1521982722>, lifetime=0
</details>

**Comment by jospoortvliet** [comment] 2018-03-24 14:27
Hmm, this WorksForMe™, even with half a dozen guests - but considering the very first info in the browser log is that your TURN server is broken and you should look at about:webrtc for more details I suggest adding that info here, too, or using it to debug the TURN server ;-)

**Comment by Svarto** [comment] 2018-03-24 16:13
Apologies, I actually laughed reading your answer - I was a bit stupid to not include that.

No idea what this means, tried to google local mis-match but didn't find anything that helped me solve this...

Here goes:
```
((ice/INFO) ICE(PC:1521907487011000 (id=8589934603 url=https://nextcloud.example.com/call/cr4o5j8x)): Skipping STUN server because of link local mis-match

(ice/INFO) ICE(PC:1521907487011000 (id=8589934603 url=https://nextcloud.example.com/call/cr4o5j8x)): Skipping TURN server because of link local mis-match

(ice/INFO) ICE(PC:1521907487011000 (id=8589934603 url=https://nextcloud.example.com/call/cr4o5j8x)): Skipping STUN server because of link local mis-match

(ice/INFO) ICE(PC:1521907487011000 (id=8589934603 url=https://nextcloud.example.com/call/cr4o5j8x)): Skipping TURN server because of link local mis-match

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:IP4:external_turnserver_ip:5733/UDP)

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:IP4:external_turnserver_ip:5733/UDP)

(ice/INFO) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:179 function nr_socket_multi_tcp_create_stun_server_socket skipping STUN with different IP version (4) than local socket (6),

(ice/WARNING) z:/build/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

(ice/WARNING) ICE(PC:1521907487011000 (id=8589934603 url=https://nextcloud.svarto-server.com/call/cr4o5j8x)): failed to create passive TCP host candidate: 3)
```

**Comment by nickvergessen** [comment] 2018-03-26 13:36
Duplicate of #649

But yeah, we can't reproduce this.

**Closed by nickvergessen** 2018-03-26 13:36 UTC
