### ISSUE TITLE
Stripped menu elements when trying to attach a file

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/spreed#3843] opened 2020-06-22 20:27 UTC
## Steps to reproduce
1. Open conversation with someone
2. Click to attach a file
3. Observe stripped menu elements in the cut window.
![image](https://user-images.githubusercontent.com/5199030/85331925-b3794f80-b4df-11ea-952a-670361b2b74a.png)

### Expected behaviour
Should be shown a pop-up window with full strings.

### Actual behaviour
The window is overlapped by left pane, so the elements seem to be cut.

## Talk app

**Talk app version:** 9.0
**Nextcloud version:** 19.0.0.12

**Comment by nickvergessen** [comment] 2020-06-22 20:35
Duplicate of #3604

**Closed by nickvergessen** 2020-06-22 20:35 UTC
Labels: 0. Needs triage, bug
