### ISSUE TITLE
Talk doesn’t work since upgrade from 18.0.3 to 18.0.4

### ISSUE THREAD

**Issue by rubo77** [nextcloud/spreed#3475] opened 2020-05-08 06:52 UTC
Since the update on last Tuesday Talk doesn't work any more across networks. Only within a local network it still works.

I use the default STUN server `stun.nextcloud.com:443` and no TURN server.

in version 18.0.3 Videocalls worked fine with those settings, also across different Networks.

I tried it in two different unrelated NC installations, everywhere I get the same error:

    Could not establish a connection with at least one participant. A TURN server might be needed for your scenario.

## Talk app

**Talk app version:**  8.0.8

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Debian/Docker

**Web server:** Nginx

**Database:** Maria

**PHP version:**  7.3.17

**Nextcloud Version:** 18.0.4

**List of activated apps:**

<details>
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - carnet: 0.20.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 0.8.2
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - news: 14.1.6
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - mindmaps
  - recommendations
  - socialsharing_email
  - user_ldap

```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "next.markus-steinmetz.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/next.markus-steinmetz.com",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "mail_template_class": "\\OC\\Mail\\EMailNoLogoTemplate",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "debug": false,
        "app_install_overwrite": [
            "calendar",
            "files_retention",
            "spreed",
            "mindmaps",
            "socialsharing_email"
        ],
        "has_rebuilt_cache": true,
        "trashbin_retention_obligation": "auto, 3"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "yes",
            "installed_version": "3.7.0",
            "types": "logging"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "14"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.3",
            "types": ""
        },
        "carnet": {
            "enabled": "yes",
            "installed_version": "0.20.0",
            "types": "filesystem"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1534165912.9829",
            "lastcron": "1588918506",
            "lastupdateResult": "[]",
            "lastupdatedat": "1588912202",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "theming.variables": "23294b57ab5ba694c30b298bc9715829",
            "updater.secret.created": "1564701765",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.8.2",
            "types": "dav"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_mindmap": {
            "enabled": "no",
            "installed_version": "0.0.15",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_group_share_enabled": "yes",
            "installed_version": "1.10.1",
            "lookupServerEnabled": "yes",
            "outgoing_server2server_group_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "levels": "11111",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.3.4",
            "types": ""
        },
        "maps": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "lastAddressLookup": "1583158540",
            "types": "filesystem"
        },
        "mindmaps": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        },
        "news": {
            "enabled": "yes",
            "installed_version": "14.1.6",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "polls": {
            "enabled": "yes",
            "installed_version": "1.4.3",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "socialsharing_email": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "types": ""
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "8.0.8",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "last_report": "{\"id\":\"oc7nfa33b0ow\",\"items\":[[\"server\",\"version\",\"18.0.3.0\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.3.16\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.4.12\"],[\"database\",\"size\",53411840],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"activity\",\"2.11.0\"],[\"apps\",\"admin_audit\",\"1.8.0\"],[\"apps\",\"announcementcenter\",\"3.7.0\"],[\"apps\",\"apporder\",\"0.9.0\"],[\"apps\",\"bruteforcesettings\",\"1.6.0\"],[\"apps\",\"calendar\",\"2.0.2\"],[\"apps\",\"carnet\",\"0.20.0\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"contacts\",\"3.2.0\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"deck\",\"0.8.0\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"federation\",\"1.8.0\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"files_external\",\"1.9.0\"],[\"apps\",\"files_mindmap\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"files_retention\",\"1.7.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"files_versions\",\"1.11.0\"],[\"apps\",\"files_videoplayer\",\"1.7.0\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"mail\",\"1.1.4\"],[\"apps\",\"maps\",\"0.1.6\"],[\"apps\",\"mindmaps\",\"disabled\"],[\"apps\",\"news\",\"14.1.3\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"polls\",\"1.3.0\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"recommendations\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"socialsharing_email\",\"disabled\"],[\"apps\",\"spreed\",\"8.0.7\"],[\"apps\",\"support\",\"1.1.0\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"tasks\",\"0.12.1\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"theming\",\"1.9.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"stats\",\"num_files\",4103],[\"stats\",\"num_users\",2],[\"stats\",\"num_storages\",5],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",2],[\"stats\",\"num_storages_other\",2],[\"stats\",\"num_comments\",113],[\"stats\",\"num_comment_markers\",1],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",2],[\"files_sharing\",\"num_shares_user\",0],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",2],[\"files_sharing\",\"num_shares_link_no_password\",2],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_3_1\",\"1\"],[\"files_sharing\",\"permissions_3_15\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1588375806",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.12.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "14",
            "color": "#C92B78",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "name": "Nextcloud",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "updatenotification": {
            "apporder": "0.9.0",
            "bruteforcesettings": "1.5.0",
            "calendar": "2.0.3",
            "carnet": "0.21.1",
            "contacts": "3.3.0",
            "core": "18.0.4.2",
            "deck": "1.0.0",
            "enabled": "yes",
            "files_mindmap": "0.0.15",
            "files_rightclick": "0.15.1",
            "installed_version": "1.8.0",
            "mail": "1.3.4",
            "maps": "0.1.6",
            "news": "14.1.7",
            "polls": "1.3.0",
            "socialsharing_email": "1.0.6",
            "spreed": "8.0.8",
            "tasks": "0.12.2",
            "types": "",
            "update_check_errors": "0"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

Discussion here: https://help.nextcloud.com/t/talk-doesnt-work-since-upgrade-from-18-0-3-to-18-0-4/80811

**Comment by nickvergessen** [comment] 2020-05-08 07:16
Well `stun.nextcloud.com` is not a TURN server but a STUN server, so remove it from there.
If that doesn't fix it, you need to set up a TURN server as per https://nextcloud-talk.readthedocs.io/en/latest/TURN/

**Comment by rubo77** [comment] 2020-05-08 22:00
Sure, I meant Stun server. 

Before the update, it worked without turn server

**Comment by D-Jy-lab** [comment] 2020-05-10 13:50
我也遇到了这个问题，我设置了stun和turn服务器，但语音和视频仍无法工作。
[EN]  I also had this problem, I set up stun and turn servers, but voice and video still didn't work.

**Comment by rubo77** [comment] 2020-05-11 06:32
@D-Jy-lab did it work fine art your NC too before the last upgrade?

**Comment by rubo77** [comment] 2020-05-11 14:03
Update:

I found out, that on some internet access connections it works through the net, without turn server, just the default stun server.

So I guess, that it could have something to do with the IPv6 connectivity of your internet access.

Could someone please explain what are the prerequisites to a successful connection without turn Server?

**Comment by nickvergessen** [comment] 2020-05-11 16:38
Well, check the intro on https://nextcloud-talk.readthedocs.io/en/latest/TURN/

**Comment by nickvergessen** [comment] 2020-05-11 16:39
But this then sounds like you're turn server is not correctly configured.
So this is not a bug in talk and i will close this issue

**Closed by nickvergessen** 2020-05-11 16:39 UTC
Labels: 0. Needs triage, bug, needs info
