### ISSUE TITLE
Avatar menu only open a time, when we try to open again, don't work

### ISSUE THREAD

**Issue by vitormattos** [nextcloud/spreed#9055] opened 2023-03-13 17:46 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. go to the message list of a room
2. Pass your mouse over the avatar of an user
3. You will see a tree dots menu
4. Click at menu
5. You will see the menu
6. Click at other place
7. The menu don't will open again

### Expected behaviour
See the menu every when I try to open

### Actual behaviour
Avatar menu didn't work when we try to open two times at the same message

## Talk app

**Talk app version:** `17.0.0-dev`

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 110.0.1 (64-bit)

**Comment by nickvergessen** [comment] 2023-03-13 20:22
Duplicate of #9006

**Closed** 2023-03-13 20:22 UTC
Labels: 0. Needs triage, bug
