### ISSUE TITLE
[FEATURE REQUEST] "Guest" label in Public Call's needs some sync/link?

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/spreed#690] opened 2018-03-07 19:42 UTC
While experimenting with a public call/room I shared the link to two other connections on mobile devices with Chrome Incognito windows. Each participant successfully edited their own name and it displayed correctly in their web-cam space. The chat labels for them remained Guest and the Participants section of the right-side panel also remained labeling them each as Guest. If I were to decide to kick one out of the call/room, I wouldn't know which one to boot.

Also along those lines, it would be wonderful if each unauthenticated participant got prompted to write a name for themselves before loading the page, and it was tested for uniqueness before they could enter it in as their label.

**Comment by nickvergessen** [comment] 2018-03-08 13:39
Duplicate of #551

**Closed by nickvergessen** 2018-03-08 13:39 UTC

**Comment by WNYmathGuy** [comment] 2018-03-08 17:25
@nickvergessen Thank you. :)
