### ISSUE TITLE
Infochannel / one-way 

### ISSUE THREAD

**Issue by Smith-fms** [nextcloud/spreed#6781] opened 2022-01-14 18:24 UTC
A top-down message function would be useful. A kind of info channel where not every user can write. Only moderators as an example.
Especially within the club communication this would be a simplification!
Is this already possible? I haven't found anything yet.

We have a user group where every user is in it. If only the group admin could write here, that would be perfect.

Greetings from germany!

**Comment by nickvergessen** [comment] 2022-01-17 15:07
We introduced permissions recently and I guess a permission whether the chat can be used sounds like the next useful step

**Comment by nickvergessen** [comment] 2022-04-06 14:00
Duplicate of https://github.com/nextcloud/spreed/issues/3886

**Closed by nickvergessen** 2022-04-06 14:00 UTC
Labels: 1. to develop, enhancement, feature: chat  💬, feature: settings ⚙️
