### ISSUE TITLE
Guest chat removable by other logged in user

### ISSUE THREAD

**Issue by Millesimus** [nextcloud/spreed#4707] opened 2020-12-01 11:31 UTC
## Steps to reproduce
1. Create group chat with guest link using account A
2. Open guest link with account B logged in
3. Click "leave chat" with account B

### Expected behaviour
The respective group chat should be simply removed from the Talk overview page of account B, but still present for account A and accessible via the share link.

### Actual behaviour
The respective group chat is deleted completely, i.e. also for the original creator (account A).

## Talk app

**Talk app version:** 9.0.6

## Server configuration

**Nextcloud Version:** 19.0.5

**Comment by PVince81** [comment] 2020-12-03 09:03
I couldn't reproduce this with NC 20.0.0 and Talk 10.0.1.

maybe this got fixed in a more recent version ?

**Comment by Millesimus** [comment] 2020-12-21 20:45
Thanks for your input. I have just reproduced the error with NC 20.0.4 and Talk 10.0.4, so it is still present.

**Closed** 2021-01-05 17:52 UTC
Labels: 0. Needs triage, bug

**Comment by Millesimus** [comment] 2021-01-09 09:02
Can confirm issue is gone in Talk 10.0.5 on NC 20.0.4.

**Comment by nickvergessen** [comment] 2021-01-11 14:44
Thanks!
