### ISSUE TITLE
Web notifications, supposedly disallowed technique

### ISSUE THREAD

**Issue by honzapatCZ** [nextcloud/spreed#5096] opened 2021-02-06 18:29 UTC
So the latest issue was closed, because "Evil browsers have some list of allowed sites or whatever", while I really tried, I searched thru the source of chromium and didnt find any, closest was this: https://github.com/chromium/chromium/blob/master/third_party/blink/renderer/core/html/media/autoplay_policy.cc
But thats normal policy that can be changed by the user the same as notifications at: chrome://settings/content/sound
And even that occurs only if the user didnt interact with the website at all, while if you have opened the messenger in some tab, you probably clicked thru some conversations as this is mainly to avoid spam websites that play crazy sounds and scams on load.

**Comment by nickvergessen** [comment] 2021-02-09 14:55
Closing as duplicate of #760 so the info is not distributed across multiple reports.

**Closed by nickvergessen** 2021-02-09 14:55 UTC
Labels: 0. Needs triage, enhancement
