### ISSUE TITLE
Unable to set camera for multi camera pc. Eg Surface tablet

### ISSUE THREAD

**Issue by MarkPartlett** [nextcloud/spreed#676] opened 2018-02-27 10:53 UTC
## Steps to reproduce
1. Start Nextcloud Talk Call

### Expected behaviour
your image is recorded and displayed

### Actual behaviour
Wrong camera is displayed , there should be a camera selector. eg. Cam1/Cam2

**Microphone available:** yes

**Camera available:** yes but wrong one.

**Operating system:** Windows as client

**Browser name:** Chrome

**Browser version:** Version 64.0.3282.186 

## Spreed app

**Custom TURN server configured:** yes ( private coturn on AWS) 

**Custom STUN server configured:** yes ( private coturn on AWS)

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**Nextcloud Version:**  13.0.0

**Comment by nickvergessen** [comment] 2018-03-09 14:25
Duplicate of https://github.com/nextcloud/spreed/issues/358

**Closed by nickvergessen** 2018-03-09 14:25 UTC
