### ISSUE TITLE
UI Feedback when invite people via email

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/spreed#3090] opened 2020-03-16 01:02 UTC
If you are in a talk room and want to invite people by mail. You first search for users and then click on the e-mail-address you want to sent the link to.

There is currently no feedback, that the link was sent by mail. The dialog simply closes. 
Users then send the mail again, again and again... because they don't know it it was sent...

**Describe the solution you'd like**
Maybe show a message in the chat, that the link was sent to this email address or show a note in the "Participants" dialog.
![image](https://user-images.githubusercontent.com/16019165/76714785-6d1a9480-6729-11ea-9be3-a660384396cb.png)
Maybe it would also make sense (to follow up #3089) to show all invited people/email addresses in the list. The same view like sharing a file via mail... and also give a moderator the option to revoke access, if a user was invited with a custom link/password.

**Comment by nickvergessen** [comment] 2020-03-17 16:44
Duplicate of #1902

**Closed by nickvergessen** 2020-03-17 16:44 UTC
Labels: 0. Needs triage, enhancement
