### ISSUE TITLE
Log level for chat

### ISSUE THREAD

**Issue by mw80** [nextcloud/spreed#4297] opened 2020-10-06 07:17 UTC
### Expected behaviour
Only real chat messages should be visible. Possibility to change the log level?

### Actual behaviour
Currently a lot of administrative messages are display. (Started a call, left a call, etc.)

**Comment by nickvergessen** [comment] 2020-10-06 09:19
Duplicate of #1148

**Closed by nickvergessen** 2020-10-06 09:19 UTC
