### ISSUE TITLE
unified search for old message doesn't lead to actual message

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/spreed#8381] opened 2022-11-19 20:55 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Use unified search to find a known, old message in a Talk chat (say, hundreds of messages ago)
2. Click on that message
3. URL in address bar becomes something like `https://nextcloud.example.com/call/abcdefgh#/message_210492`

### Expected behaviour
The message's chat is opened (`abcdefgh`) and the message returned by unified search (`210492` in this case) is highlighted.

### Actual behaviour
The message's chat is opened and **only shows the most recent messages, not the message clicked on from the search** (again, unless it is one of the last few messages of the chat). I don't see an easy way to read old messages from the Talk web UI other than scrolling or running queries directly against the backend database.

Seems like this would only be a problem where some messages are not loaded, say, in a chat with lots of messages.

## Talk app

**Talk app version:** 14.0.6

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes, (private / self-hosted coturn / seems to work OK)

**Custom STUN server configured:** yes, `stun.nextcloud.com:443`

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** 64-bit Ubuntu 22.04 LTS desktop

**Browser name:** Firefox

**Browser version:** 107.0 (64-bit)

## Server configuration

**Operating system**: 64-bit Ubuntu 20.04 LTS server

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0.25

**Nextcloud Version:** 24.0.7

**Comment by nickvergessen** [comment] 2022-11-19 21:38
Duplicate of #6046

**Closed** 2022-11-19 21:39 UTC
Labels: 0. Needs triage, bug

**Comment by meonkeys** [comment] 2022-11-19 22:51
> Duplicate of #6046

Much obliged, thank you! I searched a bit and failed to find that existing issue.
