### ISSUE TITLE
No name shown for user with webcam on

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#5815] opened 2021-06-21 12:25 UTC
## Steps to reproduce
1. Start a group call
2. Have someone who transmits a static black image as "webcam"

### Expected behaviour

I still see who the participant is

### Actual behaviour

![Bildschirmfoto von 2021-06-21 14-23-48](https://user-images.githubusercontent.com/1374172/122761366-74b9d900-d29c-11eb-8074-c5359a15dfe2.png)

Also on hover I see only the two icons.

## Talk app

**Talk app version:** the one on c.nc.com

**Comment by nickvergessen** [comment] 2021-06-21 13:26
Can not reproduce. The name is shown for me with and without the HPB.
But note that the name fades out when a video stream is received.

Anymore details on your call? All logged in users?

**Comment by ChristophWurst** [comment] 2021-06-21 13:48
It was our call earlier. That user was @miaulalala. She could also not hear me, while I could and everyone else. So this is possible a side effect of another bug, but I don't know how to trigger it. Anything to check for if I encounter it another time?

**Comment by miaulalala** [comment] 2021-06-21 13:51
To add, @ChristophWurst's picture and avatar was in a "loading" state a long time for me, which is when I couldn't hear him.

**Comment by nickvergessen** [comment] 2021-06-21 14:19
Okay, then I guess it is because the peer never connected.
If the peer could not be resolved we can also not map it to the participants as we don't have the session id?

cc @danxuliu

**Comment by nickvergessen** [comment] 2021-06-21 17:13
@miaulalala @ChristophWurst in case it happens again, would be nice to have the console output of both sides :)

**Comment by danxuliu** [comment] 2021-06-22 00:23
> If the peer could not be resolved we can also not map it to the participants as we don't have the session id?

Even if the Nextcloud session ID was known for that participant [the name would have come only from the signaling due to a bug](https://github.com/nextcloud/spreed/issues/5832) :shrug: But independently of that something strange is going on.

Unless it was explicitly done by publishing a black image with v4l2-loopback or something like that (but I guess you would have mentioned it :-P ), a black video is a disabled video (or a video not being sent, but this issue looks like a disabled video). When a participant has video disabled the video is replaced with the avatar in Talk UI. But Talk does not check the video stream; it listens to `videoDisabled` messages sent by the other participant through the signaling and data channels and, when they are received, it shows the avatar instead of the video.

Initially the video is assumed to be enabled, so when a participant joins a call the actual video state is sent (with the HPB it is not known whether a remote participant has connected or not, so the messages are sent several times in an increasing interval). Besides the video state the initial data includes the audio state and the nick of the participant.

Before a connection is established with the HPB to receive data from a remote participant a loading spinner is shown on that participant. As there is no loading spinner, but there is a black video and no nick, my guess is that a connection was established with the remote participant, but the remote participant had video disabled and, for some reason, the initial state was not properly sent.

Checking the HPB logs I found a very unusual message (which may require some changes in our Janus setup, but that is a different matter). When @miaulalala tried to connect to Janus to receive @ChristophWurst media Janus failed to get its own IP address. This explains why @miaulalala saw @ChristophWurst's avatar in loading state and could not hear him: the connection was not established.

However, in that case an ICE failure should have been eventually triggered by the browser, which would have caused Talk to try to connect again. Strangely, there are no traces of a reconnection in the HPB logs.

Could the problem be that Janus not sending the ICE candidates somehow triggered an error which was not properly handled and also aborted the loop that should have sent the initial state? Very very unlikely, but I have seen weirder errors :-P

In any case, as mentioned by @nickvergessen this can not be reproduced in a normal way. It looks like a strange corner case :shrug: Anyway I will make Janus fail to get its own IP address and see what happens.

**Comment by danxuliu** [comment] 2021-06-22 17:14
> Anyway I will make Janus fail to get its own IP address and see what happens.

It works fine. If Janus fails to get its own IP address at the time of the request it will just use the public IP address that was found [when Janus was started](https://github.com/meetecho/janus-gateway/blob/422e26dacd34ee22083ae77673fcc5af7a3b098f/ice.c#L1119-L1120), so in the case of our HPB server it makes no difference.

Janus waits 5 seconds to get its own IP address, and Talk waits 10 seconds before trying to reconnect with a receiver. It could happen that Janus takes a bit long to answer, so Talk tries to reconnect before receiving the answer, and that can happen several times in a row. But even in that case it will eventually connect, and while it is not connected a loading spinner is shown on the participant.

So... I do not know what happened :shrug:

**Comment by nickvergessen** [comment] 2021-07-05 09:32
So closing for now. If it happens again try to save the browser console.

**Closed by nickvergessen** 2021-07-05 09:32 UTC
Labels: 1. to develop, bug, feature: call 👥, feature: frontend 🖌️, regression
