### ISSUE TITLE
Public room, but without showing old messages for guests

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/spreed#6744] opened 2022-01-04 15:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Intro:
Again a small NGO. Connected civicrm/wordpress with nextcloud via https://apps.nextcloud.com/apps/user_sql. From wordpress/civicrm, user choose there groups whom are mapped to nextcloud talk rooms.

Issue:
We've got a regional group in Berlin. So there is also a talk room Berlin for chatting in between our appointments. It would make perfect sense to just use that room for appointments of that group. But not everybody is logged in at Nextcloud, also, from time to time we expect some guests. So we need to make that room public.

**Describe the solution you'd like**
But if this room is public, everybody could read old messages. But you don't want other ppl/ngos read your old messages.

So, the solution would be an option to hide old messages, when you join as guest.

**Describe alternatives you've considered**
The alternative is to create another room in Talk, just for the appointments of that berlin group. But then I also have to deal with additional rooms for all the other regional groups (and also the working groups). Big overload!

I could also just create appointment rooms, but that is also dirty.
a) ppl are already in that room and get calls for things that are not their concerns.
b) ppl are not in that room, and find it hard to find it, also don't get a call automatically

Also then I just have to empty that appointment room from time to time manually.

Searched for, but haven't found an open issue.

**Comment by nickvergessen** [comment] 2023-08-23 15:23
CLosing as duplicate of https://github.com/nextcloud/spreed/issues/7462

**Closed by nickvergessen** 2023-08-23 15:23 UTC
Labels: 1. to develop, enhancement, feature: chat  💬
