### ISSUE TITLE
"Schedule send" for chat messages

### ISSUE THREAD

**Issue by kirmaha** [nextcloud/spreed#6441] opened 2021-11-03 09:20 UTC
**Is your feature request related to a problem? Please describe.**
For some reasons, users could need to send a message with a specific time of delivery.
E.g. : _This evening, I want to inform my collegue about something important. That collegue always keeps his phone on, and I don't want to disturb him during his off time -> I can write a message that will be delivered tomorrow morning at 8 AM._
This feature can also be used many other ways, e.g. as a _task reminder you set for other people_.

**Describe the solution you'd like**
When you write a message, a right click on the _send_ button allow you to access _sending options_ including **send as scheduled message** (and others :  #6257 ). It opens a dialog where the user sets the day and time of delivery. When the user validates it, the message is added to a queue.
- The message is sent but not delivered yet : it means that the message will be delivered on time, whether the user is online or not.
- The queue must be accessible for each conversation, to allow the user to cancel or modify the message at any moment before the delivery time.

**Describe alternatives you've considered**
Rather than a queue for each conversation, all the pending messages could be accessed in one common window (one for each sender rather than one for each conversation).

**Comment by nickvergessen** [comment] 2021-11-18 22:25
Duplicate of #3954

**Closed by nickvergessen** 2021-11-18 22:25 UTC
Labels: 1. to develop, enhancement, feature: chat  💬
