### ISSUE TITLE
automatically unfurl / preview / inline media when chat message includes a link

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/spreed#4705] opened 2020-11-30 22:28 UTC
When I post a link to media that can be previewed (either it is publicly accessible or chat participants have access to it), it would be great to be able to optionally unfurl / preview / inline the linked-to media.

For example, if I paste in a chat "test 123 http://example.com/test.jpg" and if test.jpg is a valid JPEG image, it could be automatically previewed right in the chat. Similarly for internal Nextcloud file links and other linked-to media.

**Comment by PVince81** [comment] 2020-12-01 07:57
duplicate of https://github.com/nextcloud/spreed/issues/3156

**Closed by PVince81** 2020-12-01 07:57 UTC
Labels: 0. Needs triage, enhancement

**Comment by meonkeys** [comment] 2020-12-01 21:58
Ah, thank you! I didn't find that dup when I searched earlier. I'll add my thumbs up there.
