### ISSUE TITLE
Incompatibility with NC18 / Flow

### ISSUE THREAD

**Issue by Rello** [nextcloud/spreed#2644] opened 2019-12-29 08:55 UTC
the following error is thrown when accessing the Flow settings in NC18 Beta 4

```
flow.js?v=453566be:221 
Uncaught TypeError: Cannot read property 'registerOperator' of undefined
```

**Comment by Rello** [comment] 2019-12-29 08:55
https://github.com/nextcloud/server/issues/18514

**Comment by nickvergessen** [comment] 2019-12-29 12:54
Are you running the talk alpha from github or the master branch?

**Comment by Rello** [comment] 2019-12-29 13:23
Hi,
the one from the appstore.
I am using an out of the box NC18b4

if you say the current version is not compatible yet and the issue is known, we can close this ticket.

**Comment by nickvergessen** [comment] 2019-12-29 16:22
I think I uploaded alpha 2 to the app store (its not visible thou). Anyway we will be compatible with 18 on the release day because it will be part of the blogpost 😅

**Closed by nickvergessen** 2019-12-29 16:22 UTC
Labels: 0. Needs triage, bug

**Comment by Rello** [comment] 2019-12-30 07:42
Hey @nickvergessen 
i just checked. 8.0.0-alpha.2 is installed on my side

**Comment by juliushaertl** [comment] 2019-12-30 08:23
I cannot reproduce the issue. @Rello Could you check in the javascript console if `window.OCA.WorkflowEngine.registerOperator` is defined once the workflow settings page has been loaded completely?

**Comment by Rello** [comment] 2019-12-30 09:31
hallo @juliushaertl 

strange:
![Screenshot 2019-12-30 at 10 09 18](https://user-images.githubusercontent.com/13385119/71575951-1b317d80-2aef-11ea-91b0-cb5310ede59f.png)

its coming from `apps/workflowengine/src/workflowengine.js`
I put a breakpoint at `window.OCA.WorkflowEngine = Object.assign({}, OCA.WorkflowEngine, {` but it is not triggered.

**Comment by Rello** [comment] 2019-12-30 09:57
Solved by updating Chrome. Old version 65 not compatible
