### ISSUE TITLE
Advertise App For Mobile

### ISSUE THREAD

**Issue by EliterScripts** [nextcloud/spreed#2943] opened 2020-02-11 18:11 UTC
**Is your feature request related to a problem? Please describe.**
I find your mobile website for Nextcloud Talk very frustrating. I understand the web app is really designed for computers, but I need to be able to send people who have never used Nextcloud before, and be able to video chat on their mobile devices.

**Describe the solution you'd like**
It's probably hard to completely redevelop a web interface for mobile devices, so I would like it if the Nextcloud Talk app was advertised. "Open with Nextcloud Talk" button would go a really long way, similar to if you opened YouTube in the browser on a mobile phone, it would try to get you to use the app.

**Describe alternatives you've considered**
The alternative is to make the web interface for mobile better.

**Additional context**
Also, while I'm at it, it would be nice to be able to open a public chatroom without logging in, using the Nextcloud Talk app.

EDIT:
I would also like it if when you hit "Open with Nextcloud Talk", it opens the app and skips the credentials screen if it is a public chatroom, so you can easily join public chat rooms.

**Comment by nickvergessen** [comment] 2020-02-11 18:18
Duplicate of #1088

**Closed by nickvergessen** 2020-02-11 18:18 UTC
Labels: 0. Needs triage, enhancement
