### ISSUE TITLE
Open shared documents in a popup

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#2367] opened 2019-10-28 03:09 UTC
When I share a document in a conversation it would be best if that document is opened in a popup somehow so that everyone can quickly preview it and edit it. Maybe only allow this for the Text files that are integrated with NC. And document ones for those who have collabora enabled. It makes it way easier than simply sending the users to the folder path where that file is.

Or, maybe have 2 functions: 1 - folder/file path and 2 - open file in popup.

**Comment by nickvergessen** [comment] 2019-11-14 21:06
Duplicate of https://github.com/nextcloud/spreed/issues/2002#issuecomment-511742924

**Closed by nickvergessen** 2019-11-14 21:06 UTC
Labels: 0. Needs triage, enhancement
