### ISSUE TITLE
Allow guests to easily attract attention on a specific location of a shared screen by clicking

### ISSUE THREAD

**Issue by Fuzl** [nextcloud/spreed#1217] opened 2018-09-27 10:02 UTC
## Steps to reproduce
1. Launch a meeting with several attendees
2. User A shares his screen
3. User B wants to show all attendees a specific location on User A's screen

### Expected behaviour
- User B clics on the screen and all attendees see a colored arrow on that location. The arrow stays on that location for a few seconds then disappears.

Well done for the work ! Great to see it evolve !

**Comment by nickvergessen** [comment] 2018-09-27 10:15
I guess this counts as duplicate of #449

**Closed by nickvergessen** 2018-09-27 10:15 UTC
