### ISSUE TITLE
[Feature request] Option to deselect Enter key for sending chat message.

### ISSUE THREAD

**Issue by bushrang3r** [nextcloud/spreed#6282] opened 2021-09-24 05:00 UTC
Currently, the 'Enter' button is pressed to send a message, however, this causes problems with some languages like Japanese which often requires the Enter button to be pressed to confirm the selection of single words, which can result in incomplete sentences  being sent. 

It would be nice to have the option to deselect the use of the Enter key to send messages, and to use a dedicated send button instead (as the Nextcloud Talk Android app does). This is how Slack currently works.

**Comment by nickvergessen** [comment] 2021-09-24 08:28
Duplicate of #3268

**Closed by nickvergessen** 2021-09-24 08:28 UTC
