### ISSUE TITLE
Set username BEFORE join a call in talk as guest

### ISSUE THREAD

**Issue by TheRaven500** [nextcloud/spreed#5389] opened 2021-03-21 16:37 UTC
**Is your feature request related to a problem? Please describe.**
When a Guest is joining a meeting/chat, his username is "Guest" and he has to change it after joining.

**Describe the solution you'd like**
Guests should be asked for username BEFORE joining the meeting/chat.

**Describe alternatives you've considered**
Of course, you can easily change username after joining, but it would be better to ask this before. Not? :-)

**Comment by nickvergessen** [comment] 2021-03-21 17:36
Duplicate of #855

**Closed by nickvergessen** 2021-03-21 17:36 UTC
Labels: 0. Needs triage, enhancement
