### ISSUE TITLE
Show progress 'bar' when drag-dropping files into Talk

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/spreed#3731] opened 2020-06-03 12:00 UTC
I realized that there is none of this, and at times, if the file is large, you cannot see if it is doing anything if you drag and drop a file, or when you copy paste an image. That would be useful. A simple "upload" progress. Cheers!

**Comment by nickvergessen** [comment] 2020-06-03 12:13
Duplicate of #3423

**Closed by nickvergessen** 2020-06-03 12:13 UTC
Labels: 0. Needs triage, enhancement
