### ISSUE TITLE
Searching for WebRTC client

### ISSUE THREAD

**Issue by jalalsfs** [nextcloud/spreed#1157] opened 2018-08-26 06:46 UTC
Hello there!,
Thank you for amazing app, which I use it on my cellphone and laptop.
 Actually I don't have an issue with the app, but what I am looking for is to use this service (chat) within my desktop/laptop's app as a client without using web browser.
I want any app can use this (webrtc) that runs in desktop,
I am using Linux (Fedora 28).
Thank you.

**Comment by nickvergessen** [comment] 2018-08-26 08:05
Duplicate of #1100

**Closed by nickvergessen** 2018-08-26 08:05 UTC
