### ISSUE TITLE
Message input line

### ISSUE THREAD

**Issue by Kitanit** [nextcloud/spreed#9683] opened 2023-06-02 10:57 UTC
NC 26
Talk 16.0.4

Internal text in Ukrainian is outside the input line when you turn on the call

https://github.com/nextcloud/spreed/assets/65107731/11e471ee-1101-4788-9d5e-df9700dab95e

**Comment by nickvergessen** [comment] 2023-06-02 11:01
Duplicate of https://github.com/nextcloud/nextcloud-vue/issues/4173

**Closed by nickvergessen** 2023-06-02 11:01 UTC
Labels: 0. Needs triage, bug
