### ISSUE TITLE
Images are not displayed in public chats for non-logged-in user

### ISSUE THREAD

**Issue by SlavikCA** [nextcloud/spreed#2309] opened 2019-10-13 08:41 UTC
## Steps to reproduce
1. Create public chat
2. Publish image (photo) into conversation
3. Open that chat in incognito window

### Expected behaviour
Expected, that message and images will be visible

### Actual behaviour
Only text messages are visible. Grayboxes displayed instead of images.

## Browser
- Chrome 77
- Operating system: Windows

This is how bug looks like in the browser:

![image](https://user-images.githubusercontent.com/6293679/66713024-2bd91f80-ed5a-11e9-84ab-8656c06fd652.png)

And this is how same chat room looks like for logged-in user:

![image](https://user-images.githubusercontent.com/6293679/66713042-5e831800-ed5a-11e9-8b58-25b4b1c73bea.png)

## Talk app
**Talk app version:** 7.0.0
**Custom TURN server configured:** no
**Custom STUN server configured:** no

## Server configuration
**Operating system**: Ubuntu
**Web server:** Nginx
**Database:** MySQL
**PHP version:** 7.3
**Nextcloud Version:** 17.0.0

**Comment by SlavikCA** [comment] 2019-10-13 08:42
welcome to test / reproduce that issue with my public room:

https://cloud.aidcim.org/index.php/call/j9nc9sdu

**Comment by nickvergessen** [comment] 2019-11-14 21:00
Yeah, the preview endpoint we try to use does not work publically atm.

I guess this will not be fixed until #1811 

So I will close it as a duplicate of that.

**Closed by nickvergessen** 2019-11-14 21:00 UTC
Labels: 0. Needs triage, bug
