### ISSUE TITLE
Description missing when switching to a conversation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#4881] opened 2021-01-04 08:50 UTC
## Steps to reproduce
1. Create 2 conversations
2. Set a description in conv1
3. Switch to conv2
4. Switch back to conv1

### Expected behaviour
You see the description

### Actual behaviour
No description shown

**Comment by PVince81** [comment] 2021-01-11 10:12
duplicate of https://github.com/nextcloud/spreed/issues/4809

**Closed by PVince81** 2021-01-11 10:12 UTC
Labels: 1. to develop, bug, feature: frontend 🖌️
