### ISSUE TITLE
Error : Connexion to server lost. Try to reconnect.

### ISSUE THREAD

**Issue by VincentMillot** [nextcloud/spreed#11502] opened 2024-01-31 14:07 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Dedicated server + Proxmox VE 8.1 + pfSense
2. NextCloud et Talk UP to date
3. HAproxy create certificate and redirect 443 to 80

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Talk app

**Talk app version: 17.1.5 (see apps admin page: `/index.php/settings/apps`)

**Custom Signaling server configured: no

**Custom TURN server configured:no

**Custom STUN server configured:no

## Browser

**Microphone available: yes

**Camera available: yes

**Operating system: Windows 11 Pro 23h2

**Browser name: Firefox

**Browser version: 122

## Server configuration

Just a minor bug. When I leave a talk page open, after a while a message appears at the top right "Connection to server lost. Try to reconnect". This does not impact connectivity at all, this message appears but Talk continues to work perfectly.

**Operating system**: Ubuntu

**Web server: SNAP up to date

**Database: SNAP up to date

**PHP version: SNAP up to date

**Nextcloud Version: 27.1.4
![Capture d'écran 2024-01-31 150515](https://github.com/nextcloud/spreed/assets/58065834/78dce6c9-d4b4-4405-b073-3dc09aef1bb2)

**Comment by SystemKeeper** [comment] 2024-01-31 17:06
Seems like a duplicate of https://github.com/nextcloud/spreed/issues/11216 ?

**Closed** 2024-01-31 21:26 UTC
Labels: 0. Needs triage, bug
