### ISSUE TITLE
Reading counters

### ISSUE THREAD

**Issue by albertooka** [nextcloud/spreed#1907] opened 2019-06-13 18:59 UTC
I would like you to add the function of being able to know if someone has read your messages. It's a very useful feature that WhatsApp has, but that Nextcloud Talk does not have ...

**Comment by nickvergessen** [comment] 2019-06-27 13:14
Duplicate of https://github.com/nextcloud/spreed/issues/1012

**Closed by nickvergessen** 2019-06-27 13:14 UTC
Labels: enhancement, feature: api, feature: chat
