### ISSUE TITLE
Feature request: Delivery and Read Receipts

### ISSUE THREAD

**Issue by alex9434** [nextcloud/spreed#2441] opened 2019-11-09 12:13 UTC
**Is your feature request related to a problem? Please describe.**
Currently I am not able to see whether the recipient has received the message and read the message

**Describe the solution you'd like**
It would be nice to have indications on each message of the status. I like the logic from other chat systems to mark on each message a) sent, b) delivered and c) read.

**Comment by nickvergessen** [comment] 2019-11-09 12:23
Duplicate of #1012

**Comment by alex9434** [comment] 2019-11-09 12:24
Sorry, did not see this. You are right it is a duplicate.

**Closed by nickvergessen** 2019-11-09 12:23 UTC
Labels: 0. Needs triage, enhancement
