### ISSUE TITLE
Add conversations joined via link from other servers to own rooms

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/spreed#908] opened 2018-05-17 12:18 UTC
with talk-android it is already possible to join conversations via a link (on other instances)
it would be nice, if these conversations/rooms could be kept in the conversations list (marked as such). 
maybe these conversations could later be automatically converted to federated ones.
see nextcloud/talk-android#176

**Comment by nickvergessen** [comment] 2018-06-21 11:09
The thing is, currently we remove the users again so they have to reenter the password, when joining the next time.

**Comment by violoncelloch** [comment] 2018-06-21 12:28
Hmm
I don't know how federated calls will be handled, but it would be nice if at least as soon as federated calls are supporter calls joined via links could be turned into federated calls

**Comment by PVince81** [comment] 2020-12-08 09:59
closing in favor of https://github.com/nextcloud/spreed/issues/4717 which has more details how to reproduce and next steps

**Comment by PVince81** [comment] 2020-12-08 10:00
wait, this was about conversations on remote servers... reopening and edited title to make it clearer

**Comment by nickvergessen** [comment] 2020-12-08 12:24
The issue is tracked at #21 *cough*

**Comment by nickvergessen** [comment] 2021-02-19 13:54
This is now achieved with the "open conversations" in Talk 11

**Closed by nickvergessen** 2021-02-19 13:54 UTC
Labels: 1. to develop, enhancement, feature: api 🛠️
