### ISSUE TITLE
Shortcut to create new conversation

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#4721] opened 2020-12-07 16:26 UTC
Not sure if it is just me. But often I'm not 100% sure if a room for a topic already exists or not. Therefore the first thing I do is, I search for it. If I don't find anything I have to use the "+" button to create a new conversation.

I wonder if it wouldn't be a nice feature if I could create a new room, right from the search like in this mockup:

![image](https://user-images.githubusercontent.com/1589737/101376445-e3ab8380-38b0-11eb-9ab6-dc6c156c16f0.png)

The benefit here would be, that I have already entered the room name in the search. So we could skip the first screen of the wizard (or at least pre-fill the room name) and the user doesn't have to enter the name a second time.

What do you think?

cc @nextcloud/designers

**Comment by nickvergessen** [comment] 2020-12-07 16:59
Duplicate of #4318

**Closed by nickvergessen** 2020-12-07 16:59 UTC
Labels: 0. Needs triage, enhancement
