### ISSUE TITLE
Connection can not be established without camera permission

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7048] opened 2022-03-24 08:52 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. As user A create a room with group 1 where user B is a member of
2. As user A set custom permissions for user B only change to remove the camera permission
3. As user A start a call
4. As user B try to join the call

### Expected behaviour
User B can join and talk

### Actual behaviour
User B is disconnecting and connecting all the time

## Talk app

**Talk app version:** master

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes - using fake stream

**Camera available:** yes - using fake stream

**Operating system:** Ubuntu

**Browser name:** Firefox

**Browser version:** 96

### Browser log
![Bildschirmfoto von 2022-03-24 09-51-04](https://user-images.githubusercontent.com/213943/159878444-87e14843-c39b-4afc-b6e9-3f668dd9d432.png)

**Comment by nickvergessen** [comment] 2022-03-24 08:52
cc @danxuliu

**Comment by danxuliu** [comment] 2022-03-30 03:35
With the HPB this is a regression (ironically) introduced in https://github.com/nextcloud/spreed/pull/6992 Without the HPB this was happening on v13.0.0 already :see_no_evil: In both cases the problem is the same ([only audio or only video permissions are not properly handled](https://github.com/nextcloud/spreed/blob/8c7461590e726f927e9266ef794f4e5d2c55f3a0/src/utils/webrtc/webrtc.js#L985-L997)) and it will be implicitly fixed by the changes in https://github.com/nextcloud/spreed/pull/7034

**Closed** 2022-04-04 10:47 UTC
Labels: 1. to develop, bug, regression, feature: call 👥
