### ISSUE TITLE
 Talk - no chat no call 

### ISSUE THREAD

**Issue by htttito** [nextcloud/spreed#4519] opened 2020-11-03 09:36 UTC
Hi !
System: ubuntu 20.04
Nextcloud 20.0.1

My error:
In Talk (spreed) i can´t chat or phone or something.
(My TURN-Server is working well)

`    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/html/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main()

    /var/www/html/nextcloud/ocs/v1.php - line 88:

    OC\Route\Router->match()

    /var/www/html/nextcloud/ocs/v2.php - line 24:

    require_once("/var/www/ht ... p")

Verursacht durchError: Object of class DateTime could not be converted to string

    /var/www/html/nextcloud/lib/private/Comments/Manager.php - line 786:

    OC\DB\QueryBuilder\QueryBuilder->execute()

    /var/www/html/nextcloud/lib/private/Comments/Manager.php - line 749:

    OC\Comments\Manager->insertQuery()

    /var/www/html/nextcloud/lib/private/Comments/Manager.php - line 725:

    OC\Comments\Manager->insert()

    /var/www/html/nextcloud/apps/spreed/lib/Chat/ChatManager.php - line 151:

    OC\Comments\Manager->save()

    /var/www/html/nextcloud/apps/spreed/lib/Chat/Changelog/Manager.php - line 80:

    OCA\Talk\Chat\ChatManager->addChangelogMessage()

    /var/www/html/nextcloud/apps/spreed/lib/Chat/Changelog/Listener.php - line 53:

    OCA\Talk\Chat\Changelog\Manager->updateChangelog("*** sensiti ... *")

    /var/www/html/nextcloud/apps/spreed/lib/Chat/Changelog/Listener.php - line 37:

    OCA\Talk\Chat\Changelog\Listener->preGetRooms()

    /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 251:

    OCA\Talk\Chat\Changelog\Listener::OCA\Talk\Chat\Changelog\{closure}("*** sensiti ... *")

    /var/www/html/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 73:

    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()

    /var/www/html/nextcloud/lib/private/EventDispatcher/EventDispatcher.php - line 86:

    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()

    /var/www/html/nextcloud/apps/spreed/lib/Controller/RoomController.php - line 164:

    OC\EventDispatcher\EventDispatcher->dispatch()

    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Talk\Controller\RoomController->getRooms()

    /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/html/nextcloud/lib/private/AppFramework/App.php - line 157:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/html/nextcloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main()

    /var/www/html/nextcloud/ocs/v1.php - line 88:

    OC\Route\Router->match()

    /var/www/html/nextcloud/ocs/v2.php - line 24:

    require_once("/var/www/ht ... p")`

Can anyone help?!

**Comment by PVince81** [comment] 2020-11-03 12:39
might be similar to https://github.com/nextcloud/spreed/issues/4463

**Comment by htttito** [comment] 2020-11-03 12:51
maby the same, but there is no solution...

**Comment by nickvergessen** [comment] 2020-11-03 18:39
Duplicate of #4463

**Closed by nickvergessen** 2020-11-03 18:39 UTC
