### ISSUE TITLE
Let users delete their messages anytime (remove 6 hour limit)

### ISSUE THREAD

**Issue by Qi2nR9uw** [nextcloud/spreed#6678] opened 2021-12-08 21:50 UTC
**Is your feature request related to a problem? Please describe.**
I find it quite uncomfortable that you can't delete messages after 6 hours. Why is this even a feature? Seems very anti-privacy having messages permanently stored on the server and after looking around it appears I am far from the only person who agrees.

**Describe the solution you'd like**
An option for all users to be able to delete their messages at any time without ever having a limit of when they can remove them. To spice it up, it would be neat to have expiring messages where they simply auto delete after a certain amount of time.

Let storing messages forever be a thing of the past :(

**Comment by nickvergessen** [comment] 2021-12-11 22:44
Duplicate of #6132
See more information in #4861 and all the other issues about it

**Closed by nickvergessen** 2021-12-11 22:44 UTC
Labels: 0. Needs triage, enhancement

**Comment by illetschko** [comment] 2022-03-09 12:36
I just want to mention, that I also would like to be able to delete **my** messages **anytime**.
And I see it like Terrox from #6132:
> I want to delete messages to clean up the chat records for various reasons.

**Comment by nousernameavailableanymore** [comment] 2022-04-10 01:08
I m sorry, but what is this nonsense?
Are there any technical reasons for having such a seemingly arbitrary timeframe?
Let people delete their messages as is common practice in all other chat applications.

**Comment by matbyl** [comment] 2022-04-17 20:40
I tried to find the motivation behind this design decision to understand it better but could not find anything concrete. What is the the rationale behind this decision?

We are also in need of removing messages that are older than 6 hours. Imo it's reasonable to always be able to remove your own messages (even though it might be locally stored somewhere) to prevent others from reading the messages in the future.
