### ISSUE TITLE
grouping conversation threads by tags

### ISSUE THREAD

**Issue by Lionel-cl** [nextcloud/spreed#4665] opened 2020-11-23 20:31 UTC
**Is your feature request related to a problem? Please describe.**
I have a long list of conversation threads.
Are there any plan to group conversation threads by tags / folders? 

**Describe the solution you'd like**
This would make it possible to bring together the conversation threads and organize the left part of the screen at convenience in order to have a better visibility of the different threads.
Conversation threads grouped under the same tag could be indented.
It seems very useful to me when there are many conversation threads open.
Each user could define their own tags / folders. eg: projects, major themes, milestones,...

**Describe alternatives you've considered**
I didn't find alternatives

**Comment by nickvergessen** [comment] 2020-11-27 09:04
Something like #2448 ?

**Comment by nickvergessen** [comment] 2020-11-27 09:04
Duplicate of #2448

**Closed by nickvergessen** 2020-11-27 09:04 UTC
Labels: 0. Needs triage, enhancement

**Comment by Lionel-cl** [comment] 2020-11-27 14:29
yes but more simple, like https://github.com/nextcloud/spreed/issues/3527 or emails with gmail
