### ISSUE TITLE
Direct Download Option for files posted to the chat

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#5967] opened 2021-07-07 12:40 UTC
If a document which can be edited/viewed by Nextcloud, Talk opens the editor/viewer when clicking on the document.

Sometimes people want to download the file. E.g. I'm in a call with a external person and want to quickly share a document with them for their local use.

Having a "Download" option in the "..." menu for attachments would be a nice enhancement.

**Comment by nickvergessen** [comment] 2021-07-07 12:47
I thought we did in the last released, but it was only a link to jump to the files app

**Comment by biva** [comment] 2021-07-21 08:42
I agree with this proposal and I would like to see also the other way around: if the default setting is to download the file instead of editing it, I would like to have the option to edit it directly from the chat room. To summarise, it would be great to have the 3-dots menu with the following options:
- Edit / Open in OnlyOffice (or any available editor for the corresponding file type)
- Download
- Open the folder containing the file

It's easier to be clear with pictures: this is what I see today: 
![image](https://user-images.githubusercontent.com/9964305/126458061-d6b4f401-d697-4172-a615-622f2b0f0ff6.png)

And this is what would be great:
![image](https://user-images.githubusercontent.com/9964305/126458995-d6865f9b-07d5-4440-bfdb-964456996035.png)

**Comment by nickvergessen** [comment] 2021-11-18 22:10
Duplicate of #4614

**Closed by nickvergessen** 2021-11-18 22:10 UTC
Labels: 1. to develop, bug, enhancement, feature: chat  💬, feature: frontend 🖌️
