### ISSUE TITLE
Talk does user search each time You click on "Choose a person"

### ISSUE THREAD

**Issue by muppeth** [nextcloud/spreed#715] opened 2018-03-20 15:38 UTC
## Steps to reproduce
1. Click Choose a person 

### Expected behaviour
Spreed should immedietly show option to Start public call or new group call

### Actual behaviour
Spreed seems to be doing paged search first. In case of large LDAP databases this will most likely fail. Also if SharingAPI `shareapi_allow_share_dialog_user_enumeration` is set to `no` this search should not take place.
The only way around it is to type a name of existing user to be able to setup public call.

### Server log (data/nextcloud.log)
<details>
```

"user_ldap","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=&perPage=20&itemType=call&_=1521559819132","message":"getGroups(): read 2 at offset 0 (limit: 20)"
</details>

**Comment by nickvergessen** [comment] 2018-03-22 15:19
Duplicate of #115

**Closed by nickvergessen** 2018-03-22 15:19 UTC
