### ISSUE TITLE
Emoji picker is moving messages around and not placed the same every time

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/spreed#7990] opened 2022-09-22 20:48 UTC
![image](https://user-images.githubusercontent.com/7427347/191847948-0b0e6513-f12e-49a9-9aa6-b1b9ef04fecb.png)

Also cut off at the bottom. It happens when the emoji picker doesn't have enough space to the top to be displayed.

**Comment by nickvergessen** [comment] 2022-09-22 20:50
I guess the problem is there is not enough space above or beyond the actions to show the picker...
Either we reduce the size or we need to make it float instead of being linked to the button

**Comment by nickvergessen** [comment] 2022-09-23 13:57
Fixed by https://github.com/nextcloud/spreed/pull/7999

**Closed by nickvergessen** 2022-09-23 13:57 UTC
Labels: 1. to develop, bug, medium, papercut, feature: frontend 🖌️, feature: reactions 👍
