### ISSUE TITLE
Add burgermenu to left navigation

### ISSUE THREAD

**Issue by newhinton** [nextcloud/spreed#3214] opened 2020-03-31 12:07 UTC
**Is your feature request related to a problem? Please describe.**
When starting a conversation or a call, the conversation list on the left side takes considerable space. Currently there is no way to hide it for the user.
See #3082 

**Describe the solution you'd like**

A burgermenu, similar to the one for the participant list on the right side would allow the user to hide this menu. 

**Additional context**
The only "drawback" is that this slightly breaks the guideline for nextcloud, since the left bar is normally not hideable when enough space is available.

**Comment by georgehrke** [comment] 2020-04-01 09:17
Possible duplicate of https://github.com/nextcloud/server/issues/15831

**Comment by nickvergessen** [comment] 2020-05-08 09:53
Done as per above

**Closed by nickvergessen** 2020-05-08 09:53 UTC
Labels: 1. to develop, design, enhancement, feature: frontend 🖌️
