### ISSUE TITLE
Add feature to include image in conversation group

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7298] opened 2022-05-03 15:04 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently chat groups do not have the feature to include an image in it, this feature could make it easier for the user to be able to more easily differentiate which group in the left sidebar

**Describe the solution you'd like**
Add feature to include image in conversation group

**Comment by nickvergessen** [comment] 2022-05-03 15:08
Duplicate of #927

**Closed by nickvergessen** 2022-05-03 15:08 UTC
Labels: 0. Needs triage, enhancement
