### ISSUE TITLE
Can't delete public file conversations

### ISSUE THREAD

**Issue by BRadHoc** [nextcloud/spreed#6637] opened 2021-11-30 23:54 UTC
## Steps to reproduce
1. Share a file on nextcloud
2. View the shared file as a guest
3. Start a conversation in Talk in the sidebar
4. Post some obscene messages that you wouldn't want other viewers of the file seeing
5. See as a logged in admin, there is no way of deleting these messages. 

### Expected behaviour
Tell us what should happen

> Admins should be able to delete the conversation &/or individual messages.

### Actual behaviour
Tell us what happens instead

> Nothing.

**Comment by nickvergessen** [comment] 2021-12-01 03:23
Duplicate of #2236

**Closed by nickvergessen** 2021-12-01 03:23 UTC
Labels: 0. Needs triage, bug
