### ISSUE TITLE
Horizontal scrolling in call with ~15 participants in Safari

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/spreed#3411] opened 2020-04-28 14:16 UTC
## Steps to reproduce
1. Have a call with 15+ participants
2. Scroll sideways in Safari (only noticed there and didn't tested)
3. There is a white area to the right of the black call window which scrolls in and is caused by your own avatar being too far to the right (video and screen sharing button were there)

### Expected behaviour

My avatar including the buttons is to the left of the border of the window

cc @danxuliu @ma12-co @nickvergessen

**Comment by nickvergessen** [comment] 2020-04-28 14:20
Duplicate of #1056 ?

**Comment by MorrisJobke** [comment] 2020-04-28 14:28
> Duplicate of #1056 ?

I would not say so. It looks like this (cut out tabs, URL and left sidebar):

![Bildschirmfoto 2020-04-28 um 15 11 44](https://user-images.githubusercontent.com/245432/80499368-2f866980-896d-11ea-8236-ed1dd0ec6f40.png)

**Comment by nickvergessen** [comment] 2020-04-28 16:21
Yeah on firefox they dont overlap and outscroll, but just overflow into unreachable

**Comment by nickvergessen** [comment] 2020-05-07 14:18
Closing as duplicate of #1056

**Closed by nickvergessen** 2020-05-07 14:18 UTC
Labels: 0. Needs triage, bug, design
