### ISSUE TITLE
Unread messages dot/counter unreadable

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#12242] opened 2024-04-29 12:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call
2. The other person messages you
3. Look at the top right

### Expected behaviour

Readable counter or bubble or whatever the blue thing should be :laughing: 

### Actual behaviour

![image](https://github.com/nextcloud/spreed/assets/1374172/e699a3a8-537d-452a-87ae-0a36ed2e0e38)

## Talk app

**Talk app version:** (see apps administration page: `/index.php/settings/apps`)

**Custom Signaling server configured:** yes/no and version (see  Talk administration settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see Talk administration settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see  Talk administration settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/Mac/...

**Browser name:** Firefox/Chrome/Safari/...

**Browser version:** 124/125/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 8.1/8.2/8.3

**Nextcloud Version:** (see administration page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by DorraJaouad** [comment] 2024-04-29 15:09
I couldn't reproduce it but it seems styles issue. Can you please check from which style source `background` or `background-color` are applied for the counter?

**Comment by ChristophWurst** [comment] 2024-04-29 15:23
Will inspect when it happens again :+1:

**Comment by ChristophWurst** [comment] 2024-04-29 15:24
If it makes a difference, it showed when Talk could not connect (eternal *Connect ...* screen) when I started the call

**Comment by Antreesy** [comment] 2024-06-28 09:13
Reproduced and fixed on main: https://github.com/nextcloud/spreed/pull/12387#discussion_r1657286596

**Closed** 2024-06-28 13:29 UTC
Labels: 1. to develop, bug, feature: chat  💬, feature: frontend 🖌️, feature: call 📹
