### ISSUE TITLE
Nextcloud Talk (Spreed) Doesn't Work With Firefox Developer Edition (70) @Disroot Cloud

### ISSUE THREAD

**Issue by TakuyaSama** [nextcloud/spreed#2246] opened 2019-09-27 18:31 UTC
## Steps to reproduce
1. Launch Firefox Developer Edition/Beta (70).
2. Open the Nextcloud Spreed implementation.
3. Do a call with someone.

### Expected behaviour
The other person should listen me and i should listen it.

### Actual behaviour
The other person/people doesn't listen me and i don't listen anything. Also, each person icon keeps with the loading animation forever. It feels like there'd be slowdowns without any reasonable reason.

## Browser

**Microphone available:** Yes

**Camera available:** No

**Operating system:** Arch Linux

**Browser name:** Firefox

**Browser version:** 70 (Developer Edition, Beta State)

** More browser information: ** The most strict Privacy Protections available, a few add-ons installed, but disabled the ones that i think could interfere (uBlock Origin, HTTPS Everywhere, Privacy Badger, Decentraleyes).

## Extra info
It works fine with Firefox Stable (69), without much configuration (but with the same configuration at Privacy Protections), without any add-on, also on Falkon (Chromium-based KDE web browser), without any further configuration either.

A Disroot worker is helping me with the triage, trying to replicate the bug at his system, but after install Firefox Developer Edition (70), the 4 add-ons i commented, he says it works without any issue, which is making me wonder why is this happening.

## Server Information
Disroot Cloud (not my own deployment)

**Comment by nickvergessen** [comment] 2019-09-27 18:46
Anything in the browser console?

**Comment by furai** [comment] 2019-10-04 11:56
I'm having issues with newst Firefox Developer Edition as well, but for me after a while lower half of received stream freezes until the sending party focuses their browser that shares the screen to me. Then it instantly unfreezes.

**Comment by danxuliu** [comment] 2019-11-14 19:46
@TakuyaSama I have been testing this (on my development instance, not the Disroot one) and everything worked fine with Firefox 70.0.1.

If the loading icon is shown on a participant that means that there is no established connection with that participant.

Could you test with Firefox 70 but with the default configuration? Close Firefox, rename the _/home/yourUserName/.mozilla_ directory to, for example, _/home/yourUserName/.mozilla.bak_ and start Firefox again. Once you finish the tests close Firefox, rename _/home/yourUserName/.mozilla.bak_ back to _/home/yourUserName/.mozilla_ and next time you start Firefox everything will be like before ;-)

If Firefox 70 with the default configuration worked fine then the issue is in your current configuration or extensions. If not then it could be that something changed in Firefox 70 that makes your system unreachable from other computers (maybe related to https://bugzilla.mozilla.org/show_bug.cgi?id=1554976, although seems unlikely).

Also, try to do a call with yourself. Start a call and then join the call from a private window. Did it work?

In any case, please copy here the browser console when no connection can be established. Also, open `about:webrtc` in Firefox, expand the connection (if there is more than one connection clean the history and try to do a call again; then refresh `about:webrtc` after waiting for a while for the connection to fail) and copy the table with the candidates.

Finally, could you also check if Talk in Disroot uses a TURN server? You can do that by typing `OCA.SpreedMe.app.signaling.settings.turnservers.length` in your browser console (while in Talk); the result is the number of configured TURN servers.

@furai That seems to be a different problem, so please open a new issue and provide as much information as possible (at least, Nextcloud, Talk and browser versions and operating system of both the sending and receiving party, and whether it happens in other environments too or not; if possible, a list of steps that can be used to reproduce the problem).

However, note that what you describe sounds very much like a problem in the browser or the operating system itself and not something caused by (and neither fixable in) Nextcloud Talk. You can also test in a different WebRTC platform, like [Jitsi](https://meet.jit.si/), to see if the problem happens there too or not (but keep in mind that even if it happens there that does not automatically mean that it is caused by Talk ;-) ).

**Comment by nickvergessen** [comment] 2020-05-08 14:35
Closing as this seems to not be an issue with recent Firefox at least.

**Closed by nickvergessen** 2020-05-08 14:35 UTC
Labels: 1. to develop, bug, needs info
