### ISSUE TITLE
When making unified search, the URL given in the results is not pointing to the message

### ISSUE THREAD

**Issue by Dvbnhbq** [nextcloud/spreed#7507] opened 2022-07-01 09:42 UTC
## Steps to reproduce
1. Open the Nextcloud dashboard, click the unified search icon and type in a search pattern, matching some existing Talk message. Some results show up.
2. Click on the message item in the results list. 

### Expected behaviour
The exact message should be displayed in the Talk chat window. 

### Actual behaviour
The Talk chat window shows up with the latest messages displayed instead of the seeking one.

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Ubuntu, Android

**Browser name:** Qutebrowser, Chrome

**Browser version:** 2.5.2, 103.0.5060.70

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
14.0.2

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk`)
no

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk`)
no

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**Nextcloud Version:** (see admin page)
24.0.2

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment] 2022-07-01 09:44
Duplicate of  #6046

**Closed by nickvergessen** 2022-07-01 09:44 UTC
