### ISSUE TITLE
Cannot delete file/share conversation created by guest

### ISSUE THREAD

**Issue by shalak** [nextcloud/spreed#9776] opened 2023-06-13 22:40 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Create a public share link
2. Open it in incognito
3. Join conversation
4. Go back to your user, try to delete the conversation

### Expected behaviour
Owner of the share should be able to delete the conversation

### Actual behaviour
Owner can only leave the conversation. Even admin cannot delete it

## Talk app

**Talk app version:** 16.0.4

**Custom Signaling server configured:** yes

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

**Nextcloud configuration:**

nextcloud-aio, 26

**Comment by shalak** [comment] 2023-06-14 14:33
Huh, I just noticed that if I follow your flow, I'm also unable to delete the conversation as a user1.

I'm assuming that by "Create public room" you mean this:
<img width="468" alt="image" src="https://github.com/nextcloud/spreed/assets/1536554/97bdf935-51b1-4410-b6fe-95f939052a26">

**Comment by SystemKeeper** [comment] 2023-06-14 14:34
Ah no, I was on a totally wrong track here. So you create a talk room from a public file share?

**Comment by shalak** [comment] 2023-06-14 14:35
> Ah no, I was on a totally wrong track here. So you create a talk room from a public file share?

Yes, I'm creating a public share link

Where can I get the list of possible `occ` commands for `talk`? Or just a command to list the rooms?

**Comment by SystemKeeper** [comment] 2023-06-14 14:38
Okay, I'll try to reproduce it this way.

You can find a list here: https://nextcloud-talk.readthedocs.io/en/latest/occ/ 
Also you can disable this on a public share in the settings

**Comment by shalak** [comment] 2023-06-14 14:44
>  Also you can disable this on a public share in the settings

You mean this one? The `Allow conversations on public shares for files`?

<img width="426" alt="image" src="https://github.com/nextcloud/spreed/assets/1536554/073852ef-d23f-4ae4-8f7e-81a6642094d9">

But I want the guests to be able to create, just want to cleanup, if needed.

> You can find a list here: https://nextcloud-talk.readthedocs.io/en/latest/occ/

Huh, there's no `talk:room:list` - how do I identify the room to be deleted?

**Comment by nickvergessen** [comment] 2023-06-20 13:19
Related issues:
- https://github.com/nextcloud/spreed/issues/2284
- https://github.com/nextcloud/spreed/issues/2236

**Comment by nickvergessen** [comment] 2023-06-20 13:20
Just for the record, I think as soon as everyone left the conversation, it should be deleted.

**Comment by nickvergessen** [comment] 2023-08-23 13:09
Closing as duplicate of https://github.com/nextcloud/spreed/issues/2236

**Closed by nickvergessen** 2023-08-23 13:09 UTC
Labels: 0. Needs triage, bug, needs info
