### ISSUE TITLE
Add ability to react to messages

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2461] opened 2019-11-13 16:09 UTC
So I was talking with Frank a minute ago and he he'd like to have the ability to react to messages in the new talk app like others do (Slack, Microsoft teams, Mattermost, github, ... ). I think it could be a nice addition. What do you think @nextcloud/designers-talk @nextcloud/talk? Any idea on how we could implement this? 

![Screenshot_20191113_170609](https://user-images.githubusercontent.com/26852655/68781587-4e4fa880-0638-11ea-9cbf-a7ed8ab883fb.png)

**Comment by nickvergessen** [comment] 2019-11-13 16:12
Duplicate of https://github.com/nextcloud/spreed/issues/1920

**Closed by nickvergessen** 2019-11-13 16:12 UTC
Labels: 0. Needs triage, enhancement
