### ISSUE TITLE
Send email invitations to users without nextcloud account

### ISSUE THREAD

**Issue by rwolfdev** [nextcloud/spreed#6659] opened 2021-12-05 09:33 UTC
**Is your feature request related to a problem? Please describe.**
I use Spreed as a conference center for meetings with my clients and partners. Not all of them has a account inside my nextcloud instance, so it would be nice if I could invite them via email. 

**Describe the solution you'd like**
I would wish a solution where I can add some email adresses where I can invite other people to my meeting. The mail should contain informationen about the time, the link to the meeting and a description which I can set if needed. 

Also a storable calender entry should be sent with. 

Really nice would it be, if I can create different "invitation templates" which allow me to specify email content (text), for example with placeholders like [meeting_link], [meeting_time], [meeting_creator] etc.

It could be combined with the mail app which is provided by nextcloud.

**Describe alternatives you've considered**
The simplest solution is to add the posibility to add multiple email adresses to the onboarding process of the meeting, all the other functionalities are extras.

**Comment by nickvergessen** [comment] 2021-12-05 11:58
You can add emails in the right side bar after you created the conversation.
But yeah adding it to the creation screen is mostlikely more expected

**Comment by nickvergessen** [comment] 2024-10-23 04:53
Duplicate of #4966 and #4937

**Closed by nickvergessen** 2024-10-23 04:53 UTC
Labels: 1. to develop, enhancement, feature: meetings 📅
