### ISSUE TITLE
Message menu bugos on scrolling

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#5615] opened 2021-05-17 10:29 UTC
## Steps to reproduce

1. Open a conversation.
2. Write multiple messages.
3. Click on the Meatballs menu of the messages for some message.
4. Scroll through the messages with the mouse wheel.

The contents of the Meatballs menu appear in the upper left corner of the page.

When you click the mouse:

![obraz](https://user-images.githubusercontent.com/47037905/118473962-d79eda00-b70a-11eb-8305-048d75a78a90.png)

After scrolling the mouse wheel:
![obraz](https://user-images.githubusercontent.com/47037905/118474160-0cab2c80-b70b-11eb-817b-938c655e3148.png)

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.2.1

## Browser

**Browser name:** Firefox/Chrome/...
Firefox

**Browser version:** 50.1/55/...
88.0.1

## Server configuration

**Nextcloud Version:** (see admin page)
21.0.1

**Comment by nickvergessen** [comment] 2021-07-05 09:31
@marcoambrosini this feels quite weird and I can still reproduce it. Maybe you can have a look?

**Comment by marcoambrosini** [comment] 2021-07-05 13:28
How should we handle this? Is it ok if we close the menu upon scrolling?

**Comment by nickvergessen** [comment] 2021-07-05 13:37
Sounds brutal but better than a menu going wild.
But maybe you can first find out what the problem is? It sounds like a missing/wrong boundaries element or something alike.

**Comment by szaimen** [comment] 2021-07-05 13:55
Sounds like https://github.com/nextcloud/server/issues/23872 to me... (So needs to be fixed in the vue components probably)

**Comment by nickvergessen** [comment] 2022-09-16 14:57
Shouldn't happen anymore since quite a while

**Closed by nickvergessen** 2022-09-16 14:57 UTC
Labels: 1. to develop, bug, papercut, feature: frontend 🖌️
