### ISSUE TITLE
3.1 talk update version firefox camera is not working.

### ISSUE THREAD

**Issue by gurussia** [nextcloud/spreed#662] opened 2018-02-15 00:12 UTC
HI guys. IN the moment i update new nextcloud talk application and when i go to see what is new it comment: Error while accessing microphone & camera

Yestarday i try it when was old version and it works camera and micrphone was working by default. Include it was seeking to see what changelog was in new nextcloud talk application and there is no update info include in nextcloud.com application store there is no info what is new in updates. So guys if you don;t want to comment what is new in nextcloud version comment me and if i have time and rememer i will write changelogs

**Comment by jookk** [comment] 2018-02-15 06:36
I can not confirm. 
Tried accessing Nextcloud Talk by Firefox 58.0.2 (Windows) and Talk accessed camera and mic with no problems. Even tried to call with no problems

**Comment by Ivansss** [comment] 2018-02-15 09:18
@gurussia is the camera/microphone being used by another browser/app at the same time?
Can you please provide us with which FF version and OS you are using?

**Comment by gurussia** [comment] 2018-02-15 22:28
didn't you read what i write. I;'m gonna explain again. WHen i install latest talk version and try make video call i refresh web browser include i close firefox latest version and open nextcloud and log again, after that i try open nextcloud talk and it comment webcam and micrphone is not working. SO i go to permissions and there is no block, it was allowed. jookk when you want to make video call do you have configured your coturn. developer of nextcloud talk application make internal coturn that be automatically configured

**Comment by gurussia** [comment] 2018-02-16 00:00
I remember to look in developer console and it comment this:

QMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Access to microphone & camera failed 
MediaStreamError
constraint: ""
message: "The object can not be found here."
name: "NotFoundError"
stack: ""
__proto__: MediaStreamErrorPrototype
constraint: Getter
<get>: get constraint()
length: 0
name: "get constraint"
__proto__: ()
apply: apply()
length: 2
name: "apply"
__proto__: ()
apply: function apply()
arguments: null
bind: function bind()
call: function call()
caller: null
constructor: function Function()
length: 0
name: ""
toSource: function toSource()
toString: function toString()
Symbol(Symbol.hasInstance): undefined
__proto__: Object { … }
arguments: null
bind: function bind()
call: function call()
caller: null
constructor: function Function()
length: 0
name: ""
toSource: function toSource()
toString: function toString()
Symbol(Symbol.hasInstance): undefined
__proto__: Object { … }
message: Getter
<get>: get message()
length: 0
name: "get message"
__proto__: function ()
name: Getter
<get>: get name()
length: 0
name: "get name"
__proto__: function ()
stack: ""
__proto__: {…}
constructor: function Error()
message: ""
name: "Error"
stack: Getter & Setter
toSource: function toSource()
toString: function toString()
__proto__: Object { … }
webrtc.js:629:4
Error while accessing microphone & camera:  The object can not be found here.
webrtc.js:646:5
CONNECTED
simplewebrtc.js:18008:4
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://yourdomain.com/core/vendor/core.js?v=62869209-0
Source Map URL: purify.min.js.map
[Learn More]

**Comment by nickvergessen** [comment] 2018-02-16 08:50
> Yestarday i try it when was old version and it works camera and micrphone was working by default. Include it was seeking to see what changelog was in new nextcloud talk application and there is no update info include in nextcloud.com application store there is no info what is new in updates. So guys if you don;t want to comment what is new in nextcloud version comment me and if i have time and rememer i will write changelogs

The changelog is in the appstore: https://apps.nextcloud.com/apps/spreed/releases?platform=13#13
and in this repository: https://github.com/nextcloud/spreed/releases/tag/v3.1.0

There were no changes related to getting media permissions.

Also please watch your language. 🙄

**Comment by gurussia** [comment] 2018-02-16 11:01
nickvergessen Also please watch your language. 🙄

the true is true. i can't do nothing.

**Comment by nickvergessen** [comment] 2018-03-12 14:32
Closing because we can not reproduce

**Closed by nickvergessen** 2018-03-12 14:32 UTC
Labels: needs info
