### ISSUE TITLE
across server calling

### ISSUE THREAD

**Issue by NavnDK** [nextcloud/spreed#3715] opened 2020-05-31 01:18 UTC
**Is your feature request related to a problem? Please describe.**
i would like the ability to call other nextcloud servers with the talk app insted of haveing everyone on the same server you can have a group of people what what i mean is

family A has a nextcloud server
and
family B has a nextcloud server
and family A wants to call family B

so what i want is some kind of bridge
**Describe the solution you'd like**
you goto the talk app and you click add server then enter the ip / domain of the other server with a key of some kind that the admin generates by clicking add server but insted of clicking login thay click generate server then once loged in everyone from the server that loged in can see everyone from the other server and call them
**Describe alternatives you've considered**
just a normal voip server but it would be nice to have build into nextcloud
**Additional context**

**Comment by nickvergessen** [comment] 2020-05-31 05:53
Duplicate of #32

**Closed** 2020-05-31 05:53 UTC
Labels: 0. Needs triage, enhancement
