### ISSUE TITLE
Returning from search to conversation list is cumbersome

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2796] opened 2020-01-19 12:59 UTC
## Steps to reproduce
1. Search for a conversation
2. Do the stuff
3. Want to go back to the conversation list

### Expected behaviour
You can easily clear the search or go back.

### Actual behaviour
You have to manually clear the search field.

A simple clear X `icon-close` in the search would be nice. :) If there’s text in it, it would show, and tapping it would clear it and reset the list.

![talk no x for search input](https://user-images.githubusercontent.com/925062/72681419-a9cc6580-3ac3-11ea-8fe9-2331b1f53765.png)

**Comment by nickvergessen** [comment] 2020-01-19 13:39
Duplicate of #2551

**Closed by nickvergessen** 2020-01-19 13:39 UTC
Labels: 1. to develop, design, enhancement, feature: frontend 🖌️, papercut
