### ISSUE TITLE
Telegram matterbridge does not send or receive messages

### ISSUE THREAD

**Issue by psuter80** [nextcloud/spreed#4719] opened 2020-12-07 14:35 UTC
I can't get a matterbridge to telegram up and running. not sure if i'm doing it all right, so here are all the steps I've executed to set up the bridge: 

## Steps to reproduce
1. create a new telegram bot using bothfather and note the API Key  (1234567890:AAH7pHpFOoKL8PVy15s6Kkqnx31hZUviPUc)
2. create a new group in telegram and add the bot to it
3. send "/command" message to the group
4. navigate to https://api.telegram.org/bot1234567890:AAH7pHpFOoKL8PVy15s6Kkqnx31hZUviPUc/getUpdates?offset=0
5. note down the chat id field (negative number i.e.: -987654321)
6. in nextcloud, as admin enable talk app and install matterbridge via nextcloud admin UI
7. as user in nextcloud, add new group conversation without participants
8. open the group conversation and go to the settings tab on the right side 
9. add a new telegram bridge
10. enter api key and chat id as noted before and click save 
11. check the enabled box to start the matterbridge service 
12. send message to the chat group

### Expected behaviour
message should appear in telegram group

### Actual behaviour
message only appears in nextcloud talk group but is not sent to telegram group. the same is true for the opposite direction, no messages from telegram are displayed in nextcloud talk. 

## Talk app

**Talk app version:** 10.0.3
**Server/PHP:** PHP 7.2.24-0ubuntu0.18.04.7
**Browser:** Firefox 83.0 on Ubuntu 18.04

matterbridge log: 
```
time="2020-12-07T15:20:55+01:00" level=info msg="Running version 1.20.0 1a5353d7" prefix=main
time="2020-12-07T15:20:55+01:00" level=info msg="Parsing gateway myGateway" prefix=router
time="2020-12-07T15:20:55+01:00" level=info msg="Starting bridge: telegram.0 " prefix=router
time="2020-12-07T15:20:55+01:00" level=info msg=Connecting prefix=telegram
time="2020-12-07T15:20:55+01:00" level=info msg="Connection succeeded" prefix=telegram
time="2020-12-07T15:20:55+01:00" level=info msg="telegram.0: joining  (ID: telegram.0)" prefix=telegram
time="2020-12-07T15:20:55+01:00" level=info msg="Starting bridge: nctalk.1 " prefix=router
time="2020-12-07T15:20:55+01:00" level=info msg=Connecting prefix=nctalk
time="2020-12-07T15:20:55+01:00" level=info msg=Connected prefix=nctalk
time="2020-12-07T15:20:55+01:00" level=info msg="nctalk.1: joining y5mbqawf (ID: y5mbqawfnctalk.1)" prefix=nctalk
time="2020-12-07T15:20:55+01:00" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
time="2020-12-07T15:21:00+01:00" level=error msg="SendMessage failed: strconv.ParseInt: parsing "": invalid syntax" prefix=gateway
```

the last line of the log file appeared after trying to send a message to telegram

**Comment by juliosibaja** [comment] 2020-12-08 23:27
Hello, Actually i found that the problem is related to: https://github.com/nextcloud/spreed/blob/master/lib/MatterbridgeManager.php#L508

We can see in [matterbridge](https://github.com/42wim/matterbridge/issues/1072) that it uses channel and not chatid.
A solution can be to add an if condition to process telegram like:
`$content .= sprintf('   channel = "%s"', $part['chatid']) . "\n\n";`

**Comment by juliosibaja** [comment] 2020-12-09 10:55
I can confirm that changing 
`} elseif (in_array($type, ['telegram', 'steam'])) {
     $content .= sprintf(' chatid = "%s"', $part['chatid']) . "\n\n";
}
`
to:
`} elseif ($type === 'telegram') {
     $content .= sprintf('   channel = "%s"', $part['chatid']) . "\n\n";
} elseif ($type === 'steam') {
     $content .= sprintf('   chatid = "%s"', $part['chatid']) . "\n\n";
}`
in MatterbridgeManager solves the telegram issue. Anyway I'm not sure that steam really uses chatid and i did not test it.

This is the log from my matterbrige:
`time="2020-12-09T09:43:02Z" level=info msg="Running version 1.20.0 1a5353d7" prefix=main
time="2020-12-09T09:43:02Z" level=info msg="Parsing gateway myGateway" prefix=router
time="2020-12-09T09:43:02Z" level=info msg="Starting bridge: telegram.0 " prefix=router
time="2020-12-09T09:43:02Z" level=info msg=Connecting prefix=telegram
time="2020-12-09T09:43:03Z" level=info msg="Connection succeeded" prefix=telegram
time="2020-12-09T09:43:03Z" level=info msg="telegram.0: joining -419XXXX12 (ID: -419XXXX12telegram.0)" prefix=telegram
time="2020-12-09T09:43:03Z" level=info msg="Starting bridge: nctalk.1 " prefix=router
time="2020-12-09T09:43:03Z" level=info msg=Connecting prefix=nctalk
time="2020-12-09T09:43:04Z" level=info msg=Connected prefix=nctalk
time="2020-12-09T09:43:04Z" level=info msg="nctalk.1: joining tajXXXXi (ID: tajXXXXinctalk.1)" prefix=nctalk
time="2020-12-09T09:43:05Z" level=info msg="Gateway(s) started succesfully. Now relaying messages" prefix=main
`

**Comment by psuter80** [comment] 2020-12-09 10:59
thank you, that helped.. i changed the lines around the region where you pointed to as follows: 
```
                        } elseif (in_array($type, ['steam'])) {
                                $content .= sprintf('   chatid = "%s"', $part['chatid']) . "\n\n";
                        } elseif ($type == "telegram"){
                                $content .= sprintf('   channel = "%s"', $part['chatid']) . "\n\n";
                        }
```
after which i was able to send messages to the telegram group chat. I then had to disable privacymode for the telegram bot in order to also be able to receive messages. 

i'd appreciate if someone who is working actively on spreed could patch this, i'm not familiar with the wohle process yet and and don't have too much time atm to get into that :) 

I think my "steps to reproduce" could also be used for documentation purposes in the future. just add a step where privacy mode is disalbed as step 2 into the list :)

**Comment by psuter80** [comment] 2020-12-09 11:01
@juliosibaja you beat me by a couple of minutes ;)

**Comment by eneiluj** [comment] 2020-12-09 11:06
@psuter80 @juliosibaja Thanks a lot! I'll make a PR to fix this on the Talk side.

There are still 2 changes to make/suggest to Matterbridge project:
* https://github.com/42wim/matterbridge/blob/0d7315249d20bf9856605068074a7b6c6bcce835/matterbridge.toml.sample#L1825 is wrong
* as @psuter80 said, privacy mode of the telegram bot must maybe be disabled, this should appear in Matterbridge documentation

**Comment by juliosibaja** [comment] 2020-12-09 16:32
Nice!!
Thank you @eneiluj @psuter80 .

I'm not a matterbrige expert but looking some examples like the zulip's conf into [matterbridge.toml.sample](https://github.com/42wim/matterbridge/blob/0d7315249d20bf9856605068074a7b6c6bcce835/matterbridge.toml.sample#L1876) 
or the [msteams's](https://github.com/42wim/matterbridge/wiki/MS-Teams-setup#once-again-the-complete-configuration) and same for [Steam](https://github.com/42wim/matterbridge/wiki/Section-Steam-%28basic%29). It seems like all the message services use the channel tag/var to identify the chat id / room id and the ids in the table (i.e. https://github.com/42wim/matterbridge/blob/0d7315249d20bf9856605068074a7b6c6bcce835/matterbridge.toml.sample#L1825 ) is just how it is originally called on each platform. 

This is only for the `'[[gateway]]' ` part of the toml. Please correct me if i'm wrong, but i think that the line  ```				$content .= sprintf('	channel = "%s"', $part['channel']) . "\n";``` is enough for all the services.

**Comment by nickvergessen** [comment] 2020-12-10 19:29
So close because #4727 is merged? or is this a new issue and also needs fixing? @eneiluj

**Comment by eneiluj** [comment] 2020-12-11 10:07
@juliosibaja You are probably right and that would explain why I never managed to make MsTeams work... I'll check this out.

@nickvergessen It's a new issue but related enough to stay here.

**Comment by eneiluj** [comment] 2020-12-11 11:20
@juliosibaja Thanks a lot, channel is indeed always used. So now MsTeams work fine, tested and approved. Steam should also work fine.

**Comment by juliosibaja** [comment] 2020-12-11 11:24
Great @eneiluj. Thank you!!

**Closed** 2020-12-31 20:08 UTC
Labels: 0. Needs triage, bug, feature: integration 📦, needs info
