### ISSUE TITLE
Loudness of the others

### ISSUE THREAD

**Issue by sando1234** [nextcloud/spreed#5329] opened 2021-03-05 15:03 UTC
I would find it practical if you could adjust the volume of the others. Because if one is very quiet and the other is very loud, it is very difficult to listen.

**Comment by sando1234** [comment] 2021-03-05 15:05
PS: This is my first feature request. :D

**Comment by nickvergessen** [comment] 2021-03-05 15:24
Duplicate of #3155

**Closed** 2021-03-05 15:24 UTC
Labels: 0. Needs triage, enhancement
