### ISSUE TITLE
Make it more clear who's calling you in the web UI

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#1719] opened 2019-04-12 17:16 UTC
It is often not very clear who is trying to contact you in the web UI. Mostly because it is static.

When I'm in talk and somebody calls me, I get a notification from my phone, my desktop client, and in the web UI. What I don't see is what I expect - an entry on the left that blinks or somehow has an animation to catch your eye and make clear that you're getting a call from that person. You still have to search and read every room name until you find the one you were just notified about to know there is an ongoing call with you in there.

I know active rooms get sorted on top, but that doesn't do the trick if you have a bunch of favorite ones, you still have to scan manually to the bottom of your favorite list. Why not show some kind of animation, something moving, that someone is typing to you, calling you etc...

**Comment by nickvergessen** [comment] 2019-04-12 17:54
Yes its planned.
But duplicate of #1444

**Closed by nickvergessen** 2019-04-12 17:54 UTC
