### ISSUE TITLE
NC25: Conversations settings: jump to blank page when managing the lobby

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#8013] opened 2022-09-26 10:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Open the conversation settings of a conversation
2. Go to "Meeting Settings"
3. Check/Uncheck the "Enable Lobby" button

### Expected behaviour
A calendar with date picker should pop up

### Actual behaviour
A blank page pops-up and it seeems not possible to pick the date/time for the validity of the lobby.

A screen recording shows the issue: https://cloud.nextcloud.com/s/fy8nQpikwWbLooE

## Talk app

c.nc.com

## Browser

Firefox 105.0

## Server configuration

c.nc.com

**Nextcloud configuration:**
c.nc.com

**Comment by nickvergessen** [comment] 2022-09-26 10:58
Duplicate of #7997

**Closed by nickvergessen** 2022-09-26 10:58 UTC
Labels: 0. Needs triage, bug
