### ISSUE TITLE
EmojiPicker increases too much the memory usage of chat

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7325] opened 2022-05-05 16:58 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Probably related: #7319

My guess is that each EmojiPicker instance is loading into memory all the emojis, even if the picker itself is hidden and only the button is shown. As [the EmojiPicker is shown on any message that has reactions](https://github.com/nextcloud/spreed/blob/6abd57d7a50d904887e857eb42813fcd63881030/src/components/MessagesList/MessagesGroup/Message/Message.vue#L139-L146) this can greatly increase the memory usage.

This issue is especially noticeable when scrolling back and loading several comment pages in a conversation with a lot of reactions. The reproduction steps below are just a simplification and do not reflect a real case (uexcept if users *really* like reactions :-P ), but the result is the same.

Note that if the EmojiPicker is removed from the reaction list and the code rebuilt then the test steps do not show the big memory usage.

## Steps to reproduce

- Create conversation A
- Create conversation B
- Send 40 messages in conversation B
- Add a reaction to each message
- Close the browser and open it again in conversation A
- Check the memory used by the system
- Open conversation B
- Once the conversation is loaded, wait a few more seconds so the garbage collection frees some unneeded memory and then check again the memory used by the system

### Expected behaviour

The memory usage is slightly increased

### Actual behaviour

The memory usage increases by hundreds of MiB

**Comment by nickvergessen** [comment] 2022-05-05 17:03
Duplicate of #7319

**Closed** 2022-05-05 17:03 UTC
Labels: 1. to develop, bug, feature: chat  💬, feature: frontend 🖌️, feature: reactions 👍

**Comment by nickvergessen** [comment] 2022-05-05 17:59
Workaround in https://github.com/nextcloud/spreed/pull/7326
