### ISSUE TITLE
contacts availability/online status

### ISSUE THREAD

**Issue by Glebelg2** [nextcloud/spreed#832] opened 2018-05-02 08:41 UTC
is there any possibility to see/check if a contact is online (or available) before initiating a call?

**Comment by nickvergessen** [comment] 2018-05-04 09:34
If the other user is also in the same room, you will see their name being black instead of grey in the participant list (which means that the user is reading the chat).

Everything apart from that is not on our todo list for privacy reasons.

**Comment by theDyingMountain** [comment] 2018-05-08 08:25
@nickvergessen I'm working for a project where nextcloud is used as an internal communication platform for a company . More than 1000 employees are working at this company. Because of that, the "New Conversation" and "Add Participant" select lists always contains all the employees. It will be very useful to show only the employees who are online. Can you explain why the online status is an important privacy reason for you? The [XMPP Chat App](https://www.jsxc.org) also shows the online status.

**Comment by Scofield81** [comment] 2019-04-06 15:21
**Additional context**
Add any other context or screenshots about the feature request here.


Hello. It would be good if you could see who I would like to talk to online or offline.
And that sent the message,sent it, received it, read it
for example: messenger or whatsapp chat

Online
[https://user-images.githubusercontent.com/13529333/55671291-017c4600-588f-11e9-9f24-8eda2346dda1.jpg](url)

Sent ✔  Received ✔✔  Read ✔✔(two blue colored mark)
[https://www.hijosdigitales.es/wp-content/uploads/2017/01/enlinea_wasap1.jpg](url)

**Comment by camilasan** [comment] 2019-06-05 13:18
I will re-open it because I would love to be able to tell people when I am too busy/unavailable. An alternative I guess would be to do something like Whatsapp does that is to set to not get notifications from a conversation for one hour or so many days - at least in the mobile app.

**Comment by stratoss** [comment] 2019-06-19 13:12
> Everything apart from that is not on our todo list for privacy reasons.

Can't it be configurable? E.g. the system will share my online status only if I explicitly stated that I don't mind, even if I'm not reading the room at the moment.

**Comment by pwFoo** [comment] 2019-07-20 14:33
Online status would show if the user is online or not, but would it possible to do it like WhatsApp with indicators next to the message?
1. send
2. received
3. read  

With group chats it's mark as received or read if all users reached that state. It's nice to know if a user is online (ready for call?), but would be great to see if the user received / read my message.

**Comment by TeslaBenny** [comment] 2019-08-06 20:04
Duplicate of #1012

**Comment by call-me-matt** [comment] 2020-10-11 09:10
with Nextcloud 20, this feature has been introduced, right?

**Comment by nickvergessen** [comment] 2020-10-11 09:14
Yes

**Closed by nickvergessen** 2020-10-11 09:14 UTC
Labels: 1. to develop, enhancement, feature: api 🛠️, feature: frontend 🖌️
