### ISSUE TITLE
Rejection of call and information about the time of the call

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#2162] opened 2019-09-07 14:54 UTC
## Steps to reproduce
1. Call user X on Talk Android.
2. User X rejects calling in Talk Android.
3. Does **not automatically** end the call.

**In addition, information about the duration of the call appears after the caller's end:**
![obraz](https://user-images.githubusercontent.com/47037905/64476457-1dae4700-d18f-11e9-8267-cd19cbb2d6cc.png)

**Nextcloud Version:**
16.0.4
**Talk Version:**
6.0.4
**Talk Android Version:**
7.0.0b4

**Comment by nickvergessen** [comment] 2019-09-09 08:57
Duplicate of https://github.com/nextcloud/spreed/issues/1146

**Closed by nickvergessen** 2019-09-09 08:57 UTC
Labels: 0. Needs triage, bug
