### ISSUE TITLE
Send an email when a message arrives for a user not logged in 

### ISSUE THREAD

**Issue by beccon4** [nextcloud/spreed#5116] opened 2021-02-10 12:45 UTC
**Is your feature request related to a problem? Please describe.**
When away from my desk, chat notifications and beeing mentioned in the chat frequently get lost as a) desktop notification is very weak and there is virtually always some non urgent unconfirmed pending notification b) my Android app from f-froid does not support notifications at all. 

**Describe the solution you'd like**
An option to send an email from Nextcloud to the mail in the user profile to announce that someone wants to contact me. That would ring the bell via the mobile email client e.g. K9 or whatever. That would be very useful for less frequented channels - where only a few messages arrive per day/week - if any. 

**Describe alternatives you've considered**
Other ways to solve this problem
- enhance Android App to properly announce - even if run without Google FCM 
- make the notification bell louder and more visible (Slack can do this either) and leave a lear message in the status line above that a message is pending. (e.g. show a letter or some similar symbol) to notify that a chat message or mentioning has arrived and not the second upgrade announcement for some other App is pending.

**Comment by nickvergessen** [comment] 2021-02-10 15:36
Duplicate of #4878

**Closed by nickvergessen** 2021-02-10 15:36 UTC
Labels: 0. Needs triage, enhancement
