### ISSUE TITLE
"The browser you're using is not fully supported" for GNOME Web (Epiphany) 3.36.1

### ISSUE THREAD

**Issue by mjog** [nextcloud/spreed#3844] opened 2020-06-07 11:24 UTC
GNOME Web uses the WebKitGTK rendering engine, and as such is at least on par with Safari, if not more up to date. Yet every time I log in with Web, I am presented with the "The browser you're using is not fully supported" nag, which tells me to go install Safari, amongst others.

### Steps to reproduce
1. Install GNOME Web 3.36
2. Log in to Next Cloud account

### Expected behaviour

No upgrade nag is presented.

### Actual behaviour

An upgrade nag is presented.

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2.4.38

**Database:** Maria 10.3.22

**PHP version:** 7.3

**Nextcloud version:** 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Downloaded tar.gz

**Comment by nickvergessen** [comment] 2020-06-24 10:37
There is not a lot we can do here. The webrtc-adapter lib we use only supports the most famous browsers (as it gets quite complicated soon after that):
https://github.com/webrtcHacks/adapter/blob/master/src/js/utils.js#L151

So well:
> Please use the latest version of Mozilla Firefox, Microsoft Edge, Google Chrome or Apple Safari.

Is what you should do.
Hope you can still enjoy Nextcloud Talk.

**Comment by gessel** [comment] 2020-07-01 19:25
@nickvergessen the issue isn't so much a request to support other browsers, but rather to set a flag after the first time the toast is shown and then never hassle the user again.  Right now the best solution for those of us preferring an extensible browser like waterfox classic is to disable the plugin.   It is a work around, but suboptimal.  

https://github.com/nextcloud/spreed/blob/e730815e57a66f06ac11d144f1cdb41d24dbdc31/src/mixins/browserCheck.js#L85

It isn't obvious how to comment it out in the distributed files.

**Comment by mjog** [comment] 2020-07-01 22:19
>  the issue isn't so much a request to support other browsers, but rather to set a flag after the first time the toast is shown and then never hassle the user again. Right now the best solution for those of us preferring an extensible browser like waterfox classic is to disable the plugin.

Exactly, this is how I fixed it - disabled Talk.

**Comment by nickvergessen** [comment] 2020-07-02 10:36
> the issue isn't so much a request to support other browsers, but rather to set a flag after the first time the toast is shown and then never hassle the user again.

The problem is average non-technical users will have forgotten it until the next time they have their call, and then be surprised that it does not work (with Internet Explorer 11). So we always need to tell the user that they need to use a different browser.
True that this might be cumbersome for techies, but it's required.

Also when disabling Talk is the solution for you, something seems fishy. The warning should only appear when Talk UI is visible, which is:
1. When you go to Talk
2. When you open the Talk tab in the sidebar in the files app
3. When you open the Talk sidebar in a public share
4. When you try a video-verification on a share.

So if you see this somewhere else, that might be the issue and we can fix it.

Also what is the user agent you are having?

**Comment by nickvergessen** [comment] 2020-07-02 10:55
Also I just checked with latest waterfox and it is detected as Firefox 68 (as that is it's base) and you can even do calls with it.
So make sure to update the latest Talk8 or Talk9 version and enjoy.

**Comment by wouterVE** [comment] 2020-07-24 05:46
I'm also receiving this warning not only when using Talk but also in Files. This last thing is very annoying as this warning should only be given when using Talk I think. 
My user agent:
`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77`

**Comment by rclough** [comment] 2020-07-31 01:53
This alert should have an option to always ignore/permanently dismiss. It pops up in EVERy new page (if I switch from files to photos for example) and is infuriating to have to dismiss EVERY time. I haven't even tried to use Talk yet.

**Comment by nickvergessen** [comment] 2020-07-31 11:17
Okay, I managed to get hands on a fully unsupported browser and now I could reproduce it (cheating user agent doesn't work it seems).

Fix is in https://github.com/nextcloud/spreed/pull/3962

**Comment by rclough** [comment] 2020-08-01 18:56
Thanks for getting the fix in quick!

**Closed** 2020-08-02 13:14 UTC
Labels: 3. to review, bug, feature: frontend 🖌️
