### ISSUE TITLE
Using a User-Agent switcher break the app (displays blank page)

### ISSUE THREAD

**Issue by mh4ckt3mh4ckt1c4s** [nextcloud/spreed#7680] opened 2022-08-05 17:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Make a basic install of Nextcloud (`docker run -d -p 80:80 nextcloud`) and install Talk.
2. Use Firefox with a User-Agent switcher extension (eg https://add0n.com/useragent-switcher.html, but the bug is present with other switchers also (tested)). Enable the User-Agent switcher to something fancy (not Firefox, sometimes using Firefox user-agent do not trigger the bug) and browse the Talk app page.
3. Notice that the app is not loading 

![image](https://user-images.githubusercontent.com/76600167/183130322-4ccbf02f-a611-4ac1-93f4-2a5d00fdedeb.png)

### Expected behaviour
The Talk app should load.

### Actual behaviour
The Talk app is crashing due to (I'm assuming) the fancy user-agent, displaying a blank page. 

## Talk app

**Talk app version:** 14.0.3

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** ArchLinux

**Browser name:** Firefox

**Browser version:** 103.0 (64-bit)

### Browser log

<details>
I'm putting here what I think is the JS error trigerring the issue (regarding the user-agent) :

```
Uncaught TypeError: navigator.userAgent.match(...) is null
    23397 wasm-check.min.js:1
    a index.js:17
    52160 webrtc.js:4
    a index.js:17
    3454 simplewebrtc.js:3
    a index.js:17
    97456 signaling.js:1351
    a index.js:17
    91778 filesSharingServices.js:35
    a index.js:17
    <anonymous> Confirmation.vue:1
    <anonymous> main.js:166
    <anonymous> main.js:152
wasm-check.min.js:1:1693
    23397 wasm-check.min.js:1
    a index.js:17
    52160 webrtc.js:4
    a index.js:17
    3454 simplewebrtc.js:3
    a index.js:17
    97456 signaling.js:1351
    a index.js:17
    91778 filesSharingServices.js:35
    a index.js:17
    <anonymous> Confirmation.vue:1
    <anonymous> main.js:166
    <anonymous> main.js:152
```

</details>

## Server configuration

**Operating system**: Debian

**Web server:** Nginx

**Database:** MySQL or SQLite

**PHP version:** 8.0

**Nextcloud Version:** 24.0.3

**Comment by mh4ckt3mh4ckt1c4s** [comment] 2022-08-05 17:53
Additional notes : I wasn't able to reproduce this issue with Chromium, I think this is Firefox-related. 

Also, from what I was able to observe, in order to trigger the bug you need to switch the user-agent to something else than Firefox (bug working with very "fancy" user-agents but also more common ones such as Chrome and Edge).

**Comment by nickvergessen** [comment] 2022-08-05 18:17
Duplicate of #2176

**Closed by nickvergessen** 2022-08-05 18:17 UTC
Labels: 0. Needs triage, bug
