### ISSUE TITLE
File upload: prevent files with the same name from getting overwritten.

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#2995] opened 2020-02-24 12:50 UTC
## Steps to reproduce
1. Upload a file;
2. Upload a file with the same name;

### Expected behaviour
The second file is renamed before the upload: a suffix is added e.g filename(1) so that the first uploaded file isn't overwritten.

### Actual behaviour
The first file gets overwritten by the second;

**Comment by nickvergessen** [comment] 2020-02-24 12:52
Duplicate of #2987

**Closed by nickvergessen** 2020-02-24 12:52 UTC
Labels: 2. developing, bug, feature: upload & shares 📤

**Comment by ma12-co** [comment] 2020-02-24 12:53
lol
