### ISSUE TITLE
Random disconnection from Talk

### ISSUE THREAD

**Issue by ZeikoFr** [nextcloud/spreed#5177] opened 2021-02-15 12:51 UTC
## Steps to reproduce
1. Be in a Talk conversation with 1 participant or more
2. At random period the browser ask "Are you sure you want to leave thise page" even if you're not on the actual page
3. You need to leave and rejoin the conversation again or you lose the ability to hear other people

### Expected behaviour
Talk should not force disconnection

### Actual behaviour
Talk force disconnection

## Server configuration detail

**Operating system:** Linux 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.1.48

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.7 - 20.0.7.1

**Updated from an older Nextcloud/ownCloud or fresh install:** UPDATED

**Where did you install Nextcloud from:** Official repository

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - appointments: 1.8.2
 - apporder: 0.11.0
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dav: 1.16.2
 - deck: 1.2.4
 - documentserver_community: 0.1.8
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_accesscontrol: 1.10.2
 - files_downloadactivity: 1.9.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trackdownloads: 1.9.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - groupfolders: 8.2.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.2.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.5
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - w2g2: 3.0.3
 - workflowengine: 2.2.0
Disabled:
 - dashboard
 - encryption
 - groupfolders_old
 - user_ldap
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.mydomain.tld",
        "onlyoffice.mydomain.tld"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.7.1",
    "overwrite.cli.url": "http:\/\/cloud.mydomain.tld",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "theme": "",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "logfilemode": 416,
    "loglevel": "1",
    "logdateformat": "F d, Y H:i:s",
    "trashbin_retention_obligation": "10, 30",
    "mysql.utf8mb4": true,
    "onlyoffice": {
        "verify_peer_off": true
    },
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false,
    "app_install_overwrite": [
        "admin_notifications"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36 OPR/74.0.3911.75

**Operating system:** 

## Logs
These are the major log info i got : 
xhr.js:184 GET https://cloud.mydomain.tld/ocs/v2.php/apps/spreed/api/v1/signaling/vo8gibqg 404 (Not Found)
signaling.js:451 Conversation was not found anymore

<details><summary>Web server error log</summary>

xhr.js:184 GET https://cloud.mydomain.tld/ocs/v2.php/apps/spreed/api/v1/signaling/vo8gibqg 404 (Not Found)
(anonymous) @ xhr.js:184
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
c.request @ Axios.js:61
r.forEach.c.<computed> @ Axios.js:76
(anonymous) @ bind.js:9
(anonymous) @ signalingService.js:38
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
a @ talk.js?v=2e0bdb08-12:857
o @ talk.js?v=2e0bdb08-12:857
(anonymous) @ talk.js?v=2e0bdb08-12:857
(anonymous) @ talk.js?v=2e0bdb08-12:857
(anonymous) @ signalingService.js:37
(anonymous) @ cancelableRequest.js:49
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
s @ talk.js?v=2e0bdb08-12:805
o @ talk.js?v=2e0bdb08-12:805
(anonymous) @ talk.js?v=2e0bdb08-12:805
(anonymous) @ talk.js?v=2e0bdb08-12:805
(anonymous) @ cancelableRequest.js:48
m.Internal._startPullingMessages @ signaling.js:409
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
signaling.js:451 Conversation was not found anymore
(anonymous) @ signaling.js:451
Promise.catch (async)
m.Internal._startPullingMessages @ signaling.js:438
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
Promise.then (async)
m.Internal._startPullingMessages @ signaling.js:410
(anonymous) @ signaling.js:436
</details>
Insert your web server log here 
```
I checked all log files and I can't find anything related to Talk, is there a specific log file hidden somewhere for this app ?

**Comment by PVince81** [comment] 2021-02-15 13:09
Next time you feel it might be happening, please open the browser console and also the network tab.

Then as soon as you see the unwanted dialog, click cancel and copy the Console tab and Network tab info.
It will likely contain clues about why it is trying to leave the page.

I suspect that maybe it received a 404 request when querying the messages and wrongly believes that either the call/session has ended or the room disappeared. Usually a 404 would redirect to the "not found" page.

Also to try: click "ok" when it asks whether you want to leave and see where it's redirecting to. Is it the "not found" page ?

**Comment by PVince81** [comment] 2021-02-15 13:10
> 404 (Not Found)
signaling.js:451 Conversation was not found anymore

this is likely the reason, it would make it redirect to the "not found" page

**Comment by PVince81** [comment] 2021-02-15 13:10
similar issues have been reported here: https://github.com/nextcloud/spreed/issues/4670

**Comment by ZeikoFr** [comment] 2021-02-15 13:12
> > 404 (Not Found)
> > signaling.js:451 Conversation was not found anymore
> 
> this is likely the reason, it would make it redirect to the "not found" page

I guess so, the problem is that the conversation is not deleted. When I click OK or Cancel I just stay on the same page and I need to manually exist, refresh and rejoin the conversation.

At first I was thinking about php session TTL but it is so random that I can't pin point the source problem

**Comment by nickvergessen** [comment] 2021-02-15 13:38
Can still be a session TTL.

**Comment by ZeikoFr** [comment] 2021-02-15 14:34
Yes but if it was session TTL it would impact all user that have joined the same conversation at the same time and it's not the case.

Sometime I don't have error in all day and sometime it is 3/4 times in less that 10 minutes, and not everyone is impacted :(

**Comment by nickvergessen** [comment] 2021-02-15 14:44
Should be a duplicate of #5177

**Closed by nickvergessen** 2021-02-15 14:44 UTC
Labels: 0. Needs triage, bug

**Comment by ZeikoFr** [comment] 2021-02-15 16:18
I don't really see why it's a duplicate, screensharing is not used in my case :/

Do you know where I could find more info in log file to help targeting the issue ?

thc

**Comment by nickvergessen** [comment] 2021-02-16 07:47
The problem is the same "people randomly get disconnected".
In #5170 they want to stop it on screenshare.
The main issue is we don't do anything like this. If your session times out there is nothing we can do about it in Talk. We don't do any session handling to begin with and we do requests which should keep the session alive.
