### ISSUE TITLE
the share file hint-text is hidden behind the video

### ISSUE THREAD

**Issue by rubo77** [nextcloud/spreed#3933] opened 2020-07-22 11:35 UTC
## Steps to reproduce
1. start a call with one opponent
2. open the chat on the right
3. click on the share "paper clip" icon

### Actual behaviour
the text is cut off on the left part, it only shows the last part: "re File"

## Talk app

**Talk app version:** 9.0.2

**Custom Signaling server configured:** no

**Custom TURN server configured:** yes

**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** /Ubuntu 20.04

**Browser name:** Firefox//...

**Browser version:** 78.0.2 (64-bit)

## Server configuration

**Operating system**: Debian 10

**Web server:** Nginx

**Nextcloud Version:** 19.0.1

**Comment by nickvergessen** [comment] 2020-08-19 07:48
Duplicate of #3455

**Closed by nickvergessen** 2020-08-19 07:48 UTC
Labels: 0. Needs triage, bug
