### ISSUE TITLE
Own messages lead to unread indicator in navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#8862] opened 2023-02-27 08:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Send a message to a group conversation in Talk
2. Look at the left navigation

### Expected behaviour
Your own messages should not lead to an unread counter.

### Actual behaviour
In this case I am in the talk conversation, scrolled all the way down, having just written a message, and I get a blue unread indicator in the navigation. Sometimes this indicator is even primary color blue, very present and confusing.
![image](https://user-images.githubusercontent.com/925062/221515907-c886595e-89aa-4a8d-a5f4-e0dd807159f6.png)

## Talk app

**Talk app version:** Current on cloud.nc

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 22.04

**Browser name:** Firefox

**Browser version:** 109.0.1

**Comment by nickvergessen** [comment] 2023-02-27 08:52
This always happened for some brief moments, but yeah seems to be longer now

**Comment by SystemKeeper** [comment] 2023-02-28 08:11
In my tests this is not always the case. I have conversation where no unread indicator is visible and I saw it (sometimes on that same conversation) that it stayed for quite some time. I think it's a race condition between us sending a read request and receiving our own message (or updating the room list), since we don't automatically set the read marker:

https://github.com/nextcloud/spreed/blob/ef573c75b0d593f458291e11ea9fa0faad88d6a3/src/services/messagesService.js#L64

**Comment by SystemKeeper** [comment] 2023-02-28 08:37
Maybe the backend could be modified to not count our own messages as unread for ourselves? Not sure if this is possible.

**Comment by nickvergessen** [comment] 2023-02-28 10:50
> Maybe the backend could be modified to not count our own messages as unread for ourselves? Not sure if this is possible.

No, that's not possible especially with the "mark as unread" feature which sets it to the last message.

I mentioned in the chat already that I think this code here does not match anymore:
https://github.com/nextcloud/spreed/blob/e66bd05eb7f68008a4241d7679f491b4b6c5da46/src/store/messagesStore.js#L1137-L1152

that should overwrite the unread counter right away with the new data.

**Comment by SystemKeeper** [comment] 2023-03-23 08:27
![image](https://user-images.githubusercontent.com/1580193/227143848-d216fc0b-7029-4df6-8d16-4116cf4f9a5d.png)
![image](https://user-images.githubusercontent.com/1580193/227144600-00625342-709d-4d7a-8c3b-16b9722e6cc9.png)

I am still seeing this from time to time even on 16.0.0 (c.nc.c). I couldn't pin-point it to when it happens, reactions were not involved as stated in https://github.com/nextcloud/spreed/issues/9134

**Comment by SystemKeeper** [comment] 2023-03-23 08:40
I am not able to reproduce this on instances without `notify_push`... Maybe related? It's the only difference I can spot right now...
* Local test instance and sermo not reproducible (both don't use `notify_push`, but sermo has HPB, so HPB should not be a problem)
* c.nc.c + local production instance has `notify_push` set up and issue is reproducible

**Comment by nickvergessen** [comment] 2023-03-27 14:19
Fix is in https://github.com/nextcloud/spreed/pull/9180
Regression is tracked in https://github.com/nextcloud/spreed/issues/9134

**Closed by nickvergessen** 2023-03-27 14:19 UTC
Labels: 1. to develop, bug, medium, papercut, feature: chat  💬, feature: frontend 🖌️

**Comment by nickvergessen** [comment] 2023-03-27 14:39
Aparentely that is something else. Anyway, since the ticket is "solved" and released already, please create a new issue if there is still something
