### ISSUE TITLE
Multiple and unsynchronised group conversations

### ISSUE THREAD

**Issue by nooblag** [nextcloud/spreed#3018] opened 2020-02-27 12:00 UTC
### Steps to reproduce
1. On a fresh install of Nextcloud 18.0.0 and Talk 8.0.4, login as an admin user.
2. Navigate to 'Users' and create a new group. For the purposes of this test, call it 'Everyone.'
3. Navigate to 'Talk' tab, and in the 'Search conversations or contacts' box, type 'Everyone' and select the 'Everyone' group. The group chat called 'Everyone' begins, current users are added, and the admin user becomes the moderator.
4. Navigate to 'Users' tab and create a new user ("test") and add them to the 'Everyone' group.

### Expected behaviour
- The new user ("test") should be added to the "Everyone" group chat as the user account is a part of that group as defined.
- Only one "Everyone" group chat should exist, and all users in the "Everyone" group are added and appear in that chat.
- The Nextcloud user (in this case, the "admin" user) that initiates the group chat is the moderator of the group chat.

### Actual behaviour
- The new user ("test") whom is added after the "Everyone" group chat has been created by the admin, is not added to the "Everyone" group chat, and in fact if the new user "test" tries to join the existing "Everyone" group chat, Talk instead starts a new "Everyone" group chat, to which the new "test" user is the moderator and not the prior group chat moderator ("admin").
- Two group chats now exist. The "Everyone" group chat moderated by admin, and the "Everyone" group chat moderated by the new user "test".

- If the steps above are repeated and yet another new user is added to Nextcloud ("test2") and is also added to the "Everyone" group, this user is also out of sync, but is now time three steps removed. The 2nd "Everyone" group chat started by "test" does not contain the "test2" user, and the original "Everyone" group chat started by admin contains none of these new users.
- And so on and so on.

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 7.2.24-0ubuntu0.18.04.3

**Modules loaded:** Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.0 - 18.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install.

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - apporder: 0.9.0
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - camerarawpreviews: 0.7.3
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - drop_account: 0.1.0
 - event_update_notification: 1.0.1
 - external: 3.5.0
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_downloadactivity: 1.7.0
 - files_fulltextsearch: 1.4.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.1
 - impersonate: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.2
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocr: 6.0.16
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - socialsharing_email: 2.0.0
 - spreed: 8.0.4
 - support: 1.1.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - uploaddetails: 0.1.3
 - user_retention: 1.1.0
 - user_usage_report: 1.2.0
 - video_converter: 0.1.3
 - viewer: 1.2.0
 - workflowengine: 2.0.0

Disabled:
 - encryption
 - federation
 - files_external
 - group_everyone
 - nextcloud_announcements
 - survey_client
 - terms_of_service
 - user_ldap
```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "18.0.0.10",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": 0,
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 14",
    "versions_retention_obligation": "auto, 365",
    "simpleSignUpLink.shown": "false",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "dbindex": "0",
        "timeout": "1.5"
    },
    "logtimezone": "Australia\/Melbourne",
    "maintenance": false,
    "default_locale": "en_AU",
    "force_locale": "en_AU",
    "default_language": "en",
    "force_language": "en",
    "defaultapp": "activity,files",
    "activity_expire_days": 180,
    "session_lifetime": 14400,
    "session_keepalive": false,
    "lost_password_link": "disabled",
    "overwriteprotocol": "https",
    "app_install_overwrite": [
        "activitylog",
        "uploaddetails",
        "drop_account"
    ]
}
```
</details>

**Are you using encryption:** No.

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0

**Operating system:** Windows 10

**Comment by nickvergessen** [comment] 2020-02-27 12:59
> The new user ("test") whom is added after the "Everyone" group chat has been created by the admin, is not added to the "Everyone" group chat

Duplicate of #1329 
For the time being you can simply add the users manually to the conversation, or you add the "everyone" group after adding a chunk of people to the group

> in fact if the new user "test" tries to join the existing "Everyone" group chat

This concept does not exist yet. The header above the search option clearly states that a new conversation with this group is being started.

Duplicate of #1763

**Closed** 2020-02-27 13:00 UTC
Labels: 0. Needs triage, bug

**Comment by nooblag** [comment] 2020-03-06 08:36
> > in fact if the new user "test" tries to join the existing "Everyone" group chat
> 
> This concept does not exist yet. The header above the search option clearly states that a new conversation with this group is being started.

I disagree.

The "+" button suggests creating a new conversation, while the search box and rest of interface suggests joining an *existing* conversation.

![screen](https://user-images.githubusercontent.com/1122344/76066363-92006080-5fe1-11ea-8320-17ea19467c66.png)
