### ISSUE TITLE
Separate permissions for post messages and ractions.

### ISSUE THREAD

**Issue by cahebebe** [nextcloud/spreed#12650] opened 2024-07-08 15:18 UTC
In group chats, we have the possibility to edit the default permissions for participants. One of these permissions is "Can post messages and reactions". This is very useful to control the group content, for example, in groups for notification purposes only when I need a reaction for confirmation. However, I can't enable this option because it is combined into one.

Is it possible for a future version to separate this option into "Can post messages" and "Can post reactions"?

Thank you!

![Example](https://github.com/nextcloud/spreed/assets/16362456/a0592014-3200-46c7-b376-d12925cad7a3)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** (see administration page)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SystemKeeper** [comment] 2024-07-08 15:55
Duplicate of https://github.com/nextcloud/spreed/issues/11329

**Closed by SystemKeeper** 2024-07-08 15:55 UTC
Labels: 0. Needs triage, enhancement
