### ISSUE TITLE
Older messages sometimes missing until full page reload

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#5188] opened 2021-02-16 12:19 UTC
## Steps to reproduce
1. Open a chat on c.nc.c
2. See content is missing in the backlog sometimes

### Expected behaviour

I see older messages.

### Actual behaviour

I don't see older messages in some cases. I have two different scenarios:

1. Group chats in which scrolling back sometimes misses messages
2. New chats that have no content when opened (reopening sometimes helps)

Example of a 1:1 chat where I have to refresh my browser to see the received message: (which I received yesterday already and wanted to revisit today)

![image](https://user-images.githubusercontent.com/878997/108062036-80c92c00-7059-11eb-9784-703210bb1b22.png)

![image](https://user-images.githubusercontent.com/878997/108062051-86267680-7059-11eb-90bb-60a3169df089.png)

**Comment by nickvergessen** [comment] 2021-02-16 12:55
Yeah I also sometimes experience an empty chat with only new messages (no history) lately from time to time.
However we didn't find any reproducable steps yet.

**Comment by LukasReschke** [comment] 2021-02-16 13:00
@nickvergessen it reproduces for me on rhwpfxci when selecting it in the sidebar. Is there any request you are particularly interested in to see? :)

**Comment by PVince81** [comment] 2021-02-17 14:34
I just had a local case where one message was missing in the middle of a chat until refresh. Not sure if related or different issue.
Sadly I refreshed too quickly and lost the calls.

**Comment by PVince81** [comment] 2021-02-17 14:36
I have an idea about a test: have a bot post messages that count up in two rooms. Then switch between the rooms manually from times to times and see if any numbers are missing.

**Comment by PVince81** [comment] 2021-02-17 15:12
I've managed to gather some incomplete clues about a second case of missing message:

1. the message with id 492 is also missing in the store

2. access log around that case (note: this is based on https://github.com/nextcloud/spreed/pull/3825 which doesn't reset the read marker)
```
127.0.0.1 - - [17/Feb/2021:15:31:21 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy/read HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:31:19 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=486&includeLastKnown=0 HTTP/1.1" 200 225
127.0.0.1 - - [17/Feb/2021:15:30:58 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 376
127.0.0.1 - - [17/Feb/2021:15:31:29 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:31:34 +0100] "POST /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 733
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/settings?token=va6i7nwy HTTP/1.1" 200 268
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 495
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy/read HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 729
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 376
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 495
127.0.0.1 - - [17/Feb/2021:15:31:38 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 495
127.0.0.1 - - [17/Feb/2021:15:31:39 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 730
127.0.0.1 - - [17/Feb/2021:15:31:24 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 221
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 221
127.0.0.1 - - [17/Feb/2021:15:31:44 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=500&includeLastKnown=0 HTTP/1.1" 200 225
127.0.0.1 - - [17/Feb/2021:15:31:49 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 409 111
127.0.0.1 - - [17/Feb/2021:15:38:16 +0100] "POST /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 733
127.0.0.1 - - [17/Feb/2021:15:38:16 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=500&includeLastKnown=0 HTTP/1.1" 200 761
127.0.0.1 - - [17/Feb/2021:15:38:17 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/settings?token=va6i7nwy HTTP/1.1" 200 273
127.0.0.1 - - [17/Feb/2021:15:38:21 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:38:21 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 404 111
127.0.0.1 - - [17/Feb/2021:15:43:21 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=492&includeLastKnown=1 HTTP/1.1" 200 1362
127.0.0.1 - - [17/Feb/2021:15:43:21 +0100] "POST /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 737
127.0.0.1 - - [17/Feb/2021:15:43:21 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 1358
127.0.0.1 - - [17/Feb/2021:15:43:21 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 765
127.0.0.1 - - [17/Feb/2021:15:43:21 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/settings?token=va6i7nwy HTTP/1.1" 200 270
127.0.0.1 - - [17/Feb/2021:15:43:25 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 377
127.0.0.1 - - [17/Feb/2021:15:43:25 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 496
127.0.0.1 - - [17/Feb/2021:15:43:27 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 496
127.0.0.1 - - [17/Feb/2021:15:43:28 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 733
127.0.0.1 - - [17/Feb/2021:15:43:35 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:43:25 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 409 111
127.0.0.1 - - [17/Feb/2021:15:43:26 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=610&includeLastKnown=0 HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2021:15:45:39 +0100] "POST /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 733
127.0.0.1 - - [17/Feb/2021:15:45:39 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=492&includeLastKnown=1 HTTP/1.1" 200 1362
127.0.0.1 - - [17/Feb/2021:15:45:39 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 1358
127.0.0.1 - - [17/Feb/2021:15:45:39 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 765
127.0.0.1 - - [17/Feb/2021:15:45:39 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/settings?token=va6i7nwy HTTP/1.1" 200 271
127.0.0.1 - - [17/Feb/2021:15:45:43 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 374
127.0.0.1 - - [17/Feb/2021:15:45:43 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 493
127.0.0.1 - - [17/Feb/2021:15:45:44 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 727
127.0.0.1 - - [17/Feb/2021:15:45:47 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 494
127.0.0.1 - - [17/Feb/2021:15:45:47 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 727
127.0.0.1 - - [17/Feb/2021:15:46:00 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=205&includeLastKnown=0 HTTP/1.1" 200 561
127.0.0.1 - - [17/Feb/2021:15:45:44 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 374
127.0.0.1 - - [17/Feb/2021:15:45:44 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=610&includeLastKnown=0 HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2021:15:46:16 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 494
127.0.0.1 - - [17/Feb/2021:15:46:17 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 727
127.0.0.1 - - [17/Feb/2021:15:46:23 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=158&includeLastKnown=0 HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2021:15:46:23 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=0&lastKnownMessageId=158&includeLastKnown=0 HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2021:15:46:14 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 374
127.0.0.1 - - [17/Feb/2021:15:46:15 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=610&includeLastKnown=0 HTTP/1.1" 304 -
127.0.0.1 - - [17/Feb/2021:15:46:46 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 494
```

The really weird thing is that older numbers seem to come back.
For example we do a query where we say "we already know message 492".
Then later on there's a "610", but that one is followed again by 492 ?!

Somehow it seems the requests are out of order.

3. Also I noticed that sometimes the request is lagging for a long time (long polling ?).

In my case here, 610 is the last visible message in the UI and also the last in oc_comments for that room.
Requesting `GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=610&includeLastKnown=0`

after 30 seconds it returns "304 Not Modified".
I guess it's a long poll with timeout then.

Maybe in some cases we're doing long polling and not cancel properly while some other concurrent requests are happening, so maybe we receive outdated results or something messes up.

3. I tried to replay some of the requests above with the message id from the lines before 492, and the response properly contains that message

**Comment by PVince81** [comment] 2021-02-17 15:14
note: I filtered the above by the current room "va6i7nwy".

I now realize that we can see when I was switching away and back to it.
Strangely at some stage when  I switched away it was already requesting the message with "last know 610" but when switching back the last know was suddenly "492". Maybe when switching back I landed on a "scrolled up" page and the next page was missing. So maybe need to investigate the "load next page" code path to see if we have a "off by one" problem there.

**Comment by PVince81** [comment] 2021-02-17 15:25
okay, narrowed down further with some extras:
```
127.0.0.1 - - [17/Feb/2021:15:31:14 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=482&includeLastKnown=0 HTTP/1.1" 200 228
127.0.0.1 - - [17/Feb/2021:15:31:18 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy/read HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:31:21 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy/read HTTP/1.1" 200 81
# charles is posting the message with id 492 here
127.0.0.1 - charles [17/Feb/2021:15:31:22 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy HTTP/1.1" 201 514
# this request should have retrieved message 492
127.0.0.1 - - [17/Feb/2021:15:31:19 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=486&includeLastKnown=0 HTTP/1.1" 200 225
127.0.0.1 - - [17/Feb/2021:15:30:58 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 376
# leaving room (switching away)
127.0.0.1 - - [17/Feb/2021:15:31:29 +0100] "DELETE /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 81
# joining room again (switching back)
127.0.0.1 - - [17/Feb/2021:15:31:34 +0100] "POST /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants/active HTTP/1.1" 200 733
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/settings?token=va6i7nwy HTTP/1.1" 200 268
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 495
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy/read HTTP/1.1" 200 81
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 729
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v2/signaling/va6i7nwy HTTP/1.1" 200 376
127.0.0.1 - - [17/Feb/2021:15:31:36 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 495
127.0.0.1 - - [17/Feb/2021:15:31:38 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy/participants?includeStatus=true HTTP/1.1" 200 495
127.0.0.1 - - [17/Feb/2021:15:31:39 +0100] "GET /ocs/v2.php/apps/spreed/api/v3/room/va6i7nwy HTTP/1.1" 200 730
# charles post message with id 500
127.0.0.1 - charles [17/Feb/2021:15:31:42 +0100] "POST /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy HTTP/1.1" 201 512
# the following should get it (but why is it run twice??)
# at least here it appears that message 492 is known, but not sure if it's just a value or whether it was visible in the UI
127.0.0.1 - - [17/Feb/2021:15:31:24 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 221
127.0.0.1 - - [17/Feb/2021:15:31:35 +0100] "GET /ocs/v2.php/apps/spreed/api/v1/chat/va6i7nwy?setReadMarker=0&lookIntoFuture=1&lastKnownMessageId=492&includeLastKnown=0 HTTP/1.1" 200 221
```

**Comment by PVince81** [comment] 2021-02-17 15:37
```javascript
function simulateSwitching(tokens) {
   let newToken = tokens[Math.floor(Math.random() * tokens.length)]
   console.log('Switching to ', newToken)
   document.getElementById('conversation_' + newToken).click()
}

var simulatorInterval = window.setInterval(() => simulateSwitching(['token1', 'token2']), 3000)
```

combine with multiple instances of https://gist.github.com/PVince81/300f03d277a1eb8c876a27b5ddae932e

let's see if the issue will appear on its own...

**Comment by PVince81** [comment] 2021-02-17 16:44
I was not able to reproduce the issue on master, so what I saw is probably specific to workflows where the read marker is not automatically set at the end like in https://github.com/nextcloud/spreed/pull/3825.

Will keep an eye on this...

**Comment by PVince81** [comment] 2021-02-18 10:33
I've got more clues from my investigation in: https://github.com/nextcloud/spreed/pull/3825#issuecomment-781243240

@LukasReschke if you're able to reproduce the "missing messages" issues, keep an eye for requests that look like the screenshot at the link above, especially cancelled requests.

It seems that if the request is able to finish before being cancelled (bogously, it shouldn't) then you get all messages, otherwise a message might be missing.

But it seems you folks were talking about complete pages of messages missing ?

**Comment by PVince81** [comment] 2021-02-18 13:13
I was now able to confirm an issue on my PR where we're reusing a "CancelableRequest" cancel function for two calls that are supposed to not exclude each other. [In the PR](https://github.com/nextcloud/spreed/pull/3825#issuecomment-781319116) it happens for a single message and is triggered by an autoscroll during load, while the first request hasn't finished.

Now, I could imagine that this could also happen for the requests that loads previous/next pages if you scroll like crazy. This could explain missing pages of results.

**Closed** 2021-02-19 10:58 UTC
Labels: 1. to develop, bug, feature: chat  💬, feature: frontend 🖌️
