### ISSUE TITLE
Enhancing Readability in Nextcloud Talk: Message Alignment Proposal

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/spreed#13395] opened 2024-09-25 13:33 UTC
Currently, in Nextcloud Talk, all conversation threads are left-aligned, which makes it challenging to differentiate between users and follow the flow of the conversation. This alignment issue can make it harder to quickly identify who sent each message.

It would be beneficial if the chat interface could be redesigned to follow a more standard format seen in most popular messaging applications such as WhatsApp, Telegram, or Microsoft Teams. In these platforms, messages are typically encapsulated within distinct message bubbles or frames. The user's own messages are aligned to the right, while messages from other participants are left-aligned. This approach makes it much easier to visually separate and attribute messages to the correct sender, greatly improving readability and overall user experience.

Adding these UI enhancements would not only improve clarity but also create a more intuitive and familiar chat environment for users.

**Comment by ShGKme** [comment] 2024-09-25 16:59
> The user's own messages are aligned to the right, while messages from other participants are left-aligned

For this one there must be an issue already (cannot find)

**Comment by nickvergessen** [comment] 2024-09-26 07:49
Duplicate of #902

**Closed by nickvergessen** 2024-09-26 07:49 UTC
Labels: 0. Needs triage, enhancement
