### ISSUE TITLE
Send actual message along with notification of mention

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#879] opened 2018-05-09 09:03 UTC
Opened originally for the Android app at https://github.com/nextcloud/talk-android/issues/165 because the notification only shows "Ivan mentioned you in …" (not more cause phone width).

We should also show the actual message in the second row, so we need that from the server. cc @mario and also @ivansss because we'll need it there too.

**Comment by mario** [comment] 2018-05-09 09:08
If you want what you requested in the talk android app, we need a room display name too cause I will not do a regex replace on a multi-lingual content I might receive :)

**Comment by nickvergessen** [comment] 2018-05-09 09:10
The room name is inserted automatically (if one is set), we just say "public/group" when no name was set (in the ui we display all user names, but for notifications thats crap)

**Comment by jancborchardt** [comment] 2018-05-09 09:14
Right - in the call in question the name was indeed unset.

So we just need the actual message where you were mentioned.

**Comment by jancborchardt** [comment] 2018-05-14 15:47
Turns out we should get the participant list also, for when a call starts. Because there in the notification it says:
```A new group call has started in Groupname```
And nothing in the second line. Also, usually the notification is cut off on mobile, so we should shorten it to ```Incoming call from Groupname```?

It would be great to show the participants in the second line, so it’s like:
```Ivan, Joas, Mario & Dan```

**Comment by jancborchardt** [comment] 2018-05-28 14:18
@mario cool, ok – then can we show the list of users in the second row of the notification, as I mentioned? :)

**Comment by mario** [comment] 2018-05-28 14:28
No. The notification is shown, you click on the notification, a screen pops up, we find the room, get the list of participants.

So it happens AFTER the notification is shown.

It could happen before too, but network requests, etc, etc, so not really a good idea.

In addition, a participant list could be large.

(Sorry if I didn't make sense earlier)

**Comment by jancborchardt** [comment] 2018-05-31 01:17
Ok. But from the user perspective the notification is lacking information currently. We could solve this by sending 1 package with all the relevant info, including a truncated list of say, the first 5 participants.

**Comment by mario** [comment] 2018-06-30 10:44
@nickvergessen this is IHMO duplicate of https://github.com/nextcloud/spreed/issues/875.

**Closed** 2018-07-30 11:42 UTC
Labels: 1. to develop, design, enhancement, feature: api, feature: chat, mobile apps
