### ISSUE TITLE
participants shine through popup

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3472] opened 2020-05-06 21:33 UTC
Tested with Talk 9.0-beta. Clicking the "..." menu of a participant on the sidebar opens a popup in a way that you still see the remaining participants lists below. This makes the popup unreadable.

![image](https://user-images.githubusercontent.com/1589737/81230447-ce583900-8ff1-11ea-9328-d799236df4f4.png)

**Comment by nickvergessen** [comment] 2020-05-06 22:30
Duplicate of #2575

**Closed by nickvergessen** 2020-05-06 22:30 UTC
Labels: 0. Needs triage, bug
