### ISSUE TITLE
Video starts abruptly, taking people by surprise - Let's have a lobby area

### ISSUE THREAD

**Issue by luminous706** [nextcloud/spreed#5066] opened 2021-02-02 17:21 UTC
**Is your feature request related to a problem? Please describe.**
Yes, right now, as soon as you join a call, browser asks to authorise audio/video for the site, and when you say "allow" it would put you into the conversation with webcam on, the user can only disable his webcam once everyone sees them first, but not before joining.

This is not what people are used to and are taken by surprise. A private lobby is expected where you can control a few things, look at yourself, and then join the convo with video or audio on or off.

**Describe the solution you'd like**

You join a call, browser asks if you want to allow audio/video (you click "allow"), you join into a "lobby/waiting room" area where you're not officially in the call yet, but you can look at yourself, disable video if you want, etc. Then, you click "join" to officially join the conversation - just like Teams, Zoom, Google Hangout, etc.

**Describe alternatives you've considered**

I have to tell people to "be careful, the camera will start right away when you join a call, please hide it with your hands and then disable the video at the bottom if you don't want to be seen".

**Comment by HammyHavoc** [comment] 2021-02-07 10:31
Agreed. Being able to join with your video disabled, and enable it at a later point (when/if necessary) is fairly important whilst working from home.

**Comment by nickvergessen** [comment] 2021-02-07 10:56
cc @jancborchardt can't find the duplicates atm.

**Comment by PVince81** [comment] 2021-02-16 10:30
closing as duplicate of https://github.com/nextcloud/spreed/issues/3270 where topics like defaults for video/audio and pre-join screen are being discussed

**Closed by PVince81** 2021-02-16 10:30 UTC
Labels: 0. Needs triage, enhancement
