### ISSUE TITLE
Auto delete conversations after some time

### ISSUE THREAD

**Issue by Th3l5D** [nextcloud/spreed#11613] opened 2024-02-20 17:44 UTC
Is it possible to add an option to automatically delete a group conversation after some time. The main idea here is to keep a clean conversation listing and to not have any sensitive information indefinitely stored on Talk.

As explained below automatic messages deletion could be an alternative but not as user friendly as needed.

---

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Setting proposed to the conversation owner, during a group conversation creation screen and on conversation settings. Time should be user defined.

**Describe alternatives you've considered**
Auto delete message may be used but:

- The setting is not on the group conversation creation screen
- The max time for the auto delete message is 4 weeks, and thus not user defined

**Comment by nickvergessen** [comment] 2024-02-21 09:42
Duplicate of https://github.com/nextcloud/spreed/issues/5972

**Closed by nickvergessen** 2024-02-21 09:42 UTC
Labels: 0. Needs triage, enhancement
