### ISSUE TITLE
No indication of a video conference going on

### ISSUE THREAD

**Issue by omyno** [nextcloud/spreed#2234] opened 2019-09-26 22:22 UTC
When opening a Nextcloud shared link to a call, the chat list opens instead of the voice/video call itself. The user needs to click on a very small button in the top right corner to enter the actual video call. See the screenshot below.

**Describe the solution you'd like**
When opening the link to a call, the user enters the voice/video call automatically.

**Describe alternatives you've considered**
The user is offered a big button with the option to participate in the call.

**Additional context**
![spreed](https://user-images.githubusercontent.com/2902513/65728830-7ac95880-e0bc-11e9-84f9-7947bc276880.png)

**Comment by nickvergessen** [comment] 2019-09-27 08:02
Duplicate of https://github.com/nextcloud/spreed/issues/534

**Closed by nickvergessen** 2019-09-27 08:02 UTC
Labels: 0. Needs triage, enhancement
