### ISSUE TITLE
new-message-form__input unusable in case of window width < 512px and after once app-navigation click

### ISSUE THREAD

**Issue by drlight17** [nextcloud/spreed#12236] opened 2024-04-27 11:56 UTC
## Steps to reproduce
1. Set browser window width less then 512 px
2. Open conversation
3. Open and close app-navigation menu
4. Focus on new-message-form__input and try to type something

### Expected behaviour
Typed text must appear in new-message-form__input to further send

### Actual behaviour
No typed text in new-message-form__input

## Talk app

**Talk app version:**
18.0.7

## Browser

**Operating system:** 
Any (Mac, Windows, Linux)

**Browser name:** Chrome/Firefox

**Browser version:** 124.0.6367.60/115.9.1esr

**Nextcloud Version:**
28.0.4 AIO

**Comment by SystemKeeper** [comment] 2024-04-27 20:01
Should be a duplicate of https://github.com/nextcloud/spreed/issues/11454

**Comment by nickvergessen** [comment] 2024-04-29 10:52
Duplicate of #11454

**Closed by nickvergessen** 2024-04-29 10:52 UTC
Labels: 0. Needs triage, bug
