### ISSUE TITLE
mobile app should be suggested

### ISSUE THREAD

**Issue by mokkin** [nextcloud/spreed#3275] opened 2020-04-06 16:17 UTC
For performance reasons on mobile devices such as Android or iOS, the mobile apps should be suggested when nextcloud detects a mobile device.

**Comment by nickvergessen** [comment] 2020-04-06 16:27
Duplicate of https://github.com/nextcloud/spreed/issues/1088

Do you want to work on this? 😎

**Closed by nickvergessen** 2020-04-06 16:27 UTC
Labels: 0. Needs triage, enhancement
