### ISSUE TITLE
Quick multi user direct message 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#4448] opened 2020-10-23 09:35 UTC
**Is your feature request related to a problem? Please describe.**
Often I use mail to reach more then user because it's felt harder to create a talk group give it a name and send the message

**Describe the solution you'd like**
Implement a direct message function like in
rocket.chat: https://docs.rocket.chat/guides/user-guides/direct-messages-between-multiple-users
mattermost: https://docs.mattermost.com/help/getting-started/organizing-conversations.html#direct-messages-and-group-messages

Just choose your members and start a group chat without group name.

**Comment by nickvergessen** [comment] 2020-10-23 09:44
Duplicate of https://github.com/nextcloud/spreed/issues/4254 ?

**Comment by jakobroehrl** [comment] 2020-10-23 09:50
This issue is just about quick group creation without choosing a group name basicly.
https://github.com/nextcloud/spreed/issues/4254 is about the same with the difference that for the recipients shows as 1:1 conversation (not as a group)

**Comment by jakobroehrl** [comment] 2020-10-28 09:24
Maybe we want to change in the future the chat room creation.
For example: Choose the members first and preselect the groupname with some of the member names? 
Then the user can create quick or change the group name

**Comment by nickvergessen** [comment] 2021-11-18 16:24
Tracked in #4254

**Closed by nickvergessen** 2021-11-18 16:24 UTC
Labels: 1. to develop, enhancement, feature: chat  💬
