### ISSUE TITLE
Push to talk, push to mute

### ISSUE THREAD

**Issue by Nyco** [nextcloud/spreed#3509] opened 2020-05-12 16:32 UTC
**Is your feature request related to a problem? Please describe.**
Two opposite stuations:
- When I am muted, I want to briefly say something to all other participants, and immediately go back to mute
- When my mic is active, I want to briefly mute to sneeze or cough, and immediately go on

It is painfly to look for the very small mic button, aim at it, click on it, do the stuff, and then click again on it.

**Describe the solution you'd like**
Having “Push to talk” and “Push to mute” options, whould allow to win some precious time, and add some dynamics to call already impacted by lag.

The spacebar key is the de facto standard keyboard shorcut, 

**Let's try some Gherkin**

* Push to talk

GIVEN my mic is muted
WHEN I press spacebar
  AND keep spacebar pressed
THEN my mic is active

GIVEN my mic is active
  AND my spacebar is pressed
WHEN I release the spacebar
THEN my mic goes back to muted

* Push to mute

GIVEN my mic is active
WHEN I press spacebar
  AND keep spacebar pressed
THEN my mic is muted

GIVEN my mic is muted
  AND my spacebar is pressed
WHEN I release the spacebar
THEN my mic goes back to active

**Describe alternatives you've considered**
Push to talk is implemented in most videoconferencing tools.
=> It would be nice to have it in Talk, as it is kind of a lacking feature, which is quite simple and expected from the user point of view.

Some such tools add the "raise hand" to be able to speak when muted, but this is linked to some sort of adminstrative powers, which is more complex.
 
A push to talk/mute is quite an individual feature, and in full control of the user without rights/privilegdes or actions by others, giving immediate results.

**Additional context**
Push to mute, I have seen it anywhere so far, so this might be a funny and useful differentiator for Talk, to be promoted.

**Comment by Nyco** [comment] 2020-05-12 16:33
An old ticket: Implement Push-To-Talk #603

**Comment by nickvergessen** [comment] 2020-05-12 16:48
You can press `m` when the chat is not focused to toggle the microphone on and off.

Apart from that closing as duplicate of #603

**Comment by Nyco** [comment] 2020-05-12 20:30
Please reconsider this ticket, as it is neither m, neither push-to-talk alone.

**Comment by ma12-co** [comment] 2020-05-14 08:15
What about push to mute @nickvergessen, I think it'd be nice to have!

**Comment by ma12-co** [comment] 2020-05-14 08:24
Ok let's update the other issue and close this

**Closed** 2020-05-14 08:28 UTC
Labels: 0. Needs triage, enhancement

**Comment by Nyco** [comment] 2020-05-15 12:56
Thanks, but I fear I do not understand the move. You have just copied part of this ticket. Why not keep this new one, and close the other poorer, old, untouched one?

**Comment by ma12-co** [comment] 2020-05-15 13:50
Before opening a new issue you should always check if there's an already open similar issue with an ongoing discussion. In that case, the best thing to do is just to continue the discussion there and not start a new similar issue to avoid duplicating the discussion.

**Comment by Nyco** [comment] 2020-05-15 14:14
Thanks for the friendly reminder. :)

I just wanted to underline that it is a new unseen feature... De nada, you're welcome. :-p

**Comment by nickvergessen** [comment] 2020-05-15 15:56
Why we keep the older issue is because people might have subscribed, etc.
So the oldest one always remains.
