### ISSUE TITLE
Let guests join via link without having to login - IOS Nextcloud Talk

### ISSUE THREAD

**Issue by JoeBoll** [nextcloud/spreed#4220] opened 2020-09-24 10:19 UTC
At the moment within the app, people cannot join a message or call for a nextcloud instance they aren't logged into, even if they have a link to join as a guest.
A user from: example.**com** cannot join a call or conversation as a guest from example.**org** within the app. They will be forced to use their mobile web browser.

The best solution would be to:
- allow guest links to be entered on the login screen;
- possibly add a section for logged in users where guest links can be retained for future use. (similar to switching accounts)

**Comment by nickvergessen** [comment] 2020-09-24 10:58
Duplicate of https://github.com/nextcloud/talk-ios/issues/119

**Closed by nickvergessen** 2020-09-24 10:58 UTC
Labels: 0. Needs triage, enhancement
