### ISSUE TITLE
better distraction free mode

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#3109] opened 2020-03-20 10:48 UTC
When I switch to full screen we hide the right sidebar but not the left one. It would be nice if we could also collapse the left sidebar to have a distraction free view on the call and the most possible space for a shared screen.

Additionally it would be nice if I could also collapse the left sidebar in the normal view. It uses quite a lot of space which is often not needed during a call.

**Comment by nickvergessen** [comment] 2020-03-20 10:54
Duplicate of #3082

**Closed by nickvergessen** 2020-03-20 10:54 UTC
Labels: 0. Needs triage, enhancement
