### ISSUE TITLE
Telegram integration not work

### ISSUE THREAD

**Issue by poltrian** [nextcloud/spreed#4480] opened 2020-10-27 21:52 UTC
## Steps to reproduce
1. activate Talk Matterbridge App
2. enabele the app in Talk configuration
3.Create an Telegram Bot
4. Add Bot Apikey and chatid to Talk configuration
5. There is nothing like Save
6. activate the Bridge

### Expected behaviour
Tell us what should happen

Du hast Matterbridge so eingerichtet, dass diese Unterhaltung mit anderen Chats synchronisiert wird.

### Actual behaviour
Tell us what happens instead
nothing, the log is empty

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
10.0.1,

**Comment by nickvergessen** [comment] 2020-10-27 22:17
Duplicate of https://github.com/nextcloud/talk_matterbridge/issues/16

**Closed by nickvergessen** 2020-10-27 22:17 UTC
Labels: 0. Needs triage, bug
