### ISSUE TITLE
Laser Pointer Feature: point at something on shared screen of another participant

### ISSUE THREAD

**Issue by srkunze** [nextcloud/spreed#3141] opened 2020-03-24 12:25 UTC
Using Nextcloud Talk is really cool and works pretty well.

There's just one thing, we sometimes miss: point at something on somebody else's shared screen/application/tab.

Situation: they are sharing a screen. I see something they don't see. But it's necessary for them to see it. Then we need to verbally communicate where exactly I'm looking at. Even worse, they need to interact with an UI element, but don't see exactly where and how.

Pointing them at the right spot would be extremely helpful.

Mouse takeover (like team viewer) is not needed - pointing only suffices.

**Comment by nickvergessen** [comment] 2020-03-24 14:50
> Mouse takeover (like team viewer) is not needed - pointing only suffices.

This is also not possible with WebRTC anyway.

Duplicate of #449

**Closed by nickvergessen** 2020-03-24 14:50 UTC
Labels: 1. to develop, enhancement, feature: WebRTC 🚡
