### ISSUE TITLE
Add support for disabling Google WebRTC Auto Gain Control

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/spreed#4898] opened 2021-01-06 16:14 UTC
Any browser that is Chromium based, out of the box has Auto Gain Control built-in for WebRTC. And this can be very frustrating in that it turns your microphone down/up when you may not even want it (without realising it).

Furthermore, Google/Chromium devs don't really seem interested in letting you disable this: https://bugs.chromium.org/p/chromium/issues/detail?id=435112#c3

The "solution" is for WebRTC tools (in this case Talk/Spreed) to implement "JS can disable AGC if it chooses to by using the getUserMedia constrain "googAutoGainControl" and setting it to false"

Is there any way we could get support for disabling this baked into Talk/Spreed directly, please? (when used in Chromium based browsers, of course).

**Comment by nickvergessen** [comment] 2021-11-18 21:23
Duplicate of #3252

**Closed by nickvergessen** 2021-11-18 21:23 UTC
Labels: 1. to develop, enhancement, feature: WebRTC 🚡
