### ISSUE TITLE
(Option for a) Smaller contact list

### ISSUE THREAD

**Issue by ripper17** [nextcloud/spreed#12591] opened 2024-06-27 07:03 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:** 29.0.2

**Is your feature request related to a problem? Please describe.**
As soon as you have a couple of conversations in NC Talk, the contact list becomes very long.

**Describe the solution you'd like**
Have a smaller contact list: Only one line per contact, smaller icon (or no icon at all) . Slack and Mattermost use much, much less space per chat.

**Describe alternatives you've considered**
It could be dynamic: If you only have very few conversations and your window is large enough, use a large contact list style. Once you add more conversations or your window get's smaller, switch to a smaller representation style.

**Additional context**
None.

**Comment by nickvergessen** [comment] 2024-06-27 09:39
Duplicate of #11697

**Closed by nickvergessen** 2024-06-27 09:39 UTC
Labels: 0. Needs triage, enhancement
