### ISSUE TITLE
Client user interface system test and red/green light report before connection starts

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/spreed#1308] opened 2018-11-21 21:09 UTC
In my small world, every test I do shows me that my Talk Server works great. I'm at something that seems like microsecond delays while testing from a mobile device off WiFi with a medium signal strength to a desktop with a 1000 speed network connection to the server on the LAN. All other uses of the system seem to fail and everybody blames the other person's equipment and/or service for the failure; Verizon sucks, no Google phones suck, no Apple is evil... NET NEUTRALITY!!! FUCK THE FCC!!!

I'd really like to brag to others about how great Talk on Nextcloud is, but without accountability for the weak link in the use of the system, I can't do any gratuitous Nextcloud Talk promotion. 

I assume their's very few things to test that would ensure functionality. Connection speed and reliability at some load level, the connecting equipment's excess capacity to process the video, voice & text, as well as the servers ability to not display late packets even if it's recording the session for future rebroadcasting.

That system check would take us from a group of warring enemies to honest adults addressing a solvable technical problem. Maybe the shitty equipment that fails a test gets forced down to 640x480 and "[Phonograph](https://en.wikipedia.org/wiki/Phonograph)" quality mono sound?

**Comment by nickvergessen** [comment] 2021-03-25 09:29
Duplicate of  #1181

**Closed by nickvergessen** 2021-03-25 09:29 UTC
Labels: 1. to develop, enhancement, feature: call 👥
