### ISSUE TITLE
Expand message expiration to 3 and 6 months

### ISSUE THREAD

**Issue by koebi80** [nextcloud/spreed#13592] opened 2024-10-19 14:09 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

**Which Nextcloud Version are you currently using:**

- Nextcloud Hub 8 (29.0.7)
- Talk with (19.0.10) 

**Is your feature request related to a problem? Please describe.**

In our case, we use group chats and in these chats the user must find informations for a longer time as 4 weeks.
But it is not desirable to keep the messages available forever.

**Describe the solution you'd like**

Please extend the "message expiration" so that 3 months and 6 months can be selected.

The feature request https://github.com/nextcloud/spreed/issues/8547 may be also a solution for us.

**Comment by nickvergessen** [comment] 2024-10-19 14:51
Duplicate of #8547

**Closed** 2024-10-19 14:51 UTC
Labels: 0. Needs triage, enhancement

**Comment by koebi80** [comment] 2024-10-21 16:33
Is not a dublicate from https://github.com/nextcloud/spreed/issues/8547 !!!
I think its simpler to expand the drop-down entrys than expand the admin settings page!

**Comment by nickvergessen** [comment] 2024-10-21 17:31
> I would prefer to set message expiration to 6 Months or to 1 Year, or to define my own retention time, i.e. 180 Days.

That's exactly what you want. More suggested settings or a custom one.
