### ISSUE TITLE
 acoustic feedback when a user joins/leaves a call

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2345] opened 2019-10-22 10:14 UTC
A few different use cases:

1. starting One-to-one call: I start a call and it it is silent until the recipient picks up and start talking. That can be really surprising/irritating. A "ringing" sound on the caller side like your know it from phones would be nice so that you have a indicator that the phone on the other side rings and a indicator when the recipient joined.

2. staring Group calls: A acoustic signal when someone joins the group call, like you know it from most other online meeting tools would be nice. This way you know someone joined, can pause the conversation and allow the new participant to say "hello".

3. ending group or one-to-one calls: If someone leaves a call the other people should get a acoustic feedback that someone left. It happens to me already a few times that I continued talking while my chat partner left (by accident) and we only found out when he re-joined. This could be avoided by a acoustic feedback.

@tobiasKaminsky just for your information, as we discussed this recently

**Comment by tobiasKaminsky** [comment] 2019-10-22 11:05
Additionally to 1: with ringing sound you can adjust/check your volume, so that it cannot happen that your ear is destroyed or you do not hear the other because of accidently muting.

**Comment by nickvergessen** [comment] 2021-03-24 15:52
Duplicate of #1072

**Closed** 2021-03-26 13:28 UTC
Labels: 1. to develop, enhancement, feature: call 👥
