### ISSUE TITLE
An error occurred while fetching the participants

### ISSUE THREAD

**Issue by axelsegebrecht** [nextcloud/spreed#5380] opened 2021-03-18 17:41 UTC
## Steps to reproduce
1. Create a conversation (group or one to one)
2. Visit the conversation again later or in a new tab

### Expected behaviour
Conversation loads

### Actual behaviour
Page redirects to %URL%/apps/spreed/not-found and an error message is very briefly displayed `An error occurred while fetching the participants`

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
11.1.1

**Custom Signaling server configured:** 
no

**Custom TURN server configured:**  (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)
yes

**Custom STUN server configured:** (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)
no 

## Browser

**Microphone available:** yes
**Camera available:** yes
**Operating system:** Mac OS X 11.3 Beta (20E5210c)
**Browser name:** Firefox (and others)
**Browser version:** 86.0.1 (64-bit)

### Browser log

<details>
```
Conversation was not found anymore talk.js:1098:8085
    _startPullingMessages https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:1098
    _startPullingMessages https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:1098
    _joinRoomSuccess https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:1098
    joinRoom https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:1098
    joinRoom https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:1098
    e https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    c https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    _invoke https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    t https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    f https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    a https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    (Async: promise callback)
    f https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    a https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    h https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    h https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    L https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    signalingJoinConversation https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:120
    e https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    c https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    _invoke https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    t https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    A https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    a https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    (Async: promise callback)
    A https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    a https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    g https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    g https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    p https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:292
    onRouteChange https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2856
    Ge https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:7
    $emit https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:7
    n https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2856
    beforeMount https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2856
    p https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
    r https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
    r https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
    ve https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
    confirmTransition https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
    transitionTo https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
    push https://cloud.mkhackathon.org/custom_apps/spreed/js/talk.js?v=188ee9c8-16:2918
Error: Request aborted
    exports createError.js:16
    onabort xhr.js:74
    exports xhr.js:69
    exports xhr.js:13
    exports dispatchRequest.js:52
    promise callback*c.prototype.request Axios.js:61
    e Axios.js:76
    exports bind.js:9
    e participantsService.js:239
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    A talk.js:292
    a talk.js:292
    g talk.js:292
    g talk.js:292
    F participantsService.js:235
    n cancelableRequest.js:49
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    o talk.js:292
    s talk.js:292
    r talk.js:292
    r talk.js:292
    request cancelableRequest.js:48
    n ParticipantsTab.vue:246
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    y talk.js:2856
    a talk.js:2856
    w talk.js:2856
    w talk.js:2856
    cancelableGetParticipants ParticipantsTab.vue:231
talk.js:2856:112551
Error happened while getting chat messages. Trying again in  6 Error: Request aborted
    exports createError.js:16
    onabort xhr.js:74
    exports xhr.js:69
    exports xhr.js:13
    exports dispatchRequest.js:52
    promise callback*c.prototype.request Axios.js:61
    e Axios.js:76
    exports bind.js:9
    e messagesService.js:65
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    l talk.js:399
    a talk.js:399
    u talk.js:399
    u talk.js:399
    m messagesService.js:64
    n cancelableRequest.js:49
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    o talk.js:292
    s talk.js:292
    r talk.js:292
    r talk.js:292
    request cancelableRequest.js:48
    t MessagesList.vue:491
    c runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    f talk.js:399
    a talk.js:399
    h talk.js:399
    h talk.js:399
    getNewMessages MessagesList.vue:474
talk.js:399:91336
Navigating away, leaving conversation talk.js:2856:34601
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). gps.js:199:11
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). utils.js:35:9
No OC found index.js:46:12
JQMIGRATE: Migrate is installed, version 3.3.2 jquery-migrate.min.js:2:708
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:60:15
OCA.Comments.View initialized comments-app.js:31:21
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
Notifications permissions granted App.vue:306
OCA.Viewer initialized Viewer.js:49:10
No OCA.Files app found, viewer is now in standalone mode Viewer.vue:316
OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities capabilities.js:32:9
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:60:15
Setting current user App.vue:316
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 2 globals.js:60:15
Detected browser Firefox 86 (86.0) browserCheck.js:29:11
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
The following mime is already registered text/csv 
Object { id: Getter & Setter, group: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, … }
Viewer.vue:529
session heartbeat polling started session-heartbeat.js:97:9
Files_PDFViewer initialized for public page 
Object { isPublicPage: null, canDownload: true, isSecureViewerAvailable: false }
public.js:30:9
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
OCA.Sharing.ShareSearch not ready init-collections.js:44:10
OCA.Sharing.ShareSearch not ready init-collections.js:44:10
X-Nextcloud-Talk-Hash initialised:  2064902d14846a101eaad7b9afbd365a93551a62 talkHashStore.js:64:11
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 5 globals.js:60:15
[DEBUG] unified-search: Unified Search initialized with the following providers 
Object { 0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, … }
ConsoleLogger.js:42:18
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 5 util.js:133:11
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 5 util.js:133:11
```
</details>

## Server configuration

**Operating system**: Debian
**Web server:** Apache
**Database:** Maria
**PHP version:** 7.4
**Nextcloud Version:** 21.0.0
**List of activated apps:**

<details>
```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - announcementcenter: 5.0.0
  - calendar: 2.1.3
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - deck: 1.3.1
  - event_update_notification: 1.2.0
  - external: 3.8.1
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.10.0
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupfolders: 9.0.0
  - integration_gitlab: 0.0.15
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.13.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 1.7.5
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - ransomware_protection: 1.9.0
  - recommendations: 1.0.0
  - registration: 0.7.0
  - richdocuments: 4.0.3
  - richdocumentscode: 6.4.608
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.1
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - welcome: 0.0.5
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - circles
  - encryption
  - files_external
  - forms
  - mail
  - socialsharing_diaspora
  - user_ldap
```
</details>

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "cloud.mkhackathon.org",
            "2": "81.19.187.28",
            "1": "space.mkhackathon.org"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.0.18",
        "overwrite.cli.url": "http:\/\/space.mkhackathon.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en",
        "default_locale": "en_GB",
        "default_phone_region": "GB",
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "overwritehost": "cloud.mkhackathon.org",
        "overwriteprotocol": "https",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "2525",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "drawio"
        ],
        "maintenance": false
    }
}
```
</details>

### Server log (data/nextcloud.log)
<details>
```
https://cloud.mkhackathon.org/s/aNkYsdeppCD5pNY
```
Pass: L%!n&@FUesh3S7*mE*Jmv
</details>

**Comment by PVince81** [comment] 2021-03-19 07:09
if happening while switching fast (or during reload), then it's a duplicate of https://github.com/nextcloud/spreed/issues/4670

otherwise go to #5148

**Closed by PVince81** 2021-03-19 07:09 UTC
Labels: 0. Needs triage, bug
