### ISSUE TITLE
Basic text formatting to chat

### ISSUE THREAD

**Issue by theel0ja** [nextcloud/spreed#1027] opened 2018-07-09 00:22 UTC
I would like to have at least basic text formatting for chat, such as

* Basic text formatting, such as
      **bold**, _italic_ and ~~strikethrough~~
* and code tags like this:
      `console.log("Hello!");`
* and multi-line code this:
```html
<html>
  <head></head>
  <body></body>
</html>
```

---

- [x] https://github.com/nextcloud/spreed/issues/9950
- [x] https://github.com/nextcloud/spreed/issues/9949
  - [x] Above ticket is for rendering in the chat view
  - [ ] Input field option is raised in the vue library: https://github.com/nextcloud/nextcloud-vue/issues/4355
- [ ] https://github.com/nextcloud/talk-ios/issues/1299
- [x] https://github.com/nextcloud/talk-android/issues/3176
    - [x] https://github.com/nextcloud/talk-android/issues/3154

---

## Spreed app

**Spreed app version:** Talk 3.2.2

## Server configuration

**Nextcloud Version:** 1.0.4

**Comment by nickvergessen** [comment] 2018-07-09 09:19
I think most other things have bold and italic, so that's okay.
Not sure about code tags thou. THat will cause big trouble when we integrate with other services.

**Comment by nickvergessen** [comment] 2018-07-19 10:12
Checked the messengers which I use:

IM | bold | italic | striked | code
---|---|---|---|---
Whatsapp | \* | \_ | \~ | \`\`\`
Threema | \* | \_ | \~ | :heavy_multiplication_x: 
Telegram | \*\* | \_ \_ | :heavy_multiplication_x: | \`\`\`
Signal | :heavy_multiplication_x:  | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x: 
Line | :heavy_multiplication_x:  | :heavy_multiplication_x: | :heavy_multiplication_x: | :heavy_multiplication_x:

**Comment by nickvergessen** [comment] 2018-07-30 10:49
Survey: Should we support * as bold?

**Comment by nickvergessen** [comment] 2018-07-30 10:49
Survey: Should we support _ as italic?

**Comment by nickvergessen** [comment] 2018-07-30 10:49
Survey: Should we support ~ as striked?

**Comment by nickvergessen** [comment] 2018-07-30 10:50
Survey: Should we support \`\`\` as code?

**Comment by fancycode** [comment] 2018-07-30 11:00
> Survey: Should we support ``` as code?

Backticks are bad on a German keyboard layout, but they are also consistent with markdown.

**Comment by mario** [comment] 2018-07-30 11:13
Why not add a full markdown support while we're at it? :)

**Comment by nickvergessen** [comment] 2018-07-30 11:14
> Why not add a full markdown support while we're at it? :)

Because at somepoint we would like to integrate with other services (see https://github.com/nextcloud/spreed/labels/feature%3A%20integration ) which is highly difficult then

**Comment by theel0ja** [comment] 2018-07-30 19:31
I'd add most stuff, but for example not headings because they aren't needed in chats.

**Comment by nickvergessen** [comment] 2018-08-01 12:57
Well as for markdown, apart from the things in the poll the following are missing:
* url - but you can post plain urls, which are still made clickable, you can just not mask them
* images - we will allow posting images in another way (similar to how all other IMs do it.
* lists - do you really need lists in chat messages?
* headlines - see `lists`

**Comment by fancycode** [comment] 2018-08-01 12:59
I think you can skip lists and headlines. If people want to write documents, they should not use the chat but some editor app :speak_no_evil:

**Comment by jospoortvliet** [comment] 2018-08-07 16:59
Lists do make sense, though, I use it also in chat... But certainly bold, underline, strike-through and code are much more important. Headlines do seem weird yes.

**Comment by ryanprior** [comment] 2019-04-10 18:58
With regard to https://github.com/nextcloud/spreed/issues/1027#issuecomment-408828927 (suggestion for full Markdown support)

I don't like the idea of having people post links (including potentially misleading ones,) images, or headlines to chat.

Syntax compatibility with markdown might be the most appropriate, but "full Markdown" seems like an own goal.

**Comment by ryanprior** [comment] 2019-04-10 19:01
Also, info for @nickvergessen & others who prioritize issues: this is one of the major blockers keeping me from using Nextcloud Chat. I frequently post code & read other people's code in chat, and need it to be formatted nicely.

I would be interested in working on this issue if it's something you would like outside help on.

**Comment by lachmanfrantisek** [comment] 2019-04-11 07:28
What about some quote/citation?

`>` used in markdown would be useful for that:

Example:

```
> something
```

> something

**Comment by nickvergessen** [comment] 2019-04-11 09:18
> I would be interested in working on this issue if it's something you would like outside help on.

No objection at all. Everything that is not actively being worked on can be picked up. The main issue I see is:
1. This needs to also work on iOS/Android
2. It should be mostly done in the UI so third party integration works as good as possible
3. There is a difference between markdown and all other chat clients how to do bold/italic
4. The next thing on our todo is to bring the UI to VueJS (https://github.com/nextcloud/spreed/issues/1347) and that might heavily conflict with any work being done, because we are basically redoing the UI.

**Comment by ryanprior** [comment] 2019-04-17 15:33
How is the Android/iOS app built right now? I've never done mobile app development so I'm pretty ignorant of that side of things.

As far as building it into the UI and making it Vue proof, we might build it as an embedded Vue component right away without waiting for the rest of the UI to be re-done. My understanding is that Vue components can play well next to other things and it's not all-or-nothing.

**Comment by tiotrom** [comment] 2019-10-28 03:22
I would love to see parts of the markdown being implemented too. Especially for code or quotes. Is one thing that I find it as a "must" for a text-chat.

**Comment by Gadgitmatic** [comment] 2019-11-12 05:32
Formating using keyboard shortcuts (CTRL+B, CTRL+U. etc)  **will apply as expected** in the preview box, **however, it does not carry formatted once submitted** into Talk's conversation area.
GIF screen capture below. 

![Peek 2019-11-12 00-06](https://user-images.githubusercontent.com/28793787/68644401-de7bd980-04e2-11ea-86f9-26cbdec76185.gif)
Sorry for the flicker. I promise it's not subliminal messaging.

Tested on 
Nextcloud 17.0.1
Chromium Version 78.0.3904.97 (Official Build)

**Comment by boppy** [comment] 2020-03-01 19:35
> I would love to see parts of the markdown being implemented too. Especially for code or quotes. Is one thing that I find it as a "must" for a text-chat.

Totally in for that. But I'm also all in for full markdown support. YES, it makes no sense to have links and or images available in two ways, BUT: markdown seems to me as a standard nowadays - for most devs at least. So why not supporting it? It would be easily integrated into apps and services, because there are tons of middlewares available. No need for a new parser - okay, yes, this is also true for stripped down markdown... ¯\_(ツ)_/¯

> Survey: Should we support ``` as code?

Triple is multiline. Might be intentional, might be a wrapping flaw by github (three single backticks do not convert to one single backtick shown as code). But I would go for a single backtick for inline code (and also triple for multiline).

**That would be the most complete and useful *input* to me (from slack):**

![image](https://user-images.githubusercontent.com/749141/75632113-415fc080-5bf9-11ea-9ca5-d98248c76427.png)

ltr:

- bold
- italic
- striked
- inline-code
- link
- num list
- unsorted list
- quote
- multiline code
*space*
- hide toolbar (image below)
- search for @&lt;query>
- 💩 selector

**reduced**
![image](https://user-images.githubusercontent.com/749141/75632217-47a26c80-5bfa-11ea-9f01-b1f5e098f125.png)

**small (as reply) w/ `…` menu**
![image](https://user-images.githubusercontent.com/749141/75632244-71f42a00-5bfa-11ea-8c0b-20a5a335a894.png)

> Formating using keyboard shortcuts (CTRL+B, CTRL+U. etc) will apply as expected in the preview box, however, it does not carry formatted once submitted into Talk's conversation area.

For me on latest chrome dev I have it as `<html>` transmitted.

**Comment by githubkoma** [comment] 2020-04-30 07:02
It would be so nice in the first step to be able to link shorter URLs in Chat.

Helps the integration for other apps as well, as they can post a short Link into a Room/Conversation, that points to the other apps resource.

Current: https://mynextcloud.com/index.php/app/MyApp/#myCustomParameter=123
Future:  like: **MyApp Link1** 
             `[MyApp Link1](https://mynextcloud.com/index.php/app/MyApp/#myCustomParameter=123)`

**Comment by tromlet** [comment] 2020-08-11 21:20
>Survey: Should we support ``` as code?

I would recommend ``` as multi-line code, and ` as a single line code. 

Honestly, I see the Nextcloud Talk app as more of a competitor to Mattermost/RocketChat/Slack/Teams than to, say, Signal etc - although as a paranoid open-source fanboy, hook me up with those off-the-record end-to-end encrypted chats, fam.

**Comment by Cacodaimon** [comment] 2020-08-31 11:20
I am not in nextcloud development and architecture, but would it be possible to develop a plugin (as app available in the app store) for Talk which adds e.g. Markdown support?

**Comment by nickvergessen** [comment] 2020-08-31 11:22
Not really, because the mobile apps would still not understand it and show `![image](url to image)` then instead of an image. Also instead of implementing an additional addon, a PR to this app here would be enough.

**Comment by Cacodaimon** [comment] 2020-08-31 11:35
@nickvergessen I see, but if we ignore the fact that the apps would show plain markdown instead of formatted content would it be possible to build such a plugin which would work in the web / browser version only?

Maybe the formatting could be stripped (e.g. **Bold** becomes Bold) for apps consuming the API?

**Comment by nickvergessen** [comment] 2020-08-31 11:36
Well all apps and the browser use the same API. But that is also not an issue. If we want this we just need to do it properly and tell the mobile apps to also understand it.

**Comment by Cacodaimon** [comment] 2020-08-31 11:42
@nickvergessen I see so a hint when fetching messages e.g. `formattedContent = true` which defaults to `false` could do the trick.

The apps does not know about this hint and gets content without formatting and the browser uses the hint to get formatted or plain markdown content.

**Comment by nickvergessen** [comment] 2020-08-31 12:44
Well we just bump the api version in that case, and you use `api/v3` for with markdown as ultimatly all clients need to support this.

**Comment by Cacodaimon** [comment] 2020-08-31 14:17
What should happen with the V2 API? 
Should it strip markdown content or would it cause some backward compatibility issues? (Maybe configurable)

The V3 in this case would pass the content as it is to client and the client would handle the formatting?

Any other requirements for an proper PR?

In this case I would set up an dev environment and dig into next cloud development this weekend.

**Comment by Rik44444** [comment] 2020-09-16 11:15
yes to add to this thread, hyperlink support (see link above) would be great

**Comment by Cacodaimon** [comment] 2020-09-21 16:44
@nickvergessen Hey I made some progress integrating markdown support, you can review my changes here: https://github.com/nextcloud/spreed/compare/master...Cacodaimon:master .

For easier testing I skipped using `RichText` as external component  ("@juliushaertl/vue-richtext"), maybe keeping the component here makes more sense because many specific styles where needed to reset the NextCloud default styles on HTML elements like lists or italic text… . 

The used markdown library ([remark-parse](https://github.com/remarkjs/remark/tree/main/packages/remark-parse)) might look a little bit over sized for the task but was needed to preserve the features like placeholders and component support of the old RichText component and render the formatted content with VUE's render method instead of displaying plain HTML.

The API side is still missing (the discussed markdown stripping for mobile apps until they support markdown), I could need some directions where to start in the PHP code.

There are two screen shots of my progress.

![Basic markdown](https://user-images.githubusercontent.com/2429503/93793947-c6fb9a00-fc37-11ea-9e66-b5909368302a.png)

![Mention and Quote Support](https://user-images.githubusercontent.com/2429503/93793966-cbc04e00-fc37-11ea-96ba-1c62aa6118e2.png)

I skipped @boppy suggestion of an advanced text input component with formatting support, because I think that this could be added independently of the basic MD support here.

Please give me your opinion if I am on the right way of an mergeable pull request.

**Comment by nickvergessen** [comment] 2020-09-21 16:59
I'm not too familiar with markdown libs, but the Text app seems to use `markdown-it`.
Maybe @juliushaertl can say if that was a good choice? If so I would like the same lib, so people and fixes can be used more efficiently

**Comment by Cacodaimon** [comment] 2020-09-21 17:54
@nickvergessen @juliushaertl I have already used markdown-it in another project and it work great, but the downside of markdown-it is that it just renders markdown as plain HTML string (as far as I know). 

Hence the original `RichText` component supports Vue.js components as placeholders e.g. mentions… I had to use a more advanced markdown lib which converts markdown to an AST. This enables extending the syntax (placeholders), choose how to render (via Vue's render method) and more post processing.

The same lib could be used remove markdown where needed, too: https://github.com/nextcloud/spreed/commit/0d291980bb8e58f5652fe91250f29a92c56674f8

**Comment by juliushaertl** [comment] 2020-09-22 06:46
> I have already used markdown-it in another project and it work great, but the downside of markdown-it is that it just renders markdown as plain HTML string (as far as I know).

There is also a parse method for markdown-it (https://markdown-it.github.io/markdown-it/#MarkdownIt.parse)

The general approach seems good to me, though I'm a bit hesitant towards the larger list of additional dependencies https://github.com/nextcloud/spreed/compare/master...Cacodaimon:master#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40-R52 so it might be worth to check if this would be something that could also be implemented with markdown-it. However I did not have a detailed look at remark/rehype yet, so the amount of packages is of course not meaningful.

Also I think we could even move the markdown behavior to vue-richtext so other apps can make use of it as well in case we bring markdown support to comments or other areas. What do you think?

**Comment by Cacodaimon** [comment] 2020-09-22 12:52
@juliushaertl thanks for your response!

> > I have already used markdown-it in another project and it work great, but the downside of markdown-it is that it just renders markdown as plain HTML string (as far as I know).
> 
> There is also a parse method for markdown-it (https://markdown-it.github.io/markdown-it/#MarkdownIt.parse)

I took a look at markdown-it's `parse` method, it just returns a list of tokens, so its rather a tokenizer. 
So I would need to build an AST from the list, the lib `'markdown-it-ast'` seems to be unmaintained and does nor produce a valid AST in my test.

Therefore the steps to archive the same would be:

* Rendering markdown:
  * Extend markdown-it syntax to support placeholders e.g. `Hello {world}!`, this seems to involve more code to write and maintain in markdown-it (example [markdown-it-kbd](https://github.com/jGleitz/markdown-it-kbd/blob/master/src/index.ts)) as in comparison to the custom remark-parse [plugin](https://github.com/nextcloud/spreed/blob/f3931c2ee06a5014d047857d68c24630bd7887ac/src/components/RichText.vue#L13) used here.
  * Convert the token list manually to an AST.
  * Traverse the AST and render nodes using Vue.js's render method.
* [Removing markdown](https://github.com/nextcloud/spreed/commit/0d291980bb8e58f5652fe91250f29a92c56674f8)
  * Manually convert the token list to plain text?

So after my **quick** research it should be possible to use marokdown-it to archive the same goal, but with more hand crafted code instead of lib usage. The unified lib with it's remark, rehype… plugins is more versatile, it could even used to convert HTML pasted in the chat message input to markdown 🤯. So please make a choice whether to keep my current solution or enforce me to rewrite it to markdown-it ;) . 

> Also I think we could even move the markdown behavior to vue-richtext so other apps can make use of it as well in case we bring markdown support to comments or other areas. What do you think?

Sure only the following [test](https://github.com/juliushaertl/vue-richtext/blob/d1a36770cb7795841a4143f9a154a90b29a13cce/tests/richtext.spec.js#L125) would fail due to remarks's autolink function, but links with ending braked would work as markdown link.

> …maybe keeping the component here makes more sense because many specific styles where needed to reset the NextCloud default styles on HTML elements like lists or italic text…

There is only open question where to keep the [styles](https://github.com/nextcloud/spreed/blob/f3931c2ee06a5014d047857d68c24630bd7887ac/src/components/RichText.vue#L152)? Many reset code was needed hence nextcloud's styles overwrites some default HTML styles globally.

**Comment by juliushaertl** [comment] 2020-09-22 13:42
> So after my quick research it should be possible to use marokdown-it to archive the same goal, but with more hand crafted code instead of lib usage. The unified lib with it's remark, rehype… plugins is more versatile, it could even used to convert HTML pasted in the chat message input to markdown exploding_head. So please make a choice whether to keep my current solution or enforce me to rewrite it to markdown-it ;) .

Ok, that definitely sounds reasonable to me. That would probably something worth to check if we can make use of the same libs in text as well, since implementing a parser with the markdown-it capabilities also seemed like a a lot of custom implementation effort, so we are using some dirty workarounds over there right now.

> Sure only the following test would fail due to remarks's autolink function, but links with ending braked would work as markdown link.

I personally prefer that behaviour however the main concern @nickvergessen had about this is that this breaks for example wikipedia links like https://de.wikipedia.org/wiki/Klammer_(Zeichen)

> There is only open question where to keep the styles? Many reset code was needed hence nextcloud's styles overwrites some default HTML styles globally.

For the component itself I'd actually prefer to keep them renderless. However we could of course just export some common markdown styling so that apps could embed that then if needed.

**Comment by Cacodaimon** [comment] 2020-09-22 16:54
> That would probably something worth to check if we can make use of the same libs in text as well, since implementing a parser with the markdown-it capabilities also seemed like a a lot of custom implementation effort, so we are using some dirty workarounds over there right now.

Remind me about this when this issue is solved, maybe I can help out.

> I personally prefer that behaviour however the main concern @nickvergessen had about this is that this breaks for example wikipedia links like https://de.wikipedia.org/wiki/Klammer_(Zeichen)

I see maybe opening a ticket [here](https://github.com/gnab/remark/issues?q=) solves the issue (somewhere in the future) without putting own effort about fixing this, with the current auto link implementation like like this one http://git (local office git server) or https://192.168.1.101/foo does not get detected. So maybe is failing test can be ignored?

 > For the component itself I'd actually prefer to keep them renderless. However we could of course just export some common markdown styling so that apps could embed that then if needed.

Currently all classes can be [overwritten](https://github.com/nextcloud/spreed/blob/f3931c2ee06a5014d047857d68c24630bd7887ac/src/components/RichText.vue#L53) but I could although provide the default styles as a SASS + CSS file in the package dist folder, for self including, and omit the VUE component's styles.

**Comment by tromlet** [comment] 2020-09-22 19:44
Holy cats that is all great work @Cacodaimon! Hopefully you and the Nextcloud guys can come to some kind of agreement!

I DID notice a couple things in your example screenshots:

1. Text that was both bold and italicized did _not_ appear to work with asterisks
2. Your ordered list featured bullets, not numbers or letters identifying list items (and thus was not "ordered")
3. Your ordered and un-ordered sub-lists were not sub-lists at all

I freaking LOVE LOVE LOVE the small table in there, and was there single line and multi-line code formatting? E.g. `this` and
```
this?
```

**Comment by Cacodaimon** [comment] 2020-09-23 14:04
@juliushaertl You might find find a [pull request](https://github.com/juliushaertl/vue-richtext/compare/master...Cacodaimon:master) once I was able to fix the `rollup.config.js`.

@tromlet Thanks! But the most work comes form the libs used.

I have used [this markdown example](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) as test content, maybe the lib and the test content does not use the same markdown flavor. Currently ordered lists gets rendered as unordered 🤦. But sub lists are working it seems that my test content had some formatting issues here.

**Comment by Cacodaimon** [comment] 2020-09-24 02:03
@juliushaertl you should already haven been notified by github about my [PR](https://github.com/juliushaertl/vue-richtext/pull/226), hopefully it is fine.

So the current diff would look like: https://github.com/nextcloud/spreed/compare/master...Cacodaimon:master

@nickvergessen @juliushaertl From now on I could need some directions how to strip markdown in the PHP code for clients which does not support markdown (e.g. mobile clients)

**Comment by nickvergessen** [comment] 2020-09-24 05:17
If you don't mind, drop me an email to `<my github name>@nextcloud.com` then i will create you an account on our instance so we can chat about it or have a call.

**Comment by Cacodaimon** [comment] 2020-09-24 13:51
@nickvergessen thx I wrote you an mail about the invite.

**Comment by alexbijma** [comment] 2021-04-28 06:50
@nickvergessen could you give an update on this ticket? has there been any progress or any idea when this will be available within Talk via webbrowser?

**Comment by nickvergessen** [comment] 2021-04-28 07:50
It will only be available once we have time to implement it on all clients

**Comment by MaxHillebrand** [comment] 2021-05-24 09:15
full markdown support would be optimal, I would use it as soon as it is deployed!

**Comment by MohammedNoureldin** [comment] 2021-09-22 00:58
Hi there, thank you for this great app, is formatting coming any soon?

**Comment by IanChok** [comment] 2021-12-13 02:21
This is a really nice feature to have. What's the status so far?

**Comment by mortee** [comment] 2022-03-31 14:53
Yeah, what's up with this?

**Comment by oneWaveAdrian** [comment] 2022-05-12 14:03
@nickvergessen This feature is still requested, with a lot of interest to make Talk more coherent with platforms such as Slack or Mattermost, where basic text formatting (especially code) is standard practice. What happened to that MR from @Cacodaimon? Already looked very promising!

**Comment by nickvergessen** [comment] 2022-05-13 06:59
Yeah it is, like many other features, but it is currently not a priority item.

The PR has been merged IIRC, the problem is that Talk/Spreed is currently not using this input method and the transition to it was not straight forward last time a colleague tried it.

**Comment by danir-de** [comment] 2022-06-22 13:32
I just noticed that if you press CTRL+B, CTRL-U or CTRL+I in the chat box, the text changes its formatting to bold, underlined or italics, WYSIWYG-like.
When you send it, it turns into plain HTML though...

**Comment by ShGKme** [comment] 2022-11-02 18:23
> Is that a browser thing (Chrome) or baked into Talk?

This is browser thing of [contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable).

**Comment by seconddayout** [comment] 2023-05-08 17:29
Is this still underway?

**Comment by nickvergessen** [comment] 2023-05-08 19:57
Yes, we just talked about it again last week and discussed necessary steps and possible intermediate steps.

**Comment by nickvergessen** [comment] 2023-05-15 10:07
So NcRichText supports markdown, but similarly to GitHub it seems to use the double vs. single logic:

Input | Result
---|---
`__bold__` | __bold__
`**bold**` | **bold**
`_italic_` | _italic_
`*italic*` | *italic*

That however is not how telegram, whatsapp or any other handle them:
https://github.com/nextcloud/spreed/issues/1027#issuecomment-406226961

**Comment by AndyScherzinger** [comment] 2023-07-06 17:06
> So NcRichText supports markdown, but similarly to GitHub it seems to use the double vs. single logic:

That is also the logic markwon applies (markdown lib we use in files/talk Android), so I vote to go with the (more or less) standard markdown spec

**Comment by jancborchardt** [comment] 2023-07-11 10:15
Yep:
- People familiar with Markdown or who use text for formatting will appreciate the same syntax being used (that is, standard Markdown)
- For people not familiar with it we need a popover when text is marked for example (like other apps do).

**Comment by szaimen** [comment] 2023-07-19 17:39
Hi, so I created the following mockup:


![Image](https://github.com/nextcloud/spreed/assets/42591237/c430590a-1632-439d-8510-bf0854b37319)


When selecting the formatting, markdown syntax should be used to directly add characters around the marked text and adjust the look of it.

I hope this looks fine to you. Do you have some feedback?

**Comment by ShGKme** [comment] 2023-07-19 17:53
It's a bit unclear to me, how "remove formatting" is supposed to work

**Comment by nickvergessen** [comment] 2023-07-19 17:54
That would be on rightclick?
But that is something the vue library should handle anyway, so that when an app uses the input component it can say "yes markdown please" (like NcRichText afterwards for the posted messages already does for the post rendering)

**Comment by nickvergessen** [comment] 2023-07-19 18:01
> It's a bit unclear to me, how "remove formatting" is supposed to work

I guess that only would be available work, when the same style-marker (e.g. `**` in the screenshot) is to the left and right of the selection. But I agree that the removing thing looks very complicated.

**Comment by szaimen** [comment] 2023-07-19 18:02
> That would be on rightclick?

I would say it should rather be shown directly as soon as you select some text. (e.g. after the mouse click is done and text was selected)

> But that is something the vue library should handle anyway, so that when an app uses the input component it can say "yes markdown please" (like NcRichText afterwards for the posted messages already does for the post rendering)

indeed. So should we transfer the ticket to the vue library?

**Comment by szaimen** [comment] 2023-07-19 18:06
> > It's a bit unclear to me, how "remove formatting" is supposed to work
> 
> I guess that only would be available work, when the same style-marker (e.g. `**` in the screenshot) is to the left and right of the selection. But I agree that the removing thing looks very complicated.

Indeed that looks complicated. So lets for now not offer this.

New mockup:
![Board (12)](https://github.com/nextcloud/spreed/assets/42591237/b6b07856-7801-4cf6-9448-8806ed90108f)

**Comment by AndyScherzinger** [comment] 2023-07-19 18:21
@szaimen no underline since that is not supported by markdown (!)

**Comment by nickvergessen** [comment] 2023-07-19 18:21
> So should we transfer the ticket to the vue library?

No, because this ticket is for Talk, to handle the output result, notifications and everything else.
But feel free to create a new one there

**Comment by szaimen** [comment] 2023-07-19 18:32
> PS I actually never thought of UI options to insert markdown in first place

I was asked to create a mockup for this ticket so that is what I did. If we dont need this then I am fine as well. Do we simply need a decision on the syntax to use or what is needed from design perspective?

---

> @szaimen no underline since that is not supported by markdown (!)

All right. New one:
![Board (13)](https://github.com/nextcloud/spreed/assets/42591237/471d72b7-1b9e-468b-bfdd-47706cde2d96)

**Comment by nickvergessen** [comment] 2023-07-19 18:34
> I was asked to create a mockup for this ticket so that is what I did. If we dont need this then I am fine as well.

I guess it's fine. but as mentioned just not the right place and a different work task.
I will split the last mockup off into a new ticket inside the vue lib (with all relevant comment parts) and add it to the overview section of this ticket.


> Do we simply need a decision on the syntax to use or what is needed from design perspective?

Syntax is Markdown. Nothing to discuss there.

**Comment by AndyScherzinger** [comment] 2023-07-19 19:46
Afaik @jancborchardt mentioned such a helper function to add Markdown to the Editor field during the planning call. Nevertheless it is not mandatory for the first iteration of the feature bit a nice polishing to put on top, so should come last.

**Comment by marcoambrosini** [comment] 2023-07-20 05:10
I think that the menu upon selecting the text would be useful, but I would prefer to have a buttons bar with just the icons in line, just like in Nextcloud text's top-bar. I think it would be much less obtrusive.

**Comment by nickvergessen** [comment] 2023-07-20 05:25
@marcoambrosini please keep the frontend discussion in https://github.com/nextcloud/nextcloud-vue/issues/4355

**Comment by nickvergessen** [comment] 2023-08-08 10:02
Closing as the base work is done 🎉

**Closed by nickvergessen** 2023-08-08 10:02 UTC
Labels: 1. to develop, enhancement, overview, feature: chat  💬, client: 🤖🍏 mobile

**Comment by omoustaouda** [comment] 2024-03-01 14:56
well done to everyone involved here : )
i appreciate very much.

i needed this feature, and was searching about its current status.

i'm a software developer, and happy to contribute if needed,
just need a little overview about the current state.

**Comment by nickvergessen** [comment] 2024-03-01 14:57
Current status is "Completed, Markdown works"
