### ISSUE TITLE
Blank page, nothing appaers - Latest version Nextcloud talk v8.0.9

### ISSUE THREAD

**Issue by Thovi98** [nextcloud/spreed#3535] opened 2020-05-13 16:26 UTC
## Steps to reproduce
Go to Nextcloud spreed webpage

### Expected behaviour

See the conversations list and be able to start a new conversation

### Actual behaviour

I have a blank page.

## Browser

Firefox (Ubuntu and Android), Chromium (Ubuntu), Brave (Android)

**Operating system:** Ubuntu, Android (but I guess it's same on Windows)

**Browser name:** : Firefox (Ubuntu and Android), Chromium (Ubuntu), Brave (Android)

**Browser version:** Latest version of each browser

### Browser log

When I check the Firefox console, I see this. 

![Sélection_117](https://user-images.githubusercontent.com/51749973/81837953-c9413f80-9545-11ea-9ac5-422866ba97da.jpg)

## Server configuration

**Operating system**: Debian Yunohost

**Web server:** Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page) : 18.02

**List of activated apps:**

<details>

```
sudo -u nextcloud php7.3 /var/www/nextcloud/occ app:list
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.9.0
  - audioplayer: 2.10.0
  - audioplayer_editor: 0.2.2
  - bookmarks: 3.0.13
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - cookbook: 0.6.5
  - dav: 1.14.0
  - deck: 1.0.0
  - documentserver_community: 0.1.5
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - guests: 1.4.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - metadata: 0.11.1
  - music: 0.14.0
  - news: 14.1.7
  - nextbackup: 20.4.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - occweb: 0.0.7
  - ocr: 6.0.39
  - ocsms: 2.1.7
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - phonetrack: 0.6.2
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - unsplash: 1.1.5
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - weather: 1.7.2
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - recommendations
  - updatenotification



```
</details>

**Nextcloud configuration:**

<details>

```

sudo -u nextcloud php7.3 /var/www/nextcloud/occ config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "next.nohost.me"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.2.2",
        "overwrite.cli.url": "https:\/\/next.nohost.me",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updatechecker": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "integrity.check.disabled": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": "0.0",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "logout_url": "https:\/\/next.nohost.me\/yunohost\/sso\/?action=logout",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "uploaddetails"
        ],
        "theme": "",
        "data-fingerprint": "31cd84a3f8015641c0b6fb9f4fa8eee4",
        "has_rebuilt_cache": true
    }
}

```
</details>

Server is Yunohost. it is maybe a Yunohost related issue, as specified here : https://github.com/gary-kim/riotchat/issues/26#issuecomment-624661073. I think those issues are similar. 

Thanks for your time and your amazing work !!!

**Comment by gabooh** [comment] 2020-05-13 16:35
I had the same problem. Seams linked to https://github.com/nextcloud/server/issues/19102 because I see this in my logs : 
![Screenshot_20200513_183044](https://user-images.githubusercontent.com/3327028/81839584-0c041700-9548-11ea-94ea-4cf955bc0e26.png)

And after trying to fix it with various occ repair commands and installing the talk app again, I have this error now : https://github.com/nextcloud/spreed/issues/3534

**Comment by maxcolomb** [comment] 2020-05-13 16:50
Idem :
### Server configuration
Nextcloud version : 18.0.4.2
Operating system: Ubuntu 18.04.4
Web server: Apache/2.4.29 (Ubuntu)
Database: PostgreSQL 10.12
PHP version: 7.2.24

**Comment by nickvergessen** [comment] 2020-05-13 16:53
Duplicate of  #3532

**Closed by nickvergessen** 2020-05-13 16:53 UTC
Labels: 0. Needs triage, bug

**Comment by Thovi98** [comment] 2020-05-13 16:58
Woah thanks, I've deleted/reinstalled and now it works perfectly ! Huge thanks, this app is so great :smiley:

**Comment by maxcolomb** [comment] 2020-05-13 17:12
If you uninstall and reinstall the whole app, does it remove the past conversations ?

**Comment by Thovi98** [comment] 2020-05-13 17:14
> If you uninstall and reinstall the whole app, does it remove the past conversations ?

Nope, not for me !

**Comment by maxcolomb** [comment] 2020-05-13 17:18
Ok !! Well same here. Yes those apps are really great 
Thanks yall
