### ISSUE TITLE
Group Profile Picture

### ISSUE THREAD

**Issue by dolphinscorp** [nextcloud/spreed#8184] opened 2022-10-16 18:16 UTC
Hi 

We cannot find feature to set profile picture for group conversation in Talk? Is it possible in Nextcloud talk?

Please advice. Thanks

**Comment by nickvergessen** [comment] 2022-10-17 05:48
Duplicate of https://github.com/nextcloud/spreed/issues/927

See https://github.com/nextcloud/spreed/issues/927#issuecomment-1055195768 for my personal workaround

**Closed by nickvergessen** 2022-10-17 05:48 UTC
Labels: 0. Needs triage, enhancement
