### ISSUE TITLE
install talk 15.0.2 erro

### ISSUE THREAD

**Issue by TwoDogs2** [nextcloud/spreed#8497] opened 2022-12-30 19:51 UTC
install talk 15.0.2 erro
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
reference resources：https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

I strictly follow the manual，The result is still not good

**Comment by nickvergessen** [comment] 2022-12-30 19:54
Duplicate of #8496

Please do not reopen another issue about it.
You can easily continue to comment there, or you ask for help in https://help.nextcloud.com/c/support/7

**Closed by nickvergessen** 2022-12-30 19:54 UTC
Labels: 0. Needs triage, bug
