### ISSUE TITLE
Various issues in participant list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#4866] opened 2020-12-29 14:42 UTC
![various partiicpant list issues](https://user-images.githubusercontent.com/925062/103290898-ddf61900-49ea-11eb-8a6a-c5bfd1ca60fd.png)

![image](https://user-images.githubusercontent.com/925062/103291548-4eea0080-49ec-11eb-8753-4c1cfac479d4.png)

Possibly some of these are in the components instead of Talk, in that case they should be fixed there of course. :) 

- [ ] The hover/focus feedback does not have perfect half-circles on the left and right ends
- [ ] The hover/focus feedback of the first participant is overlapped by the white area below the search field
- [ ] On hover/focus, the border around the status icon of the avatar should also get that same grey color, cause we don’t want the border to appear as border, but as if it was transparent
- [ ] The video icon is vertically misaligned, slightly too high (especially visible when you are moderator and have the 3-dot menu too)
- [ ] Inbetween focusing the active tab of Chat/Participants/Settings and the search field (which you can change via arrow keys left/right), there is one focus step which doesn’t do anything, and hitting it can make people think that changing the tabs is not possible.
- [ ] People’s names are ellipsized before they need to be (see second screenshot)

Avatar menu:
- [ ] The avatar menu triangle is horizontally not centered below the avatar, but off to the left
- [ ] There is a huge vertical whitespace below the status in the avatar menu
- [ ] It is not possible to open anyone’s avatar menu with the keyboard, as you can not tab to it. The participant menu (Promote/demote, remove participant) is fine

@ma12-co

**Comment by nickvergessen** [comment] 2021-11-18 21:19
> The hover/focus feedback does not have perfect half-circles on the left and right ends

There is no more hover effect

> The hover/focus feedback of the first participant is overlapped by the white area below the search field

There is no more hover effect

> On hover/focus, the border around the status icon of the avatar should also get that same grey color, cause we don’t want the border to appear as border, but as if it was transparent

There is no more hover effect

> The video icon is vertically misaligned, slightly too high (especially visible when you are moderator and have the 3-dot menu too)

Centered now

> Inbetween focusing the active tab of Chat/Participants/Settings and the search field (which you can change via arrow keys left/right), there is one focus step which doesn’t do anything, and hitting it can make people think that changing the tabs is not possible.

We are using vue components nowadays, if there is still an issue it should be fixed there

> People’s names are ellipsized before they need to be (see second screenshot)

Not the case anymore

> The avatar menu triangle is horizontally not centered below the avatar, but off to the left

Menu is now vertical and the triangle is centered

> There is a huge vertical whitespace below the status in the avatar menu

Caused by the user status and avatar component? Needs fixing in the vue app

> It is not possible to open anyone’s avatar menu with the keyboard, as you can not tab to it. The participant menu (Promote/demote, remove participant) is fine

Caused by the avatar component? Needs fixing in the vue app

**Closed by nickvergessen** 2021-11-18 21:19 UTC
Labels: 1. to develop, bug, design, feature: frontend 🖌️
