### ISSUE TITLE
enable media playback within a conversation

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/spreed#5280] opened 2021-02-28 11:23 UTC
Use case for me would be to be able to play an audio or video file or embedded platform video in Nextcloud Talk in a conversation so that all participants can listen/view it in parallel.
This will be a welcome function, especially in the now mostly digital education work in schools and universities.

Related Issues for Android & iOS
nextcloud/talk-android#1043
https://github.com/nextcloud/talk-ios/issues/510

**Comment by nickvergessen** [comment] 2021-04-09 07:18
Duplicate of #4658

**Closed by nickvergessen** 2021-04-09 07:18 UTC
