### ISSUE TITLE
Password protected share page issues since NC 20 with Talk App enabled

### ISSUE THREAD

**Issue by Apieceofbluesky** [nextcloud/spreed#4561] opened 2020-11-06 15:58 UTC
Server Version: Latest snap on ubuntu 18.04, behind HAProxy reverse proxy

Issue: The page for a password protected file/document share doesnt display background image correctly, it gets tiled instead of centered. Also, there is a new button on that page "Passwort anfordern" ("Request Password") which only works for video verification. If the video verification is not activated, the button only offers a generic error message, quite confusing. 

I've also noticed, that the tiling of the background image happens simultaneously with the "Request Password" Button loading, i guess those issues are related. 

![image](https://user-images.githubusercontent.com/11054677/98425590-fd7d5f00-2095-11eb-9994-4d8fa7c4d2ba.png)

Edit: I've figured out, that the Talk app is responsible for this. The issue is gone after uninstalling Talk.

**Comment by nickvergessen** [comment] 2020-11-07 22:16
Duplicate of #2938

**Closed** 2020-11-07 22:16 UTC
Labels: 1. to develop, bug
