### ISSUE TITLE
Update UI when audio/video call is in progress but user has not joined yet

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#625] opened 2018-02-05 11:33 UTC
There is no way for users to see that an audio/video call is currently in progress in the room if they are in the room but didn't join the call yet. I think it would be nice to show this somewhere in the UI (maybe the right side where the room name is shown?).

**Comment by Ivansss** [comment] 2018-02-05 11:38
I also think that's a really important thing we need to add to the UI asap.
@jancborchardt Do you have any ideas here?

**Comment by nickvergessen** [comment] 2018-02-06 16:40
I think it is duplicate of #534

**Comment by fancycode** [comment] 2018-02-07 09:06
It's similar, #534 seems to be mostly about the "Join call" button.

**Comment by nickvergessen** [comment] 2018-02-07 09:34
yeah which is "making it more prominent that a call is happening" 😉

**Closed by nickvergessen** 2018-02-07 09:34 UTC
Labels: feature: video call webrtc

**Comment by jancborchardt** [comment] 2018-06-21 07:50
Another concrete proposal is at
→#976 If the room does not have an active call yet, button should say "Start call" 

(Then the button would be "Start call" normally, and "Join call" when a call is active.)
