### ISSUE TITLE
Need for a default notification of the likely need to configure a TURN server.

### ISSUE THREAD

**Issue by Upperholme** [nextcloud/spreed#655] opened 2018-02-13 13:37 UTC
## Steps to reproduce
1. Enable the app in your Nextcloud instance
2. Click on the camera icon to launch the app and try to initiatie a call to another user.
3. Notice that it doesn't work. Other users report that they can launch the app but no apparent ability to connect into an existing call or make a successful connection. It appears - see #586  - that the default install will only work where users don't have firewalls in place. My assumption is that the vast majority of users will have a firewall turned on by default, and many won't actually be aware of whether it is or not (or even what a firewall is :-)).

### Expected behaviour
Wen the app is first installed an on-screen alert should inform the user that the app may need configuring if one or more users is likely to be behind a firewall. This could helpfully include a link to some documentation setting out further details as to how and why configuration of a TURN server may be needed, given that most people are not familiar with the details of how WebRTC works.

### Actual behaviour
What actually happens is that the app is installed and enabled with zero notification of any possible issues, and no links to any helpful documentation. So it just appears to be broken, with no clue as to why that may be the case.

**Comment by brylie** [comment] 2018-02-28 17:38
Yep, it seems likely that a TURN server configuration will be necessary for most/all Nextcloud deployments, since firewalls are so common among end users.

**Comment by BloodyIron** [comment] 2018-03-30 20:54
I really also want the NC documentation to talk about the Talk STUN/TURN/etc stuff. I'm very surprised NC12 or 13 docs say NOTHING about this. I've found other facets of the documentation to be far more fleshed out, but in regards to the Talk facet, it's like nothing exists at all.

Should I open a new issue for that, or is it okay to have that bundled into this one?

**Comment by tobiasKaminsky** [comment] 2018-04-04 05:34
I tried it yesterday and it was not working either, it says "waiting for participants" or it was showing the other user, but with an endless spinning circle.
The server is located at strato, while both user have Unitymedia (Cable provider) and use a FritzBox to connect their laptops via wlan.

I also would like to have 
- additional infos about STUN/TURN
- a warning once a connection is not working with a more detailed info

(@nickvergessen talk on our company server was working fine)

**Comment by brylie** [comment] 2018-04-04 05:50
@tobiasKaminsky, were you able to configure a TURN server?

**Comment by Upperholme** [comment] 2018-04-04 08:08
One that is worth checking, if oyu have a TURN server set up but are still unable to make calls successfully, is that the reference to the TURN server in your Nextcloud settings should not include any protocol prefix. The placeholder in the settings screen is presented with the format "https://turn.server.address:port" but this won't work. It needs to be just "turn.server.address:port"

I did come across an issue about this, but can't find it just now.

**Comment by mario** [comment] 2018-05-16 05:43
I doubt we'll ever ship a TURN server, so no worries there :)

**Comment by pkostelnik** [comment] 2019-10-09 10:18
Still need to clarify, how to "simple" setup a TURN/STUN Server for Nextcloud/Talk (Spreed)

**Comment by jospoortvliet** [comment] 2020-03-26 13:46
Like we warn on large nrs of users in a call without a the back-end, we could warn when it is impossible to connect that there is possibly a need for a TURN server. That would be a good solution to this issue I'd say.

**Comment by nickvergessen** [comment] 2020-03-26 13:52
Duplicate of #915 which I just fixed via #3160 this morning, so closing

**Closed by nickvergessen** 2020-03-26 13:52 UTC
Labels: enhancement, feature: settings ⚙️
