### ISSUE TITLE
grouping / nesting / categorizing chats

### ISSUE THREAD

**Issue by Rik44444** [nextcloud/spreed#9859] opened 2023-06-26 08:50 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
People use apps like Slack and Teams not only for chat but also as a knowledge repository. For this function, + to make reviewing changes more feasible when there are lots of comments, we would like to request: grouping/nesting/categorizing chats. Similar to https://zulip.com/. 

**Describe the solution you'd like**
we would like to request: grouping/nesting/categorizing chats. Similar to https://zulip.com/. 

**Describe alternatives you've considered**
moving to Zulip for chat 

**Additional context**
When there are lots of chats, it is really difficult to keep the oversight. We would like to:
A)  categorize chats into Sales, IT, Comms, etc
B) within those categories have specific threads for specific topics that are easy to order / filter / ignore / actively follow

**Comment by nickvergessen** [comment] 2023-06-26 10:08
Duplicate of #2448

**Closed by nickvergessen** 2023-06-26 10:08 UTC
Labels: 0. Needs triage, enhancement
