### ISSUE TITLE
Implement message drafts

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#6926] opened 2022-02-21 14:02 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Sometimes we loose a message because we navigate away or accidentally close the window. 

**Describe the solution you'd like**
We should save messages drafts

---

**Telegram example**

I start writing a message on my laptop

https://user-images.githubusercontent.com/26852655/154968657-8b6062e2-cf42-42c1-825e-c13afd4aeedf.mov

... And I pick it up on the phone a moment after 

https://user-images.githubusercontent.com/26852655/154969665-4c62b75b-7065-4e35-857c-897cec5b8f28.MP4

**Comment by nickvergessen** [comment] 2022-02-22 15:15
Duplicate of #6258 and #3055

**Closed by nickvergessen** 2022-02-22 15:15 UTC
Labels: 0. Needs triage, enhancement
