### ISSUE TITLE
Sound sharing while screensharing

### ISSUE THREAD

**Issue by Samsa777** [nextcloud/spreed#4175] opened 2020-09-17 18:30 UTC
**Is your feature request related to a problem? Please describe.**
It would be great if it would be possible to share the computer sound (for example the sharing of a videoplayer) during screen sharing

**Describe the solution you'd like**

* Share screen or window
* Activate option to also share sounds

**Describe alternatives you've considered**
/

**Additional context**
Discord has a similar option. There you can share your sound while sharing a single application window

**Comment by nickvergessen** [comment] 2020-09-17 19:04
This will not work until we also have a desktop client, because (luckily) websites in your browser can not do that.

**Comment by Samsa777** [comment] 2020-09-18 14:53
Oh, I didn´t know that.

Thanks

**Comment by nickvergessen** [comment] 2020-09-29 11:22
Duplicate of #3546

**Closed by nickvergessen** 2020-09-29 11:22 UTC
Labels: 1. to develop, enhancement, feature: call 👥
