### ISSUE TITLE
later added group members not applied to Talk conversation

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#2855] opened 2020-01-28 08:36 UTC
## Steps to reproduce
1. Users A and User B are members of the group "TestGroup"
2. User A creates a conversation in Talk with "TestGroup" > A conversation "TestGroup" gets created, Users A and B are members of the conversation
3. User C becomes member of user group "TestGroup"

### Expected behaviour
User C gets added to the conversation "TestGroup"

### Actual behaviour
The user list remains unchanged

NC 18.0.0
Circles 0.18.0
Talk 8.0.1

**Comment by wiswedel** [comment] 2020-01-28 08:36
rel #2854

**Comment by nickvergessen** [comment] 2020-01-28 09:07
Duplicate of https://github.com/nextcloud/spreed/issues/1329

**Closed by nickvergessen** 2020-01-28 09:07 UTC
Labels: 0. Needs triage, bug
