### ISSUE TITLE
Talk integration breaks sharing layout

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8036] opened 2022-09-29 07:45 UTC
Before | After
---|---
![Bildschirmfoto vom 2022-09-29 09-41-49](https://user-images.githubusercontent.com/213943/192971076-dbb735ce-5cde-4f1a-b11b-1ee4ea070a30.png) | ![Bildschirmfoto vom 2022-09-29 09-42-20](https://user-images.githubusercontent.com/213943/192971139-b9a751db-e3c8-4c7e-8d2d-44e4c416c6b5.png)

Seems like #7865 was not enough

**Comment by danxuliu** [comment] 2022-09-29 16:46
This is a regression introduced in https://github.com/nextcloud/server/pull/34028/commits/10ad6e17f79095ea2f0e91013046b6d82f0c8038#diff-72acc517d2cdb9c8da122c48e517a84831b04e0596ac38dc6b13add3d18dcb55R74 due to substracting the footer height from the height of the app content (and Talk moving the footer inside the app content). It is fixed by the [follow up pull request](https://github.com/nextcloud/server/pull/34331).

**Closed by danxuliu** 2022-09-29 16:46 UTC
Labels: 1. to develop, bug, high, regression
