### ISSUE TITLE
Don't follow self when ending screenshare

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#4863] opened 2020-12-29 13:56 UTC
## Steps to reproduce
1. Do a screenshare in a call
2. End the screenshare

### Expected behaviour
The same view that was active before the screenshare is restored

### Actual behaviour
You see yourself

**Comment by PVince81** [comment] 2021-01-14 07:54
Could not reproduce on Chromium Version 87.0.4280.88 (openSUSE Build) (64-bit), neither when starting screen share in promoted view nor in grid view.

Stopping the screen share brings back the old view.
I even tried clicking on my screen share video to follow it (which shouldn't do anything).

Tested on talk master 83c75400edb149c3c3e594647dbb5ab43f68664f

@ma12-co Not sure what dev env you use and whether you are reusing old test channels, maybe try clearing the local storage just in case ?

If still reproducible, please provide more details, maybe even a video.

**Comment by nickvergessen** [comment] 2021-01-14 08:14
I think this was fixed by the PR that brings you back to the grid view after a screenshare.

**Closed by nickvergessen** 2021-01-14 08:14 UTC
Labels: 1. to develop, bug, feature: call 👥, needs info
