### ISSUE TITLE
Upgrade from Nextcloud 20.0.8 to Nextcloud 21

### ISSUE THREAD

**Issue by kittkott** [nextcloud/spreed#5304] opened 2021-03-03 23:51 UTC
## Steps to reproduce
Upgrade from Nextcloud 20.0.8 to Nextcloud 21

### Expected behavior
I expect all chat in all users will not leave us.

### Actual behavior
All chat was deleted, the new chat is created in a normal way. 

## Talk app
Talk app version: 10.0.6
Custom Signaling server configured: no
Custom TURN server configured: no
Custom STUN server configured: no

Operating system: CentOS 8.3.2011
Web server: Apache 2.4.37
Database: Maria 10.3.27
PHP version: 7.4.15-1.el8.remi
Nextcloud Version: 21

List of activated apps:

Enabled:
- accessibility: 1.6.0
- activity: 2.13.4
- admin_audit: 1.10.0
- announcementcenter: 4.0.1
- apporder: 0.12.0
- bruteforcesettings: 2.0.1
- calendar: 2.1.3
- circles: 0.20.7
- cloud_federation_api: 1.3.0
- comments: 1.10.0
- contacts: 3.4.3
- contactsinteraction: 1.1.0
- dashboard: 7.0.0
- dav: 1.16.2
- deck: 1.2.4
- encryption: 2.8.1
- extract: 1.3.1
- federatedfilesharing: 1.10.2
- federation: 1.10.1
- files: 1.15.0
- files_accesscontrol: 1.10.2
- files_antivirus: 3.1.2
- files_pdfviewer: 2.0.1
- files_rightclick: 0.17.0
- files_sharing: 1.12.2
- files_trashbin: 1.10.1
- files_versions: 1.13.0
- files_videoplayer: 1.9.0
- firstrunwizard: 2.9.0
- forms: 2.1.0
- groupfolders: 8.2.0
- groupquota: 0.1.5
- logreader: 2.5.0
- lookup_server_connector: 1.8.0
- nextcloud_announcements: 1.9.0
- notes: 4.0.3
- notifications: 2.8.0
- oauth2: 1.8.0
- password_policy: 1.10.1
- photos: 1.2.3
- privacy: 1.4.0
- provisioning_api: 1.10.0
- quota_warning: 1.9.1
- rainloop: 7.0.3
- ransomware_protection: 1.8.0
- recommendations: 0.8.0
- serverinfo: 1.10.0
- settings: 1.2.0
- spreed: 10.0.6
- support: 1.3.0
- survey_client: 1.8.0
- systemtags: 1.10.0
- tasks: 0.13.6
- text: 3.1.0
- theming: 1.11.0
- twofactor_backupcodes: 1.9.0
- updatenotification: 1.10.0
- user_saml: 3.3.4
- user_status: 1.0.1
- viewer: 1.4.0
- weather_status: 1.0.0
- workflow_ocr: 1.20.2
- workflowengine: 2.2.0
Disabled:
- files_external
- onlyoffice
- sharebymail
- sharepermissions
- user_ldap

Nextcloud configuration:
{
"system": {
"dbtype": "mysql",
"version": "20.0.8.1",
"dbport": "",
"dbtableprefix": "oc_",
"mysql.utf8mb4": true,
"installed": true,
"maintenance": false,
"mail_smtpmode": "smtp",
"mail_smtpsecure": "ssl",
"mail_sendmailmode": "smtp",
"mail_smtpport": "465",
"app.mail.verify-tls-peer": false,
"loglevel": 1,
"filelocking.enabled": true,
"memcache.local": "\\OC\\Memcache\\Redis",
"memcache.locking": "\\OC\\Memcache\\Redis",
"memcache.distributed": "\\OC\\Memcache\\Redis",
"redis": {
"host": "***REMOVED SENSITIVE VALUE***",
"port": 0,
"timeout": 0,
},
"encryption.legacy_format_support": false,
"preview_libreoffice_path": " \/usr\/bin\/libreoffice",
"default_language": "ru_RU",
"default_locale": "ru_RU",
"force_locale": "ru_RU",
"force_language": "ru_RU"
}
}

**Comment by nickvergessen** [comment] 2021-03-04 06:13
Duplicate of #5281

**Closed by nickvergessen** 2021-03-04 06:13 UTC
Labels: 0. Needs triage, bug
