### ISSUE TITLE
Federated call ends after some time without a local participant

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/spreed#12917] opened 2024-08-07 14:37 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce

1. Start a call in a federated conversation
2. Wait until everyone has joined

### Actual behaviour

Federated call silently ends after some time. Looks like 30sec after the last person joined the call

- Call timer stops after some time ()
- Some people receive a "You've missed a call" notification during the call.
- "Join call" is replaced with "Start call", `callStartTime: 0`, `hasCall: false`

## Talk app

**Talk app version:** 20.0.0-beta.3 on c.nc.c

**Comment by danxuliu** [comment] 2024-08-13 06:36
The problem is that the ping is not updated for participants in the federated conversation* by the signaling server. Moreover, note that it would not be enough to make the signaling server ping the federated conversation for the federated users, as then the remote participants would still not have a ping, and the code would still misbehave (for example, to know if there are other participants in the call).

*Note that the ping is set when [joining the federated conversation](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1607), although not when [the participant joins the host conversation](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1652-L1685). However, it is nevertheless set when [the signaling server joins the host conversation](https://github.com/nextcloud/spreed/blob/cc648fd2ebcc26b604bc7e235694dd6aac57c232/lib/Controller/SignalingController.php#L818), and from that moment on the signaling server will update the host conversation, although not the federated conversation.

On a quick test I have not been able to reproduce the notification about the ended call, though; it would be worth finding the right steps to reproduce it.

Below are all the usages (unless I missed something :shrug:) of the last ping. @nickvergessen Ideas? :-)

Uses of `last_ping`:
- Commands/Monitor commands, to get the number of active participants; results will be wrong anyway in federated conversations, as it will not take into account the remote participants. Maybe ignore federated conversations, or print a warning?
- `Service/ParticipantService`:
  - cleanGuestParticipants
  - getParticipantsForAllSessions, if `maxAge` is provided
  - getParticipantsInCall, if `maxAge` is provided
  - getParticipantUserIdsForCallNotifications
  - hasActiveSessionsInCall
  - getParticipantWithActiveSession

Uses of `*LastPing`:
  - `Chat/Notifier::`[`shouldParticipantBeNotified`](https://github.com/nextcloud/spreed/blob/99707fa31aeb43006a6e8d280ad79b1727670f80/lib/Chat/Notifier.php#L659), to know if a user is active in the conversation, so the notification should be skipped
  - `Controller/CallController::getPeersForCall`, not relevant, as it is currently not available for federated conversations, and once it is it will just be proxied from the host.
  - `Controller/ChatController::`[`receiveMessages`](https://github.com/nextcloud/spreed/blob/d6cc077d42cef4e47996be3a3849ca3f3a139068/lib/Controller/ChatController.php#L445), to update the last ping when receiving messages in mobile apps, as they do not connect to the signaling unless in a call (which may not be true any longer either)
  - `Controller/RoomController::`[`formatParticipantList`](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L946-L954) to clean user and guest sessions, [clean inactive users](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L997-L999), [clean guests](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1025-L1033), and return the last ping in the formatted participant data
  - `Controller/RoomController::`[`joinRoom`](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1558), for conflicts when joining a room again and to [initially set the ping when joining the room](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1607)
  - `Controller/SignalingController::`[`backendRoom`](https://github.com/nextcloud/spreed/blob/cc648fd2ebcc26b604bc7e235694dd6aac57c232/lib/Controller/SignalingController.php#L818) to update the ping when the signaling server joins the host room and when [it updates the ping in the host room](https://github.com/nextcloud/spreed/blob/cc648fd2ebcc26b604bc7e235694dd6aac57c232/lib/Controller/SignalingController.php#L886); internal signaling server also updates the ping when pulling messages, although that is not currently relevant.
  - `Service/RoomFormatter::`[`formatRoomV4`](https://github.com/nextcloud/spreed/blob/6c5f9a9991434cc440e118fe8144d23e6fdce5cb/lib/Service/RoomFormatter.php#L254), used to format room data in controller responses
    - In the WebUI it is in turn used to [either force join a conversation or ask if force join in case of conflict](https://github.com/nextcloud/spreed/blob/3a3e4a4e93401bfa815d0be649b078d96754f524/src/store/participantsStore.js#L891-L896)
  - `Signaling/BackendNotifier`, not relevant, as it is used to provide the lastPing in the participants->update signaling messages, but this should have no effect in federated conversations, as when the clients join the room in the signaling server the signaling server in turn joins the room in the host Nextcloud server. Therefore, even if the federated Nextcloud server will notify the federated signaling server when the participants change [the signaling server will not notify](https://github.com/strukturag/nextcloud-spreed-signaling/blob/86721347f9af23fa36602ee2504447b741f6dcb9/room.go#L683-L697) any [client](https://github.com/strukturag/nextcloud-spreed-signaling/blob/a256789f20d4fbfc9f06bd09b404b0908b94c7cd/clientsession.go#L690), as none of them will be in the federated room from the point of view of the signaling server and, therefore, [they will not be listening for room events](https://github.com/strukturag/nextcloud-spreed-signaling/blob/a256789f20d4fbfc9f06bd09b404b0908b94c7cd/clientsession.go#L462-L479).

Uses of ParticipantService::cleanGuestParticipants
  - `RoomController::formatParticipantList`, not relevant, as guests are not allowed in federated conversations (they are on the host conversation, but not on the federated conversation itself)

Uses of ParticipantService::getParticipantsForAllSessions (with maxAge)
  - `SignalingController:getUsersInRoom`, not relevant, as it is used to get the active users in internal signaling messages; although currently federated calls are not implemented with internal signaling once/if it is implemented this should not be a problem, as either the signaling messages are relayed from the host, so this would not be used, or the signaling messages are got from the federated server, which would [implicitly set the ping](https://github.com/nextcloud/spreed/blob/cc648fd2ebcc26b604bc7e235694dd6aac57c232/lib/Controller/SignalingController.php#L424).

Uses of ParticipantService::getParticipantsInCall (with maxAge)
  - `CallController::getPeersForCall`, not relevant, as it is currently not available for federated conversations, and once it is it will just be proxied from the host.

Uses of [ParticipantService::getParticipantUserIdsForCallNotifications](https://github.com/nextcloud/spreed/blob/7ff8b5865cc4aec7001796d3c83dfa3a81a7b711/lib/Service/ParticipantService.php#L1704)
  - `Notifier/Listener::`[`sendCallNotifications`](https://github.com/nextcloud/spreed/blob/2a38a527d24b26a1c6bbcfc7a752061d54ab7276/lib/Notification/Listener.php#L277), to filter out participants currently in the call

Uses of [ParticipantService::hasActiveSessionsInCall](https://github.com/nextcloud/spreed/blob/7ff8b5865cc4aec7001796d3c83dfa3a81a7b711/lib/Service/ParticipantService.php#L1843)
  - `Chat/SystemMessage/Listener::sendSystemMessageAboutBeginOfCall`, not relevant, as system messages are not sent in federated conversations
  - `Controller/CallController::leaveCall` and `::leaveFederatedCall`, not relevant, as leaveFederatedCall is not called in federated conversations, and leaveCall returns before checking active sessions in federated conversations
  - `Listener/RestrictStartingCalls`, not relevant, as it is used to prevent starting a call if the participant does not have permissions and there is no ongoing call based on whether there are active participants in a call or not, but the host server will prevent anyway the federated user to start the call in that case.
  - `Notification/Notifier::`[`parseInvitation`](https://github.com/nextcloud/spreed/blob/099db18c8e6954ec593950d707602cf2d454e969/lib/Notification/Notifier.php#L929-L933), to show `Join call` or `View chat` in the notification, depending on whether there is an active call or not, when invited to a 1-1 conversation
  - `Service/ParticipantService::`[`resetCallStateWhenNeeded`](https://github.com/nextcloud/spreed/blob/7ff8b5865cc4aec7001796d3c83dfa3a81a7b711/lib/Service/ParticipantService.php#L1830), to reset call state when removing a participant, attendee... and there are no other participants in the call

Uses of ParticipantService::getParticipantWithActiveSession
  - `Federation/CloudFederationProviderTalk::messagePosted`, not relevant, as it is used to know if the user accepted the invite already or not, so the active session is not relevant, only [if there is an attendee](https://github.com/nextcloud/spreed/blob/7ff8b5865cc4aec7001796d3c83dfa3a81a7b711/lib/Service/ParticipantService.php#L1938)

**Comment by nickvergessen** [comment] 2024-08-13 06:41
> Note that the ping is set when [joining the federated conversation](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1607), although not when [the participant joins the host conversation](https://github.com/nextcloud/spreed/blob/36871453829632d08f3287a8ccf33ad9d80007f3/lib/Controller/RoomController.php#L1652-L1685).

Just for the record, the main difference here is that in case 1 we return the room object on the response. We do not do that on the federated join, so there is no direct need, but we should do it, to avoid the session being purged right away if timing happens to be exact

**Comment by nickvergessen** [comment] 2024-08-14 06:00
As per chat:
1. I think we should ask the HPB to ping both the Host Server and the Fed Server. The Host Server needs the info to track the general call state. The Fed Server needs the info to deal with notifications. *Currently this is Host Server only*
2. Some places (parse invitation, etc) should be changed to be based on the rooms in_call flag instead.

**Comment by nickvergessen** [comment] 2024-08-27 07:08
This still reproduces and is the most critical thing atm I would say:
![grafik](https://github.com/user-attachments/assets/121336c7-8982-4783-a759-6a28f2718378)

Especially confusing is that the people are still "in the call", but people joining later can not connect to them.

**Comment by nickvergessen** [comment] 2024-08-27 09:14
> Currently this is Host Server only

This is "Fed Server" only atm. Not sure if my initial notes where wrong, or if that is because I use the same HPB for both servers

**Comment by fancycode** [comment] 2024-08-27 14:10
> This is "Fed Server" only atm. Not sure if my initial notes where wrong, or if that is because I use the same HPB for both servers

I can reproduce that the pings are only sent on the Fed server (i.e. the server where the meeting is taking place) and only by the target signaling server associated with that NC instance.

This is expected as the signaling server sends the pings from the room the sessions are connected to - which is the target / fed server.

**Comment by nickvergessen** [comment] 2024-08-27 14:59
Chatted a bit with Jojo and at least with the latest code base the call is no longer terminating.
However sessions last_ping is only updated on the Host Server for all participants, so the Fed Server can no longer distinguish active/passive sessions for notification handling

**Comment by fancycode** [comment] 2024-08-29 08:20
Should be fixed with https://github.com/strukturag/nextcloud-spreed-signaling/pull/808

**Closed** 2024-08-29 14:04 UTC
Labels: 1. to develop, bug, feature: api 🛠️, feature: signaling 📶, feature: call 📹, feature: federation 🌐
