### ISSUE TITLE
Talk Web GUI unusable with signaling server 0.4.0

### ISSUE THREAD

**Issue by aviatorhh** [nextcloud/spreed#6726] opened 2021-12-20 05:48 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---
### Steps to reproduce
1. Upgrade to NC 23
2. Upgrade and update to Talk 13.0.1
3. Updating Signaling Server to 0.4.0

### Expected behaviour
The web GUI of Talk should work as expected. The message of saying that we need to update the signaling server (after installing NC 23) should go away and everything should be fine.

### Actual behaviour
The upgrade message disappears but the web GUI is not usable. We cannot enter any text or send messages. The input field is disabled. A message pops up saying that we cannot enter a conversation and we need to reload the web page. When done, no change. Messaging using the iOS App works normally.

## Server configuration detail

**Operating system:** Linux 5.10.0-0.bpo.9-amd64 #1 SMP Debian 5.10.70-1~bpo10+1 (2021-10-10) x86_64

**Webserver:** Apache/2.4.51 (Debian) (fpm-fcgi)

**Database:** mysql 10.6.4

**PHP version:** 

8.0.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, ldap, exif, mcrypt, msgpack, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 23.0.0 - 23.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from previous version

**Where did you install Nextcloud from:** NC website

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - bruteforcesettings: 2.3.0
 - calendar: 3.0.2
 - circles: 23.0.0
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contacts: 4.0.7
 - contactsinteraction: 1.4.0
 - dashboard: 7.3.0
 - dav: 1.21.0
 - drawio: 1.0.2
 - external: 3.10.2
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_external: 1.15.0
 - files_fulltextsearch: 23.0.0
 - files_fulltextsearch_tesseract: 22.0.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - fulltextsearch: 23.0.0
 - fulltextsearch_elasticsearch: 23.0.0
 - groupfolders: 11.1.0
 - issuetemplate: 0.7.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - password_policy: 1.13.0
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - spreed: 13.0.1
 - support: 1.6.0
 - systemtags: 1.13.0
 - text: 3.4.0
 - theming: 1.14.0
 - theming_customcss: 1.10.0
 - twofactor_backupcodes: 1.12.0
 - updatenotification: 1.13.0
 - user_ldap: 1.13.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - workflowengine: 2.5.0
Disabled:
 - encryption
 - firstrunwizard
 - ldap_contacts_backend
 - ldap_write_support
 - ldapcontacts
 - survey_client

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "admin.njk.aero",
        "cloud.njk.aero",
        "cloud.northwings.aero"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.northwings.aero",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "23.0.0.10",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "default_phone_region": "DE",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "overwriteprotocol": "https",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "loglevel": 0,
    "updater.release.channel": "stable",
    "theme": "",
    "auth.bruteforce.protection.enabled": false,
    "app_install_overwrite": [
        "calendar",
        "bookmarks_fulltextsearch",
        "files_fulltextsearch_tesseract",
        "spreed",
        "fulltextsearch",
        "external",
        "issuetemplate"
    ],
    "mysql.utf8mb4": true,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 0background_sync_prefix: s01cleanUpJobOffset: 0enabled: yesinstalled_version: 1.13.0s01_lastChange: 1639978647s01has_memberof_filter_support: 1s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: bWFoYWthbGE=s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: dc=northwings,dc=aeros01ldap_base_groups: ou=nextcloud,ou=apps,dc=northwings,dc=aeros01ldap_base_users: ou=people,dc=northwings,dc=aeros01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: cn=admin,dc=northwings,dc=aeros01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 1s01ldap_expert_username_attr: uids01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=groupOfNames))(|(cn=user)(cn=shareholder)(cn=gmp)(cn=camo)(cn=pilots)))s01ldap_group_filter_mode: 1s01ldap_group_member_assoc_attribute: members01ldap_groupfilter_groups: user
users01ldap_groupfilter_objectclass: groupOfNamess01ldap_host: ldap://172.20.3.5s01ldap_login_filter: (&(objectclass=person)(|(uid=%uid)(mail=%uid)))s01ldap_login_filter_mode: 1s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 0s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: users01ldap_userfilter_objectclass: s01ldap_userlist_filter: (&(objectclass=person)(|(memberof=cn=user,ou=nextcloud,ou=apps,dc=northwings,dc=aero)(memberof=cn=shareholder,ou=nextcloud,ou=apps,dc=northwings,dc=aero)(memberof=cn=gmp,ou=nextcloud,ou=apps,dc=northwings,dc=aero)(memberof=cn=camo,ou=nextcloud,ou=apps,dc=northwings,dc=aero)(memberof=cn=pilots,ou=nextcloud,ou=apps,dc=northwings,dc=aero)))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Operating system:** macOS Monterey 12.0.1

## Logs

<details><summary>Signaling server error log</summary>

```
Dec 19 18:14:56 server3 signaling[31395]: hub.go:809: Invalid message {Id: Type: Hello:<nil> Bye:<nil> Room:<nil> Message:<nil> Control:<nil> Internal:<nil>} from 31.17.252.49: type missing
Dec 19 18:14:56 server3 signaling[31395]: client.go:282: Client from 31.17.252.49 has RTT of 67 ms (67.212893ms)
Dec 19 18:14:58 server3 signaling[31395]: client.go:303: Error reading from 31.17.252.49: read tcp 172.20.2.1:8080->172.20.2.10:53230: use of closed network connection

```
</details>

<details><summary>Nextcloud log</summary>

```
no errors
```
</details>

<details><summary>Browser log</summary>

index.js:46 No OC found
Nr @ index.js:46
value @ gettext.js:45
(anonymous) @ l10n.js:3
(anonymous) @ main.js?v=1cacd142-29:160
n @ bootstrap:19
(anonymous) @ main.js?v=1cacd142-29:27
n @ bootstrap:19
(anonymous) @ main.js:1
(anonymous) @ main.js?v=1cacd142-29:891
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js?v=1cacd142-29:1
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
(anonymous) @ index.es.js:3314
(anonymous) @ main.js?v=1cacd142-29:285
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ main.js?v=1cacd142-29:776
n @ bootstrap:19
(anonymous) @ main.js?v=1cacd142-29:1336
n @ bootstrap:19
(anonymous) @ main.js:1
(anonymous) @ main.js?v=1cacd142-29:891
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js?v=1cacd142-29:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
(anonymous) @ jquery.js:10336
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
784 @ files_client.js?v=1cacd142-29:64
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=1cacd142-29:1
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
(anonymous) @ jquery.js:10339
(anonymous) @ jquery.js:28
0 @ jquery.js:14
n @ bootstrap:19
784 @ files_client.js?v=1cacd142-29:64
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ files_client.js?v=1cacd142-29:1
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
903 @ index.es.js:3314
o @ bootstrap:19
1894 @ requesttoken.js:11
o @ bootstrap:19
2200 @ index.js:25
o @ bootstrap:19
4820 @ index.js:12
o @ bootstrap:19
(anonymous) @ viewer-main.js?v=1cacd142-29:2
(anonymous) @ viewer-main.js?v=1cacd142-29:2
(anonymous) @ viewer-main.js?v=1cacd142-29:2
Viewer.js:49 OCA.Viewer initialized
Viewer.vue:338 No OCA.Files app found, viewer is now in standalone mode
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
(anonymous) @ script.js?v=1cacd142-29:492
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
(anonymous) @ files.js?v=1cacd142-29:122
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
t @ index.es.js:2337
70903 @ index.es.js:3314
a @ bootstrap:19
71894 @ requesttoken.js:11
a @ bootstrap:19
22200 @ index.js:25
a @ bootstrap:19
4820 @ index.js:12
a @ bootstrap:19
(anonymous) @ notifications-main.js?v=1cacd142-29:2
(anonymous) @ notifications-main.js?v=1cacd142-29:2
(anonymous) @ notifications-main.js?v=1cacd142-29:2
App.vue:138 Loading theming data for notification bell styling
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
mounted @ App.vue:143
qt @ vue.runtime.esm.js:1863
ln @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
L @ vue.runtime.esm.js:6390
ya.nodeOps @ vue.runtime.esm.js:6609
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
En.$mount @ vue.runtime.esm.js:8459
t._init @ vue.runtime.esm.js:5032
En @ vue.runtime.esm.js:5099
(anonymous) @ main.js:32
(anonymous) @ notifications-main.js?v=1cacd142-29:2
(anonymous) @ notifications-main.js?v=1cacd142-29:2
App.vue:148 Registering notifications container as a menu
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
mounted @ App.vue:149
qt @ vue.runtime.esm.js:1863
ln @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
L @ vue.runtime.esm.js:6390
ya.nodeOps @ vue.runtime.esm.js:6609
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
En.$mount @ vue.runtime.esm.js:8459
t._init @ vue.runtime.esm.js:5032
En @ vue.runtime.esm.js:5099
(anonymous) @ main.js:32
(anonymous) @ notifications-main.js?v=1cacd142-29:2
(anonymous) @ notifications-main.js?v=1cacd142-29:2
globals.js:62 $ is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
mounted @ App.vue:149
qt @ vue.runtime.esm.js:1863
ln @ vue.runtime.esm.js:4235
insert @ vue.runtime.esm.js:3158
L @ vue.runtime.esm.js:6390
ya.nodeOps @ vue.runtime.esm.js:6609
t._update @ vue.runtime.esm.js:3960
r @ vue.runtime.esm.js:4081
bn.get @ vue.runtime.esm.js:4495
bn @ vue.runtime.esm.js:4484
t @ vue.runtime.esm.js:4088
En.$mount @ vue.runtime.esm.js:8459
t._init @ vue.runtime.esm.js:5032
En @ vue.runtime.esm.js:5099
(anonymous) @ main.js:32
(anonymous) @ notifications-main.js?v=1cacd142-29:2
(anonymous) @ notifications-main.js?v=1cacd142-29:2
App.vue:366 Notifications permissions granted
App.vue:326 Polling interval updated to 30000
App.vue:204 Started background fetcher as session_keepalive is enabled
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
(anonymous) @ index.es.js:3314
(anonymous) @ user-status-menu.js?v=1cacd142-29:216
r @ bootstrap:63
(anonymous) @ requesttoken.js:11
r @ bootstrap:63
(anonymous) @ index.js:25
r @ bootstrap:63
(anonymous) @ user-status-menu.js?v=1cacd142-29:266
r @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ user-status-menu.js?v=1cacd142-29:1
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
t @ index.es.js:2337
70903 @ index.es.js:3314
i @ bootstrap:19
71894 @ requesttoken.js:11
i @ bootstrap:19
22200 @ index.js:25
i @ bootstrap:19
4820 @ index.js:12
i @ bootstrap:19
36726 @ talk-main.js?v=1cacd142-29:1
i @ bootstrap:19
(anonymous) @ talk-main.js?v=1cacd142-29:1
(anonymous) @ talk-main.js?v=1cacd142-29:1
(anonymous) @ talk-main.js?v=1cacd142-29:1
globals.js:62 jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.
ge @ globals.js:62
get @ globals.js:93
(anonymous) @ ua-parser.js:858
42238 @ ua-parser.js:11
i @ bootstrap:19
29823 @ talk-main.js?v=1cacd142-29:1
i @ bootstrap:19
66294 @ localmedia.js:10
i @ bootstrap:19
52160 @ webrtc.js:6
i @ bootstrap:19
3454 @ simplewebrtc.js:3
i @ bootstrap:19
97456 @ talk-main.js?v=1cacd142-29:1
i @ bootstrap:19
91778 @ talk-main.js?v=1cacd142-29:1
i @ bootstrap:19
(anonymous) @ talk-main.js?v=1cacd142-29:1
(anonymous) @ talk-main.js?v=1cacd142-29:1
(anonymous) @ talk-main.js?v=1cacd142-29:1
talk-main.js?v=1cacd142-29:1 Proxying an event bus of version 2.1.1 with 1.3.0
t @ talk-main.js?v=1cacd142-29:1
17331 @ talk-main.js?v=1cacd142-29:1
i @ bootstrap:19
(anonymous) @ Avatar.js:24
n @ Avatar.js:1
(anonymous) @ Avatar.js:151
n @ Avatar.js:1
(anonymous) @ Avatar.js:1
83507 @ Avatar.js:1
i @ bootstrap:19
(anonymous) @ talk-main.js?v=1cacd142-29:1
(anonymous) @ talk-main.js?v=1cacd142-29:1
(anonymous) @ talk-main.js?v=1cacd142-29:1
App.vue:355 Setting current user
browserCheck.js:29 Detected browser Chrome 96 (96.0.4664.110)
index.es.js:2337 Proxying an event bus of version 2.1.1 with 1.3.0
e @ index.es.js:2337
(anonymous) @ index.es.js:3314
(anonymous) @ unified-search.js?v=1cacd142-29:7
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ LoggerBuilder.js:8
n @ bootstrap:19
(anonymous) @ index.js:11
n @ bootstrap:19
(anonymous) @ unified-search.js?v=1cacd142-29:265
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ unified-search.js?v=1cacd142-29:1
session-heartbeat.js:101 session heartbeat polling started
Viewer.vue:264 Please do NOT wait for the DOMContentLoaded before registering your viewer handler
handlers @ Viewer.vue:264
We @ vue.runtime.esm.js:1863
bn.run @ vue.runtime.esm.js:4584
yn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
et @ vue.runtime.esm.js:1915
Promise.then (async)
Xe @ vue.runtime.esm.js:1942
it @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
bn.update @ vue.runtime.esm.js:4560
de.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
value @ Viewer.js:69
(anonymous) @ main.js:26
gapmhk5a:1 [DOM] Password forms should have (optionally hidden) username fields for accessibility: (More info: https://goo.gl/9p2vKq) <form id=​"sudo-login-form" class=​"hidden" method=​"POST">​…​</form>​
[Violation] Forced reflow while executing JavaScript took 135ms
App.vue:289 Got notification data
App.vue:326 Polling interval updated to 30000
ConsoleLogger.js:29 [DEBUG] unified-search: Unified Search initialized with the following providers {0: {…}, 1: {…}, 2: {…}, 3: {…}, 4: {…}, 5: {…}, 6: {…}, 7: {…}, 8: {…}, 9: {…}, 10: {…}, 11: {…}, app: 'unified-search', uid: 'a2dc3df8-e9bd-1034-98b5-69bb9cf28e28'}
signaling.js:626 Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a
signaling.js:1017 Not connected to signaling server yet, defer joining room gapmhk5a
talkHashStore.js:78 X-Nextcloud-Talk-Hash initialised:  76e5f32ed3fc9a0474b1f577ad661efad7548f11
tflite-simd.js:9 [WASM] Loading model of size: 249792
tflite-simd.js:9 INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
printChar @ tflite-simd.js:9
Ne @ tflite-simd.js:9
$func1487 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x12aedc
$func488 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x4cee6
$func1494 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x12b823
$func557 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x51a38
$func1590 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x13c4d9
$func2132 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x1b6238
$func2219 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x1d2f22
$func1246 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x1010d6
$func1617 @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x13e23e
$B @ tflite-simd.wasm?v=2424013c64ebd6da057f:0x1ed703
c._loadModel @ tflite-simd.js:9
(anonymous) @ JitsiStreamBackgroundEffect.worker.js:61
await in (anonymous) (async)
self.onmessage @ JitsiStreamBackgroundEffect.worker.js:18
signaling.js:636 Connected Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
VM450:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
VM451:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
signaling.js:666 Close CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: '', type: 'close', …}
signaling.js:680 Reconnecting socket as the connection was closed unexpected
signaling.js:600 Reconnect in 1075.2567539628506
signaling.js:626 Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a
signaling.js:636 Connected Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
VM452:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
VM453:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
signaling.js:666 Close CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: '', type: 'close', …}
signaling.js:680 Reconnecting socket as the connection was closed unexpected
signaling.js:600 Reconnect in 1273.9533309401381
signaling.js:626 Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a
signaling.js:636 Connected Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
VM454:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
VM455:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
signaling.js:666 Close CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: '', type: 'close', …}
signaling.js:680 Reconnecting socket as the connection was closed unexpected
signaling.js:600 Reconnect in 1317.1460052646567
signaling.js:626 Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a
signaling.js:636 Connected Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
VM456:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
VM457:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
signaling.js:666 Close CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: '', type: 'close', …}
signaling.js:680 Reconnecting socket as the connection was closed unexpected
signaling.js:600 Reconnect in 1441.7245267057217
signaling.js:626 Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a
signaling.js:636 Connected Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
VM458:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
VM459:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
signaling.js:666 Close CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: '', type: 'close', …}
signaling.js:680 Reconnecting socket as the connection was closed unexpected
signaling.js:600 Reconnect in 1184.8781776800333
signaling.js:626 Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a
signaling.js:636 Connected Event {isTrusted: true, type: 'open', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
VM460:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
VM461:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at f.<anonymous> (signaling.js:687)
(anonymous) @ signaling.js:687
signaling.js:666 Close CloseEvent {isTrusted: true, wasClean: true, code: 1005, reason: '', type: 'close', …}
signaling.js:680 Reconnecting socket as the connection was closed unexpected
signaling.js:600 Reconnect in 585.7059115952217
​ Connecting to wss://signaling.njk.aero/standalone-signaling/spreed for gapmhk5a

</details>

**Comment by fancycode** [comment] 2021-12-20 08:05
Duplicate of https://github.com/strukturag/nextcloud-spreed-signaling/issues/180

**Closed by fancycode** 2021-12-20 08:05 UTC
Labels: 0. Needs triage, bug
