### ISSUE TITLE
Nextcloud talk 

### ISSUE THREAD

**Issue by kienlap** [nextcloud/spreed#6214] opened 2021-09-09 07:51 UTC
Nextcloud 22.1.1
When i turn on Nextcloud Talk Nextcloud
have a mess below
**The column 'sip_enabled' on table 'oc_talk_rooms' already exists.**

**Comment by nickvergessen** [comment] 2021-09-14 14:14
Duplicate of https://github.com/nextcloud/spreed/issues/6165

**Closed by nickvergessen** 2021-09-14 14:14 UTC
Labels: 0. Needs triage, bug
