### ISSUE TITLE
New Talk app allows users to get stuck in full-screen

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#527] opened 2017-12-14 12:28 UTC
## Steps to reproduce
1. start a call with somebody
2. go full-screen
3. other party leaves the call, ending it

### Expected behaviour
You can now exit full-screen

### Actual behaviour
You're stuck in full screen with no left or top Nextcloud bar

## Browser
Chromium

**Microphone available:** yes

**Camera available:** yes

**Operating system:** openSUSE

**Browser name:** chromium

**Browser version:** latest

## Spreed app
the one on the nextcloud.com server from beta3 ;-)
</details>

**Comment by nickvergessen** [comment] 2018-01-08 11:06
Pressing `ESC` jumps back like it should.

But yeah, maybe we should automatically do this, when either everyone else or you left the call.

PS: if you leave the call yourself, the "Exit fullscreen" button is still displayed, so it seems to be a problem with the "forced back"

**Comment by jancborchardt** [comment] 2018-01-09 23:12
Unrelatedly I was looking into displaying the #video-fullscreen already when you pressed »Join call« but are still alone.

The problem is that I only have .participants-1 to go off of, no .incall or other class by which I can actually separate if we are still in the chat (where fullscreen makes no sense really).

**Comment by nickvergessen** [comment] 2018-03-22 15:13
Fix is in https://github.com/nextcloud/spreed/pull/741

It also fixes your request @jancborchardt

**Closed** 2018-03-29 07:57 UTC
Labels: bug
