### ISSUE TITLE
possibility to see all open groups 

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6566] opened 2021-11-19 10:59 UTC
If there are open groups, it's only possible to join after searching for the name of the group. 
Maybe a overview of all open groups could be nice to not miss one interessting:

![image](https://user-images.githubusercontent.com/24530680/142611809-2b7fc253-97b0-4577-bd85-c5d11ad43e09.png)

**Comment by nickvergessen** [comment] 2021-11-19 11:08
Duplicate of #6431

**Closed by nickvergessen** 2021-11-19 11:08 UTC
Labels: 0. Needs triage, enhancement
