### ISSUE TITLE
List of open conversations

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#2784] opened 2020-01-18 10:18 UTC
Imagine a company with multiple open conversations, where new employee can join on their own to meet new colleagues, e.g. "Running during lunch break", "Pilates", etc.

So technically 
- a conversation needs to be allowed to be self-joining as an option
- have a (searchable) list of these conversations

**Comment by nickvergessen** [comment] 2020-01-18 10:31
Duplicate of #1763

**Closed** 2020-01-18 10:31 UTC
Labels: 0. Needs triage, enhancement
