### ISSUE TITLE
Conversation 3-dot-menu not responding in fullscreen mode

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#5250] opened 2021-02-23 19:06 UTC
## Steps to reproduce
1. Create a group conversation
2. Enter fullscreen mode
3. click on the ... menu beside the "start call" button

### Expected behaviour
Conversation context menu opens

### Actual behaviour
Nothing happens

## Talk app

**Talk app version:** 10+11

**Comment by nickvergessen** [comment] 2021-02-23 19:42
Duplicate of #5027

**Closed by nickvergessen** 2021-02-23 19:42 UTC
Labels: 0. Needs triage, bug, feature: frontend 🖌️

**Comment by wiswedel** [comment] 2021-02-23 19:51
> Duplicate of #5027

Ah, missed that, sorry. Where's that handy duplicate suggestion dropdown gone anyway? 🤷‍♂️
