### ISSUE TITLE
Avatar does not show if you disable your camera before joining a room

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/spreed#178] opened 2016-12-13 14:11 UTC
When you disable your camera before joining a room it doesn't show avatar for other people (you still see your own)

enabling an re-disabling the camera fixes it

**Comment by Ivansss** [comment] 2016-12-15 18:13
I can't reproduce this issue. The only time I don't see any avatar is when a guest hides its camera.

**Comment by jancborchardt** [comment] 2016-12-15 23:05
@icewind1991 this occured because your webcam is broken or you don’t have one, right? We should catch that case too and then directly show the avatar in either case.

**Comment by nickvergessen** [comment] 2017-01-18 14:15
@Ivansss this is fixed now for firefox, but not for chrome, right?

**Comment by Ivansss** [comment] 2017-01-18 14:47
@nickvergessen not really 😬 , this is a different issue.

**Closed** 2017-05-08 10:59 UTC
Labels: 1. to develop, bug, medium, papercut, starter issue
