### ISSUE TITLE
Feature request - add syntax highlighting for commands/code

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/spreed#1187] opened 2018-09-16 19:02 UTC
Add syntax highlighting for commands/code.

Like the integrated editor:

![image](https://user-images.githubusercontent.com/16019165/45599866-838c4680-b9f3-11e8-9533-a6c2e76f96dd.png)

**Comment by nickvergessen** [comment] 2018-09-17 07:40
Duplicate of #1027

**Closed by nickvergessen** 2018-09-17 07:40 UTC

**Comment by owzim** [comment] 2024-02-07 21:51
@nickvergessen I don't see anything related to code highlighting in issue #1027
