### ISSUE TITLE
Sidebar and logo overlapping Menu

### ISSUE THREAD

**Issue by materthewelon** [nextcloud/spreed#3121] opened 2020-03-20 21:49 UTC
## Steps to reproduce
1. Install Talk App
2. Start New Conversation With Someone
3.  Click their profile picture
4. You can see the left sidebar overlaps the button and the logo also overlaps the button
Screenshot: http://prntscr.com/rjw8q1

### Expected behaviour
It should normally display the options in the menu that pops up when you click a users profile picture.

### Actual behaviour
The left sidebar overlaps the menu and/or a logo does too.

## Browser
Firefox

**Microphone available:** yes/no: Yes

**Camera available:** yes/no: Yes

**Operating system:** Windows/Ubuntu/...: Windows 10 Home

**Browser name:** Firefox/Chrome/...: Firefox

**Browser version:** 50.1/55/...: 74.0 (64 BIT)

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log: 

**Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). inject.js:44:31
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Setting current user talk.js:1661:19914
Current participant found talk.js:993:122107
Joined 
Object { data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, request: XMLHttpRequest }
talk.js:119:3213
Current participant found 19 talk.js:993:122107
Source map error: Error: request failed with status 404
Source Map URL: talk.js.map**



b) The network log: No errors are there
c) ...
```

</details>

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`): 8.0.5

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`): No

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`): No

## Server configuration

**Operating system**: Ubuntu/RedHat/...: Ubuntu 18.04 

**Web server:** Apache/Nginx: LiteSpeed Web Server

**Database:** MySQL/Maria/SQLite/PostgreSQL: MySQL

**PHP version:** 7.3

**Nextcloud Version:** (see admin page): 18.0.2

**List of activated apps:**:

Accessibility	1.4.0	Featured	
Brute-force settings	1.5.0	Featured	
Calendar	2.0.2	Featured	
Collaborative tags	1.8.0	Featured	
Comments	1.8.0	Featured	
Deleted files	1.8.0	Featured	
Federation	1.8.0	Featured	
File sharing	1.10.1	Featured	
Log Reader	2.3.0	Featured	
Mail	1.1.3	Featured	
Monitoring	1.8.0	Featured	
Nextcloud announcements	1.7.0	Featured	
Notifications	2.6.0	Featured	
ONLYOFFICE	4.1.4	Featured	
Password policy	1.8.0	Featured	
PDF viewer	1.7.0	Featured	
Photos	1.0.0	Featured	
Privacy	1.2.0	Featured	
Recommendations	0.6.0	Featured	
Registration	0.4.7		
Right click	0.15.2	Featured	
Share by mail	1.8.0	Featured	
Support	1.1.0	Featured	
Talk	8.0.5	Featured	
Text	2.0.0	Featured	
Theming	1.9.0	Featured	
Update notification	1.8.0	Featured	
Usage survey	1.6.0	Featured	
Versions	1.11.0	Featured	
Video player

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment] 2020-03-20 23:09
Duplicate of https://github.com/nextcloud/spreed/issues/2575#issuecomment-565756275

**Closed by nickvergessen** 2020-03-20 23:09 UTC
Labels: 0. Needs triage, bug

**Comment by materthewelon** [comment] 2020-03-20 23:39
Will this get fixed?
