### ISSUE TITLE
Enable Talk with Sharing Disabled 

### ISSUE THREAD

**Issue by mistletoe91** [nextcloud/spreed#1464] opened 2019-01-23 16:59 UTC
**Is your feature request related to a problem? Please describe.**
I do not want my users to share file folder outside nextcloud but I do love Nextcloud Talk App. When sharing disabled, netcloud talk app does not work 

**Describe the solution you'd like**
 Just keep talk working with sharing disabled

**Describe alternatives you've considered**
 No

**Additional context**

**Comment by nickvergessen** [comment] 2019-01-24 16:06
The problem is we use the sharing endpoints to get the users etc. which you are allowed to see. Without that it becomes quite hard, because we would have to duplicate it all.

**Comment by mistletoe91** [comment] 2019-01-24 16:12
Thanks for adding to Backlog, I understand its hard to implement but I think those two features are separate and decoupling them might be good idea. Thanks again

**Comment by nickvergessen** [comment] 2021-03-25 09:27
We are currently doing more and more the opposite on this, all kind of apps prevent interacting with groups when sharing with groups is disabled, etc.
So I will close this as we can't really workaround that anymore.

**Closed by nickvergessen** 2021-03-25 09:27 UTC
Labels: 1. to develop, enhancement, feature: settings ⚙️
