### ISSUE TITLE
Talk Group Media/Chat Media

### ISSUE THREAD

**Issue by apg1980** [nextcloud/spreed#7150] opened 2022-04-14 08:13 UTC
Hello,

i am asking, is it possible to integrate an extra tab for shared media within a room/chat?
Like whatsapp got this Groupmedia feature to see all the published images, videos, files within an chat.

This would be a great extension for usage. To reshare from an known chat i already shared a specific file, to another chat, or to find it easyer again.

Best regards

**Comment by nickvergessen** [comment] 2022-04-14 08:57
Duplicate of #1577

**Closed** 2022-04-14 08:58 UTC
Labels: 0. Needs triage, enhancement
