### ISSUE TITLE
"The conversation does not exist" with Edge

### ISSUE THREAD

**Issue by Psych3s** [nextcloud/spreed#5241] opened 2021-02-22 13:57 UTC
Idk may be its a bug in Edge but i think i should anyway post it...

## Steps to reproduce
1. Create a conversation with some users
2. Share it via link
3. Try to join via link as unauthirized user
4. Get "The conversation does not exist" message

### Expected behaviour
Joining as guest
### Actual behaviour
Getting "The conversation does not exist" message

## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
 10.1.2

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Edge (Chrome based)

**Comment by nickvergessen** [comment] 2021-02-22 14:00
So i tested at least with a logged in Edge and that worked.

**Comment by Psych3s** [comment] 2021-02-22 14:43
I u're logged in yes all works fine

**Comment by ReyKoxha** [comment] 2021-02-24 00:46
I was unable to reproduce this. Even when I opened a non public group and changed it as open for guests.
Clear your cache maybe.

**Comment by isdnfan** [comment] 2021-03-04 10:54
I have similar issue with one conversation after updating from NC19 > NC20 (no idea was just an intermediate step) > NC21 (spreed 11.0.0). As logged-in user a click on a conversation in list results in "conversation not found" message. There is an error which is shown very brief an immediately disappears "An error while fetching the participants"

![image](https://user-images.githubusercontent.com/18125597/109951499-0b5a8e00-7cde-11eb-968a-e0d7c2804739.png)

![image](https://user-images.githubusercontent.com/18125597/109951656-3fce4a00-7cde-11eb-92e3-50d05e9a1f10.png)

in the browser log I see first a successful request: ../ocs/v2.php/collaboration/resources/room/macviavc?format=json
followed by this request which results in 404: ../ocs/v2.php/apps/spreed/api/v1/chat/macviavc?lookIntoFuture=0&lastKnownMessageId=543&includeLastKnown=1

**Comment by nickvergessen** [comment] 2021-03-05 12:17
Yeah sounds like #4670  and/or #5148 

So lets close this for now

**Closed by nickvergessen** 2021-03-05 12:17 UTC
Labels: 0. Needs triage, bug
