### ISSUE TITLE
Talk error in NGINX+PHP_FPM env

### ISSUE THREAD

**Issue by ViVlVl** [nextcloud/spreed#8466] opened 2022-12-14 11:34 UTC
I’m running Nextcloud on debian 11, nginx  + php_fpm (php8.1)

I recently installed the Talk app and went into Administration settings > Talk and noticed this error under Web server setup checks.

`Could not detect the PHP and Apache configuration because exec is disabled or apachectl is not working as expected. Please note that PHP can only be used with the MPM_PREFORK module and PHP-FPM can only be used with the MPM_EVENT module.`

Support - System information report:

[2022-12-14 (2).md](https://github.com/nextcloud/spreed/files/10227334/2022-12-14.2.md)

nginx config - from https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html - "Nextcloud in the webroot of NGINX" section, only server_name and root path fixed.

same error yesterday from another user:  https://help.nextcloud.com/t/talk-errors-about-apache-in-nginx-environment/151730

**Comment by nickvergessen** [comment] 2022-12-20 09:14
It's a warning, not an error.
Yes the check is currently ignoring the fact that nginx could be used. But we still believe it can help people to discover issues with their setups.

We are thinking already how to improve the wording.

Duplicate of https://github.com/nextcloud/spreed/issues/8436

**Closed by nickvergessen** 2022-12-20 09:14 UTC
Labels: 0. Needs triage, bug
