### ISSUE TITLE
How do I remove or disable the 'Start Call' button for users?

### ISSUE THREAD

**Issue by greavette** [nextcloud/spreed#4004] opened 2020-08-10 03:48 UTC
I'm testing Nextcloud Talk 9.0.3 on our server.  We plan to use Nextcloud only within our office for chat purposes and not for Video.  I would like to remove the video button that says 'Start Call' as we do not need to see it. We will instruct people to not use but having it there will still allow people to click on it which will cause confusion. None of our workstations has microphones or webcams so having this button there will only cause confusion.

Please advise how we can remove this buttton or if a feature could be added to Talk Settings to remove this button by Group.

Thank you.

**Comment by PVince81** [comment] 2020-12-18 14:58
if you go to the admin settings, there's an option called "Limit starting a call".

but currently it only allows limiting it to moderators but not disabling completely.

I guess we could add an option also for disabling starting calls for everyone there.

**Comment by nickvergessen** [comment] 2021-01-05 14:21
Duplicate of #1282

**Closed by nickvergessen** 2021-01-05 14:21 UTC
Labels: 1. to develop, enhancement, feature: call 👥, feature: settings ⚙️
