### ISSUE TITLE
Added reaction doesn't trigger message polling

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#11286] opened 2023-12-22 10:24 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. As user 1, react to message
2. As user 2, wait up to 30 seconds to see reaction
3. As user 1, revoke reaction
4. As user 2, see updated list immediately

### Expected behaviour
Both actions from user 1 should trigger long polling of messages.
https://github.com/nextcloud/spreed/blob/f4ba35d820936fe8c34a92022fefde9845709947/lib/Controller/ChatController.php#L422

If I get it right, difference is in functions `addReactionMessage` and `deleteReactionMessage`:
First one somehow creates a system message under the hood, but doesn't trigger the pollling finisher
https://github.com/nextcloud/spreed/blob/bfa2c83fcee9d6b510b608b1c0474fb6c6cf0afb/lib/Chat/ReactionManager.php#L69

Second one calls `$this->chatManager->addSystemMessage`, which then calls `$this->dispatcher->dispatchTyped($event)` to return polling request:
https://github.com/nextcloud/spreed/blob/bfa2c83fcee9d6b510b608b1c0474fb6c6cf0afb/lib/Chat/ReactionManager.php#L111

## Talk app

**Talk app version:** 18+

**Custom Signaling server configured:** not related

**Comment by DorraJaouad** [comment] 2023-12-22 10:34
I think `addReactionMessage` is just missing this ( addsystemMessage) : 

```php
		$this->chatManager->addSystemMessage(
			$chat,
			$actorType,
			$actorId,
			json_encode(['message' => 'reaction', 'parameters' => ['message' => (int) $comment->getId()]]),
			$this->timeFactory->getDateTime(),
			false,
			null,
			$parentComment,
			true
```

Already tried it and it is fixing the issue, but I am doing sthg wrong with parameters :3 
![image](https://github.com/nextcloud/spreed/assets/84044328/8960499c-e41f-4f30-ba68-d1c812e3c09b)

**Comment by nickvergessen** [comment] 2024-01-01 16:44
Duplicate of #7064

**Closed** 2024-01-01 16:44 UTC
Labels: 0. Needs triage, bug, feature: api 🛠️, feature: reactions 👍
