### ISSUE TITLE
Group join/left call messages

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2948] opened 2020-02-13 15:22 UTC
In large meetings you see at the beginning a lot of "user X joined the call" and at the end "user Y left the call" notification which leaves the chat history in a quite "chaotic" state.

It would be nice to group all "user X joined call" and "user Y left call" messages to one message like
"userA userB userC joined the call"

A simple approach could be to look at the previous message, if it was the same message type we could extend it with the additional user. If not we post it as a new message. This way all join/leave messages would be grouped unless they where interrupted by another chat message.

**Comment by nickvergessen** [comment] 2020-02-13 15:54
Duplicate of #1148

And actually I'm against post-processing of messages. Especially with the upcoming offline support, this will be rather troublesome and means the logic has to be implemented by each client.

**Closed by nickvergessen** 2020-02-13 15:54 UTC
Labels: 0. Needs triage, enhancement
