### ISSUE TITLE
Downloading a text file from Viewer not possible during a call

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#8563] opened 2023-01-17 16:07 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Start a call
2. Share markdown file
3. Click on the file (Viewer opens)
4. Try to download via the actions in the top right

### Expected behaviour

The file downloads

### Actual behaviour

Talk asks me if I really want to leave the page

## Talk app

**Talk app version:** latest on 25
**Custom Signaling server configured:** yes/no and version (see additional admin settings: `/index.php/index.php/settings/admin/talk#signaling_server`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#turn_server`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/talk#stun_server`)

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 85/96/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:** 7.4/8.0/8.1

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment] 2023-01-18 07:56
Similar issue to https://github.com/nextcloud/spreed/issues/8551

**Comment by nickvergessen** [comment] 2023-05-02 07:16
So here the problem is actually the viewer I guess. The problem is it redirects to the webdav endpoint of the file so the browser triggers a download. But yeah leaving the call (with a redirect is not okay either). So maybe the download should happen in a new tab and close the tab after it started?

@Antreesy am I correct that this should be fixed more in the viewer/editors then Talk?

**Comment by Antreesy** [comment] 2023-06-23 14:19
@ChristophWurst please check if that's still a valid issue
Viewer adds 'Fullscreen button', so 'Download' isn't the only action button, and issue should be not reproducible anymore
Although I upstreamed the source problem to Vue library

**Closed** 2023-06-23 14:59 UTC
Labels: 1. to develop, bug, feature: frontend 🖌️, feature: call 📹
