### ISSUE TITLE
trying to execute a node application with talk commands

### ISSUE THREAD

**Issue by Laazarus** [nextcloud/spreed#2986] opened 2020-02-20 13:57 UTC
Hello,

I have a small node js application that I would execute with the talk app.

I have created the script and tested on the machine where nextcloud is running and everything works perfectly.
I registered the command as explained in the docs and I verified that the command can be executed (the help works and in general everything works except the last line)

when i run the command from talk i get 
An error occurred while running the command. Please ask an administrator to check the logs

If I commend the last line of my script (ts-node ./index.ts   $@) I can see all the echo in the chat correctly as follow:

moving to the src folder to execute the operation with paramters --application=worldschool --operation=content
/home/ubuntu/mp_worldschool_uploader_script/marcopolo4school-content-uploader/src
Starting the operation ...

here is the script:

```
while test $# -gt 0; do
      case "$1" in
        --help)
          echo "/calc - A Nextcloud Talk chat wrapper for gnome-calculator"
          echo " "
          echo "Simple equations: /calc 3 + 4 * 5"
          echo "Complex equations: /calc sin(3) + 3^3 * sqrt(5)"
          exit 0
          ;;
        *)
          break
          ;;
     esac
    done


echo "moving to the src folder to execute the operation with paramters $@" 

cd /home/ubuntu/mp_worldschool_uploader_script/marcopolo4school-content-uploader/src

pwd 

echo "Starting the operation ..."
 
ts-node ./index.ts   $@
```

## Steps to reproduce
1.create a script that execute a node js application passing some paramenters
2. register the command as per documentation
3.run the command in in he chat 

### Expected behaviour
I should run the script in the same way i run it from the terminal

### Actual behaviour
An error occurred while running the command. Please ask an administrator to check the logs.

**Comment by nickvergessen** [comment] 2020-02-20 14:00
Have you tried using a full path instead of `./index.ts` ?

**Comment by Laazarus** [comment] 2020-02-20 14:33
Hello @nickvergessen 

Just tried now but no luck... 

Is there anywhere where i can check logs?

**Comment by nickvergessen** [comment] 2020-02-20 14:38
Well does `sudo -u www-data ts-node ./index.ts` work in your console?

**Comment by Laazarus** [comment] 2020-02-20 15:00
Hello 
running the command like that in the script i get this 
```
-u www-data ts-node ./index.ts  --application=worldschool --operation=content
sudo: ts-node: command not found

```
I thought it could do something like that so in the script I tried to do
```
sudo su
```
before running the ts-node command but it does not work.

Is there a possible solution to this? (sorry if sounds a stupid question but I am not very familiar with Linux)

**Comment by nickvergessen** [comment] 2020-02-20 16:07
So your script is called by the apache user, and the problem is you didn't install ts-node for all users but just for your own.

**Comment by Laazarus** [comment] 2020-02-20 16:28
Ok I found that the user www-data cannot find the node path.

If i run the command with the absolute path of node the script runs but I have other problems in the script (mainly because I cannot find the .env file that my project uses:( )

Is there anyone that faced the same problem?

**Comment by nickvergessen** [comment] 2020-02-26 13:19
Closing as it is not a problem with the talk app

**Closed by nickvergessen** 2020-02-26 13:19 UTC
Labels: needs info

**Comment by Laazarus** [comment] 2020-02-28 12:02
Hi, yes I confirm it is not a problem with talk app, was me that forgot to use absolute path as mentioned in the docs!!!
Sorry for this. 

Now that everything works though I am facing another problem, The script that I am running takes a couple of minutes to executes and I am getting always the error

"The message you are trying to Send is too long".

Is there any configuration that I can use to make Talk understand it is not actually a message but a script that is taking that time?

**Comment by nickvergessen** [comment] 2020-02-28 13:33
The error message doesn't mean your message takes too long, but the actual content is too long. Messages can only be up to 32000 characters long.

**Comment by Laazarus** [comment] 2020-02-28 13:36
Ok I will try to reduce the characters and I will see if that works Thanks
