### ISSUE TITLE
Restrict sharing with users within the group (check field in the administration settings)

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/spreed#8990] opened 2023-03-07 14:00 UTC
## Steps to reproduce
1. User A in Group A / User B in Group B
2. Disable the checkbox Restrict sharing with users within the group in the admin settings
3. look in Talk at the user list

### Expected behaviour
Tell us what should happen
Users from different groups should be displayed.
### Actual behaviour
Tell us what happens instead
Only the users of their own group are displayed.
## Talk app

**Talk app version:** (see apps admin page: `/index.php/settings/apps`)
 15.0.4
## Server configuration
Nextcloud AIO -stable

**Comment by nickvergessen** [comment] 2023-03-07 14:10
Which user list? Can you add a screenshot?

**Comment by nickvergessen** [comment] 2023-03-08 10:16
Can you please show a screenshot of the sharing settings?
This all works as expected here.

**Comment by R7JANV1** [comment] 2023-03-08 12:02
> Can you please show a screenshot of the sharing settings?
> This all works as expected here.

![Screenshot_20230308-130114~2.png](https://user-images.githubusercontent.com/90777102/223708304-f2532138-9dfd-44c7-81fa-838e719e25c0.png)

**Comment by R7JANV1** [comment] 2023-03-17 18:19
could you reproduce the problem?  And is there more information about it?

**Comment by nickvergessen** [comment] 2023-03-29 15:03
These are the default settings and I can see other users pretty fine.

So that brings me back to:
> Which user list? Can you add a screenshot?

Without a screenshot to know where you think something is wrong, it's very hard for us to follow.

**Comment by nickvergessen** [comment] 2023-03-29 19:13
I'm totally unsure which list and search you are talking about.
But note that chats are not automatically created with the other users, etc. So you first need to start a chat with them before they appear in the left sidebar, you might have to search then name for them to pop up in the right sidebar or when creating a new conversation.
For anything else you need to make a screenshot so we know what search or input or whatever you are talking about.

**Comment by R7JANV1** [comment] 2023-03-29 20:15
![grafik](https://user-images.githubusercontent.com/90777102/228656792-06a83d21-c6b4-4ebd-a8e4-7c5d2b206723.png)

> you might have to search then name for them to pop up in the right sidebar

This exactly is the problem: When searching for the name of another user to create a new conversation, the user you look for does not appear.

**Comment by nickvergessen** [comment] 2023-03-30 10:06
I can not reproduce:

Description | Screenshot
---|---
Sharing settings | ![Bildschirmfoto vom 2023-03-30 12-01-59](https://user-images.githubusercontent.com/213943/228801956-28fefd76-6866-40f7-bc81-432fd07a6d70.png)
User "Num-Eric User" and "Bennet" don't share a group | ![Bildschirmfoto vom 2023-03-30 12-01-07](https://user-images.githubusercontent.com/213943/228802235-9d0fedf5-ec99-435a-99ce-e31a6173163b.png)
Bennet can see Eric when searching left | ![Bildschirmfoto vom 2023-03-30 12-00-12](https://user-images.githubusercontent.com/213943/228802317-92164466-4c14-4d07-9b29-a3267dddd6ba.png)
In creating group conversation preload | ![Bildschirmfoto vom 2023-03-30 12-00-29](https://user-images.githubusercontent.com/213943/228802595-4714e646-1143-43f9-9e6d-71fe10f0a85d.png)
In creating group conversation with search | ![Bildschirmfoto vom 2023-03-30 12-00-35](https://user-images.githubusercontent.com/213943/228802652-2009a354-e0bd-49cb-9bac-9f4016778ec7.png)
In right sidebar to add a user | ![Bildschirmfoto vom 2023-03-30 12-00-51](https://user-images.githubusercontent.com/213943/228802704-0c1c7a07-7604-4624-ba20-596cd569ff6a.png)

Is there an error logged in the console maybe? Or in the nextcloud.log of the server, or anything?

**Comment by R7JANV1** [comment] 2023-03-30 10:30
Very interesting... I set up an instance for testing and everything works there as you describe it. However, I have two other instances running (using Nextcloud AIO) and the problem occurs with both. Maybe it's the version of Nextcloud? I tested it with Nextcloud 26 and everything works as it should. Unfortunately, it doesn't work with my Nextcloud AIO instances.

**Comment by nickvergessen** [comment] 2023-03-30 11:45
You might want to ask for help with the AIO then, but in Talk there is nothing to do, so I would close this issue here.
The related code is the same since many releases, so I don't think there is a problem with major versions

**Closed by nickvergessen** 2023-03-30 11:45 UTC
Labels: 0. Needs triage, bug, needs info
