### ISSUE TITLE
Make people aware of unread mentions out of the viewport of the conversation list

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#3299] opened 2020-04-08 11:28 UTC
Having lots of favorited chats might lead to missing unread one, as the user has to scroll down a bit.
If app chooser a litte unread chat counter would be shown, the user can directly see that they have to scroll down a bit.

**Comment by nickvergessen** [comment] 2020-04-08 12:38
The biggest issue is people would then expect this is there all the time so we would need to get your room list on all pages, etc.
Huge performance break hitting in, so backlog for now

**Comment by tobiasKaminsky** [comment] 2020-04-08 12:57
True.
Maybe to make this more clear, we could show a 0 (or x for unread chats) when we are in talk and only the talk icon if we are in any other app.

**Comment by Dubidubiduu** [comment] 2020-06-10 11:20
I have a lot users only logging in for our monthly conference. Would be a big plus to inform them about unread messages. Since I prefer "sidemenu" over regular one I would prefer that hint on profile icon or so. Something like an additional custom field (e.x. Use Nextcloud Talk App for smartphone) and never miss a message is a big plus.

Also a "use smartphone app to never miss a message" overlay once a month to users who aren't using that, propably nc-app based, would help.

**Comment by tobiasKaminsky** [comment] 2020-07-20 05:28
I had this today again.
I have multiple 1:1 chats and one of those chats I delayed for ~1-2 days to answer it, but then all new chats were higher in list and thus the unread and important chat scrolled out of the visible list and thus I never answered it.
I just found it now by "accident".

**Comment by nickvergessen** [comment] 2020-07-28 12:54
Mabye we add a red dot similar to the notifications app one, but only when you are on talk? But that might be too confusing already again, as people might then think "Talk doesnt have the red dot, so no need to go there".

cc @nextcloud/designers-talk for input?

**Comment by jancborchardt** [comment] 2020-07-28 14:15
Let’s step back and look at the problem:

> Having lots of favorited chats might lead to missing unread one, as the user has to scroll down a bit.

The solution to that would be to show an indicator on the bottom of the conversation list. E.g. like this, similar to Twitter and Instagram do it with the "new unread posts" on the top of their view:
![image](https://user-images.githubusercontent.com/925062/88677366-795a2980-d0ed-11ea-9cbe-2ee3d074274b.png)

This doesn’t have the drawback of the global indicator either. :)

**Comment by tobiasKaminsky** [comment] 2020-09-18 08:01
Another, and maybe more simple solution would be to have sorting like this:
- favorites
- unread
- rest, sorted by date

This way one can always see their unread conversations (except if one has too many favorites and too small window :see_no_evil:)

**Comment by jancborchardt** [comment] 2020-09-18 09:57
@tobiasKaminsky could be a possibility, yes. But then I would say _only_ the unread @-mentions should be sorted up top.

But even if we have that, we still need to account for the fact that there are unread mentions which are above or below the current scrolled viewport. And for that the way Twitter does it and the mockup I showed above is needed either way. :) Also, this is how Discord does it:
![Peek 2020-09-18 11-27](https://user-images.githubusercontent.com/925062/93584825-20e53100-f9a6-11ea-9a82-9be217606ac8.gif)

**Comment by Dubidubiduu** [comment] 2021-04-02 10:49
Also we need something which indicates unread messages for moments you use other apps, like in the screenshot Jan shared but also Teams is doing it. Cause my users don't always start through dashboard.

**Comment by tobiasKaminsky** [comment] 2021-06-22 06:59
So I again missed some "urgent" conversations as they were hidden…
Can't we have some short win for this…? 😞

**Comment by AndyScherzinger** [comment] 2021-09-23 14:49
@jancborchardt this has been implemented now (and here comes the "but")... but it'll only be shown to actual mentions. So in my test were this became clear to me was when I all rooms read completely except a 1on1 I have with Tobias. My Android view shows 7 items in the list and Tobias chat was around position 20+ so I think the items that lead to the "unread bubble" should be explicit mentions as well as 1on1 with unread messages, no?

**Comment by jancborchardt** [comment] 2021-09-23 14:54
> so I think the items that lead to the "unread bubble" should be explicit mentions as well as 1on1 with unread messages, no?

Yes, 100%. Additionally I'd say that all 1on1 chat bubbles should always be blue/primary since they are only ever for you, just like @-mentions

**Comment by AndyScherzinger** [comment] 2021-09-23 14:56
> Yes, 100%. Additionally I'd say that all 1on1 chat bubbles should always be blue/primary since they are only ever for you, just like @-mentions

@jancborchardt I mean the little bubble at the bottom that scrolls you to the first item in the list where has unread mentions

**Comment by AndyScherzinger** [comment] 2021-09-23 15:00
Okay, then I just don't understand the "additionally" part of the sentence since that bubble is always blue/primary be default ;)

**Comment by nickvergessen** [comment] 2021-09-23 15:00
> Yes, 100%. Additionally I'd say that all 1on1 chat bubbles should always be blue/primary since they are only ever for you, just like @-mentions

This is already the case, but I now noticed we do this in the UI:
https://github.com/nextcloud/spreed/blob/98d679964a2352a4fa455c514944273a2b14b778/src/components/LeftSidebar/ConversationsList/Conversation.vue#L160-L162

So that condition should of course also work for the "Unread mentions" bubble.

**Comment by nickvergessen** [comment] 2021-09-23 15:01
Just checked and iOS is already doing it:
https://github.com/nextcloud/talk-ios/pull/617/files#diff-aab5ed2e45f307347a961ee9ac3ca1f75b62223325d16f337ee87904fa9c0b66R483

**Comment by nickvergessen** [comment] 2021-09-23 15:04
Place where this needs fixing https://github.com/nextcloud/talk-android/pull/1588/files#r714890635

**Comment by AndyScherzinger** [comment] 2021-09-23 15:09
Ah, nice

**Comment by AndyScherzinger** [comment] 2021-09-23 15:09
I'll do a drive-by PR for Android then ❤️ Thanks for checking @nickvergessen 🙏

**Comment by mahibi** [comment] 2021-09-24 07:06
thanks @AndyScherzinger & @nickvergessen :+1:

**Comment by Ivansss** [comment] 2021-10-07 12:45
As discussed with @jancborchardt the text for the unread mentions indicator should be "Unread mentions"

<img width="148" alt="Screenshot 2021-10-07 at 14 43 29" src="https://user-images.githubusercontent.com/4638605/136386330-ebf59c6a-5eec-48e9-90d9-1f2273062fef.png">

@mahibi @marcoambrosini

**Comment by nikola-gladovic** [comment] 2022-04-06 15:17
@marcoambrosini  
Which api we can use to get the number ?

**Comment by nickvergessen** [comment] 2022-04-07 10:42
There is no specific API.
Basically you have to check in the ConversationList component the elements which are below the viewport and check if they have the unreadMention flag set to true.

**Comment by nikola-gladovic** [comment] 2022-04-26 16:05
I think it was already working well on master branch :)

**Comment by nickvergessen** [comment] 2022-04-26 16:24
FIxed via https://github.com/nextcloud/spreed/pull/7115

**Comment by tobiasKaminsky** [comment] 2023-01-25 08:55
This does not work for me in ~80% of time.
Can I help to debug it?

**Comment by nickvergessen** [comment] 2023-01-25 08:58
Works pretty fine here.
You have any reproduction steps?

**Comment by tobiasKaminsky** [comment] 2023-01-25 09:35
- 7 starred conversations
- 6 unread conversations (some group, some 1:1) 3 are visible, 3 not
--> no "unread chat" bubble

**Comment by nickvergessen** [comment] 2023-01-25 10:52
Any error in the browser console?

**Comment by nickvergessen** [comment] 2023-01-25 10:53
Raised a new issue in https://github.com/nextcloud/spreed/issues/8599 so the board is not showing open todos from 1 year ago

**Closed** 2023-01-25 10:53 UTC
Labels: 1. to develop, enhancement, low, feature: frontend 🖌️
