### ISSUE TITLE
Conversation creation experience improvements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#2797] opened 2020-01-19 13:39 UTC
## Steps to reproduce
1. Create a new conversation
2. Go to the "Add participants" step
3. Be confused by there being no people shown
4. Search manually for the first person by typing in the search field
5. Check them
6. Remove the search
7. Repeat steps 4 to 6 until you have everyone in

### Expected behaviour
The dialog should no only show an emptycontent view and force you to search, but:

- Show the first ~50 contacts/groups/etc. in the list so people see immediate feedback that content exists and in the ideal case can directly choose the people to start a conversation with.
- While it loads these initial contacts, show a loading spinner and text below saying "Loading contacts …" (compare to the Contacts menu in the top right)
- On the bottom of this list of 50, show an emptycontent element saying "Search for more contacts" which on tap focuses the search field.

This should be the same cross-platform, on the web, Android and iOS.

--------------------------------------

As discussed with @mario @Ivansss and also mentioned to @ma12-co @nickvergessen

**Comment by ma12-co** [comment] 2020-01-20 08:40
duplicate of #2546

**Closed** 2020-01-20 08:59 UTC
Labels: 1. to develop, client: 🤖🍏 mobile, enhancement, high, mobile apps
