### ISSUE TITLE
Description not easy to find during call

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#7501] opened 2022-06-30 08:34 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When in a conversation, the description is nice and present. If there is a link to meeting notes or something like that, it’s easy to find.
As soon as you join the call though – the moment when you actually need the meeting notes – the description is only reachable via the menu anymore.

**Describe the solution you'd like**
For there to be a header as well during the call, for example. The navigation toggle and buttons on top right stay anyway, so the title and description could also stay where they are.
@marcoambrosini since I’m sure we either talked about this before or you thought about this. :)

**Additional context**
In conversation (description shows nicely):
![image](https://user-images.githubusercontent.com/925062/176631753-557a3c7c-aafe-41e9-a268-0504eac0faaa.png)

During call (unsure where to find description):
![image](https://user-images.githubusercontent.com/925062/176631167-915c9339-406c-4023-b93d-2d94f85557c1.png)

**Comment by nickvergessen** [comment] 2022-06-30 10:27
Duplicate of #6766

**Closed by nickvergessen** 2022-06-30 10:27 UTC
Labels: 0. Needs triage, design, enhancement, feature: frontend 🖌️, feature: call 👥
