### ISSUE TITLE
Ability to 'raise hand'

### ISSUE THREAD

**Issue by brylie** [nextcloud/spreed#979] opened 2018-06-20 17:51 UTC
When using Nextcloud Talk, not all participants are always visible. This makes it difficult to know when someone might like to speak.

# Feature request
(as seen in Jit.si Meet, etc) Add the ability to 'raise hand' which sends a small visual notification to all other group participants. Possibly add a 'stack' widget, where the hand raisers will be listed in the order they raised their hands. Taking stack is often the task of a facilitator, to make sure everyone gets a chance to speak in due order.

**Comment by nickvergessen** [comment] 2018-07-19 14:39
Duplicate of #364

**Closed by nickvergessen** 2018-07-19 14:39 UTC
Labels: enhancement
