### ISSUE TITLE
Make conversation password rule and more protection...

### ISSUE THREAD

**Issue by FlyingHarman** [nextcloud/spreed#6859] opened 2022-02-03 00:41 UTC
![dfg](https://user-images.githubusercontent.com/98791491/152261459-f0c9cb52-b572-4ee4-abe7-4efa062c381d.png)

no any protection for conversation password  so far,set password 2 simple like 1234, not safe and anyone can brute force without any protection

so could u consider about this and make it more safe?
for examle, password rule like what nextcloud did to anti-brute focrce in security of settings and wrong typing no more than 20 or 40 times (lock IP or block id for a while)

**Comment by FlyingHarman** [comment] 2022-02-04 13:26
this is sth about security,so plz take care of

**Comment by nickvergessen** [comment] 2022-02-09 14:00
Should just use the API of the password_policy app to verify the password and error otherwise.

**Comment by nickvergessen** [comment] 2022-06-10 10:41
Duplicate of https://github.com/nextcloud/spreed/issues/3089

**Closed by nickvergessen** 2022-06-10 10:41 UTC
Labels: 1. to develop, bug, feature: settings ⚙️
