### ISSUE TITLE
[Feature Request] attachments 📎 to posts from local device file system too please 

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/spreed#3093] opened 2020-03-17 03:59 UTC
Just  tonight I realized why people in my group chat left NextCloud and went back to the MMS thread. Somebody posted a screen shot. I realized that I could because I'm synching that folder but they aren't.

Is it that difficult for the application to pull in content from the local storage to insert into the message thread? I assumed it would be there already but I never tried to do it till tonight.

**Comment by nickvergessen** [comment] 2020-03-17 06:25
Duplicate of #1811

**Closed by nickvergessen** 2020-03-17 06:25 UTC
