### ISSUE TITLE
Feature: All Talk Attendees to Add Name When Entering New Call

### ISSUE THREAD

**Issue by stownsend101** [nextcloud/spreed#5812] opened 2021-06-21 11:56 UTC
**Is your feature request related to a problem? Please describe.**
Meeting request is shared, attendees join call and aren't asked to edit name, appearing as 'Guest'. Difficult to identify in conversation. 

**Describe the solution you'd like**
All attendees, who do not have a Talk account, are asked to update name on hitting 'Start Call'.

**Describe alternatives you've considered**
Name attendees as moderator - but this will take too much time. 

**Additional context**
No.

**Comment by PVince81** [comment] 2021-06-21 12:19
duplicate of https://github.com/nextcloud/spreed/issues/855

**Closed by PVince81** 2021-06-21 12:19 UTC
Labels: 0. Needs triage, enhancement
