### ISSUE TITLE
Follow-up(Reactions): Add 'all' reactions

### ISSUE THREAD

**Issue by DorraJaouad** [nextcloud/spreed#11326] opened 2023-12-31 11:08 UTC
Follow-up to  #11261

TODO:
* Reactions now are ordered by chronological order of last updated. It should be ordered by the count (order by descending) (done)

New feature:
* Add a reaction popover including all users who reacted.

**Comment by nickvergessen** [comment] 2024-01-01 16:42
Duplicate of #7193

**Closed** 2024-01-02 10:00 UTC
Labels: 1. to develop, bug, enhancement, feature: reactions 👍
