### ISSUE TITLE
Last message not shown

### ISSUE THREAD

**Issue by Ho551** [nextcloud/spreed#5247] opened 2021-02-23 11:18 UTC
## Steps to reproduce
1. Open talk in Browser
2. Open random chat
3. Switch to another chat

### Expected behaviour
The last message should be visible in new chat.

### Actual behaviour
The last message is not visible in new chat .

## Talk app

**Talk app version: 11.0.0

**Custom Signaling server configured: no
**Custom TURN server configured:** yes
**Custom STUN server configured:** yes

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Windows

**Browser name:** Chrome, Edge (Chromium)
**Browser version:** 88.0.4324.182

## Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud Version:** 21.0.0

**Comment by nickvergessen** [comment] 2021-02-23 11:19
Duplicate of #5188

**Closed by nickvergessen** 2021-02-23 11:19 UTC
Labels: 0. Needs triage, bug
