### ISSUE TITLE
Talk returns empty site

### ISSUE THREAD

**Issue by csware** [nextcloud/spreed#3614] opened 2020-05-19 07:39 UTC
## Steps to reproduce
1. Install/update Spreed to 8.0.9
2. Open the Talk "tab"

### Expected behaviour
The Talk app is usable as before 8.0.9.

### Actual behaviour
"Empty" page, white space. No Talk app.

A similar problem arises when opening the app settings, there no controls are visible.

## Browser

**Operating system:** Windows.

**Browser name:** Firefox

**Browser version:** 76.0.1

### Browser log

<details>
```
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions granted App.vue:242
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. addStylesClient.js:220:17
Die Ressource von "https://SERVER/apps/files/" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff). spreed
Laden fehlgeschlagen für das <script> mit der Quelle "https://SERVER/apps/spreed/js/talk.js?v=604baed0-21". spreed:43:1
```

</details>

## Talk app

**Talk app version:** 8.0.9

**Custom TURN server configured:** no

**Custom STUN server configured:** yes

## Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.3.18

**Nextcloud Version:** 18.0.4

No errors logged to `nextcloud.log`

**Comment by csware** [comment] 2020-05-19 14:08
He `js` folder of the app was empty.

Deactivating, removing and readding the app solved this issue.

**Comment by nickvergessen** [comment] 2020-05-19 15:44
Duplicate of #3535

**Closed by nickvergessen** 2020-05-19 15:44 UTC
Labels: 0. Needs triage, bug
