### ISSUE TITLE
Dialog box is partially covered

### ISSUE THREAD

**Issue by the-matzup** [nextcloud/spreed#3604] opened 2020-05-18 11:47 UTC
Display error when an attachment is to be added in a conversation: The dialog box is covered by the sidebar.

NC 19 RC2
Tested with: Firefox 76 & Chrome 81

**Comment by the-matzup** [comment] 2020-05-18 11:47
![Bildschirmfoto 2020-05-18 um 12 40 43](https://user-images.githubusercontent.com/47818886/82209744-163e6080-990e-11ea-9af9-365e557735ba.png)

**Comment by the-matzup** [comment] 2020-05-18 11:48
![Bildschirmfoto 2020-05-18 um 13 48 24](https://user-images.githubusercontent.com/47818886/82209851-45ed6880-990e-11ea-9325-fc5c90955096.png)

**Comment by nickvergessen** [comment] 2020-08-19 18:57
Duplicate of #3455

**Closed by nickvergessen** 2020-08-19 18:57 UTC
Labels: 1. to develop, bug, feature: frontend 🖌️, feature: upload & shares 📤
