### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by JanKoIT** [nextcloud/spreed#5261] opened 2021-02-25 06:26 UTC
A clean installation with MariaDB (Plesk) NC21
Next step install Talk.
Tried to make a Conversion:
 
`Verursacht durch Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxxxxxxx.oc_talk_sessions' doesn't exist`

the table is not in DB.

OC Repair did not find any issues

**Comment by jessebrownfl** [comment] 2021-02-28 00:32
Have the same missing table errors after upgrading NextCloud to 20.0.8 from 20.0.7 with Talk version 10.0.6

**Comment by nickvergessen** [comment] 2021-02-28 08:01
The table is new in Talk 10.1

**Comment by JanKoIT** [comment] 2021-02-28 09:16
ok, so i need to install them manually?

**Comment by nickvergessen** [comment] 2021-02-28 09:45
Well you would first need to post a bit more information. Like which version you have and what you did, etc

**Comment by JanKoIT** [comment] 2021-02-28 10:03
As in my first post i installed it fresh install (went fine) than go to apps an install talk, that´s it
Version
Nextcloud 21.0.0
Talk	11.0.0

**Comment by JanKoIT** [comment] 2021-02-28 10:22
it's my first problem with Nextcloud since version 17

**Comment by nickvergessen** [comment] 2021-03-02 09:32
Well I installed 11 and we do it up to hundred times per week for testing our work. There is a clear dedicated step that adds this table and it works.
So you did something special, maybe restore a (partial) backup after updating or something. But at least with normal strategy I can not reproduce any issue.

**Comment by JanKoIT** [comment] 2021-03-02 18:44
hmm ok. I checked now everything and noticed that this server is using MariaDB 10.1. It might be there this problem?
Since this is a produktion server i must wait to upgrade.

**Comment by nickvergessen** [comment] 2021-03-03 09:48
Yeah Nextcloud 21 only supports MariaDB 10.2 and later

**Comment by nickvergessen** [comment] 2021-03-03 09:49
You should have seen a warning before the upgrade

**Comment by mrjive** [comment] 2021-03-05 11:04
> As in my first post i installed it with a fresh install (went fine) than go to apps an install talk, that´s it
> Version
> Nextcloud 21.0.0
> Talk 11.0.0

I have the same problem on different installs of NC21+Talk11. Both are on shared hosting (OVH).
No problem with NC20.0.7+Talk10.0.6, same hosting.

Today I updated Talk to 11.1.1 with no luck (same error), so I tried to delete and reinstall, but it failed with the following error:
"App "spreed" cannot be installed because appinfo file cannot be read."

Thanks!
 davide

**Comment by arthurkoch** [comment] 2021-03-08 19:07
I had a problem with the assigned_hpb column. It was the [last migration file](https://github.com/nextcloud/spreed/blob/master/lib/Migration/Version10000Date20201015134000.php) in the Migrations folder. What I did was to create the column by myself. So it seems that the migration is somehow not working correctly sometimes. @nickvergessen Do you maybe know the right syntax for the occ migration command? Would this command even be able to fix it?

**Comment by nickvergessen** [comment] 2021-03-08 19:58
The occ migration commands are only for developers and should never be executed.

**Comment by arthurkoch** [comment] 2021-03-08 21:20
hey, thank you very much for the answer.
do you know a method to manually execute the database migrations for a nextcloud app?

**Comment by nickvergessen** [comment] 2021-03-08 21:23
You should just put all files into the folder and then the web or occ upgrade command do the rest

**Comment by arthurkoch** [comment] 2021-03-08 22:03
I deleted the column again, reinstalled the app and tried to do an occ upgrade - it's saying that everything is up to date and the column is still missing. I don't want to bother you too much, I found a fix working for myself - but I'm still curious about why the migrations are not happening.  The [documentation about migration ](https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html) isn't helping that much.

```
www-data@600f62e4a6a5:~/html$ ./occ migrations:status spreed
    >> App:                                                spreed
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\Talk\Migration
    >> Migrations Directory:                               /var/www/html/custom_apps/spreed/lib/Migration
    >> Previous Version:                                   8000Date20200407073807
    >> Current Version:                                    8000Date20200407115318
    >> Next Version:                                       10000Date20200819121721
    >> Latest Version:                                     11001Date20210211111527
    >> Executed Migrations:                                45
    >> Executed Unavailable Migrations:                    45
    >> Available Migrations:                               44
    >> New Migrations:                                     44
    >> Pending Migrations:                                 None
```
Does this look right? I kind of think not - shouldn't the Current Version be the latest version?

**Comment by mrjive** [comment] 2021-03-09 11:55
You're right, but the problem is the tables are note created when the app is installed. Neither version 11 nor 11.1.1 seem to work.

**Comment by baipai666** [comment] 2021-03-22 11:04
is there a solution to the problem?
nc21 / Talk 11.1.1 / Mariadb 10.2

Can I use an old working version of Talk with NC21?

**Comment by mrjive** [comment] 2021-03-22 11:07
I don't think so.
I've already tried downloading previous versions with no luck.

**Comment by baipai666** [comment] 2021-03-22 11:17
i try to install 10.2 now. wait 30 min. I'm tell you the result

**Comment by mrjive** [comment] 2021-03-22 11:19
if you install a previous version (I tried 10.0.6) NC21 complains that it is not compatible and starts upgrading. At least this is my experience.

**Comment by baipai666** [comment] 2021-03-22 11:21
here with 10.2 same. Not compatible and same Problem

my log:
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c1nc.oc_talk_sessions' doesn't exist

I'm thinking we need to live with WhatsUp

**Comment by mrjive** [comment] 2021-03-22 12:39
> here with 10.2 same. Not compatible and same Problem
> 
> my log:
> Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c1nc.oc_talk_sessions' doesn't exist

Yes, same problem here. A temporary solution would have to get the table's schema and create them manually. I'd gladly do it, thus being able to use talk again!
> 
> I'm thinking we need to live with WhatsUp

nah. Use element.io instead! ;)

**Comment by baipai666** [comment] 2021-03-22 13:32
I'm add the Table oc_talk_session and the app can start now. i can make a group chat but the video call not working fine. The Android App say Server App not installed. To much bugs on this app.

I'm waiting now for a working Update of Spreed-Talk.

**Comment by mrjive** [comment] 2021-03-22 13:44
Here's a workaround
https://help.nextcloud.com/t/nc-21-and-talk-11-not-wroking-after-migration-to-nc21-solved/111571
It' worked well for me!

**Comment by baipai666** [comment] 2021-03-22 13:50
Wow, many thanks. I'm try this tomorrow.
I'm looking 2 Days with Google for a Solution

**Comment by arthurkoch** [comment] 2021-03-22 13:52
> Here's a workaround
> https://help.nextcloud.com/t/nc-21-and-talk-11-not-wroking-after-migration-to-nc21-solved/111571
> It' worked well for me!

hey mrjive,
thanks for the link. 
so all migrations "done" are saved in a database - to repeat the migration you have to delete the entries in the table.
nice to know!
hava a good day

**Comment by mrjive** [comment] 2021-03-22 14:02
> so all migrations "done" are saved in a database - to repeat the migration you have to delete the entries in the table.
> nice to know!

yes, so basically if the app thinks the migration already took place, it doesn't try to create the tables needed. (If I got this correctly). Simple, after all... :) Thanks to **n0plan** for the solution!

**Comment by nickvergessen** [comment] 2021-03-22 19:22
Don't do that....

Maybe one of you can explain in more details what you did, so we can figure out the actual wrong part. Why is the migration apparently stored as run but didn't execute? Anything in your nextcloud.log file?

**Comment by nickvergessen** [comment] 2021-03-22 19:28
Also maybe someone can create isolated steps to reproduce the problem.

E.g.:

1. Download https://download.nextcloud.com/server/releases/latest-20.zip
2. Install it
3. Enable Talk from the appstore (gives 10.0.6)
4. Update Nextcloud to 21 via the updater
5. Talk updates to 11.1.1 on the update
6. ???
7. Table is missing
8. Post the log file in the issue.

**Comment by baipai666** [comment] 2021-03-22 23:54
Many Thanks for this solution. Now have all Table in the Database.
Only Videochat from (App to PC) or (PC to PC )not working. But this is another problem.

Error: Call to a member function getContainer() on null
Error: Undefined index: mail at /var/www/web/lib/private/AppFramework/Bootstrap/RegistrationContext.php#421

**Comment by nickvergessen** [comment] 2021-03-23 14:10
So apparently when some opcache and other caching is enabled:
```
TypeError: Argument 2 passed to OC\Comments\Manager::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in app/nextcloud_install/nextcloud/apps/spreed/lib/Chat/CommentsManager.php on line 46 and defined in app/nextcloud_install/nextcloud/lib/private/Comments/Manager.php:77
```

could be a problem. The problem is that the class is loaded/initialised with the old constructor and then tried to be used with the new dependencies which of course goes boom

**Comment by nickvergessen** [comment] 2021-07-05 09:25
Closing as this is nothing Talk can solve

**Closed by nickvergessen** 2021-07-05 09:25 UTC
Labels: 1. to develop, bug, technical debt
