### ISSUE TITLE
option to hide chat "administrative" messages

### ISSUE THREAD

**Issue by fabriziosalmi** [nextcloud/spreed#7012] opened 2022-03-16 21:20 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Talk is great and I cannot find a simple method to hide any "administrative message" in a specific chat room.
For administrative message I mean messages like "userX cleared the history of the conversation" or "userX renamed conversation from oldname to newname" or "userX cleared the history of the conversation".

**Describe the solution you'd like**
A simple options in the conversation option panel to hide all administrative messages for specific/all chat room user(s), specific user(s) or specific user group(s).

**Describe alternatives you've considered**
Manually (and selectively) deleting administrative messages as they appears (sounds crazy, isnt'it? :D )

**Additional context**
Since Nextcoud is a solid software I'm sure I'm lack knowledge, this feature is already available in some way and I just steal some time to a solid dev team :)

**Comment by nickvergessen** [comment] 2022-03-17 15:41
Duplicate of #1148

Not fully, but that is all we will do for that bit for now.

**Closed by nickvergessen** 2022-03-17 15:41 UTC
Labels: 0. Needs triage, enhancement
