### ISSUE TITLE
Nextcloud Talk app Not input Japanese character

### ISSUE THREAD

**Issue by masaburo02** [nextcloud/spreed#1603] opened 2019-03-11 02:45 UTC
## Steps to reproduce
1.I use talk
2.I tryed input new message on Japanese IME.
3.I could enter the halfwidth there, but I could not enter the fullwidth (Japanese KANJI and HIRAGANA).

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Browser

**Microphone available:** yes/no
no
**Camera available:** yes/no
no
**Operating system:** Windows/Ubuntu/...
Windows10
**Browser name:** Firefox/Chrome/...
Chrome
**Browser version:** 50.1/55/...
72.0.3626.121
### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app
Talk
**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...
CentOS 7.6.1810
**Web server:** Apache/Nginx
Apache 2.4.6
**Database:** MySQL/Maria/SQLite/PostgreSQL
MySQL 5.7.25
**PHP version:**
7.2.16
**Nextcloud Version:** (see admin page)
15.05
**List of activated apps:**
5.0.5
<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment] 2019-03-11 07:28
Can you describe what happens? And maybe add screenshots and example inputs which i can try?

**Comment by masaburo02** [comment] 2019-03-11 08:38
Thank you mail.

I used Nextcloud Talk in my local Server.
I tryed input Japanese Language to Nextcloud Talk New message.
I can't input Japanese Language, but English done.
However, after input english, i can input Japanese done.

masaburo02

2019年3月11日(月) 16:28 Joas Schilling <notifications@github.com>:

**Comment by angry-tony** [comment] 2019-03-19 23:16
• Workaround
Before typing japanese language, Input special characters andthen typing your language.

Ex) !あいさつ

**Comment by nickvergessen** [comment] 2019-03-20 14:49
Is this the same problem as #1071 ?
I still fail to have an option to test this, as I couldn't manage to install any of the input options for those characters :cry:

**Comment by masaburo02** [comment] 2019-03-25 10:09
Thank you email.

"Is this the same problem as #1071
<https://github.com/nextcloud/spreed/issues/1071> ?" > Yes! It is same
probrem.

2019年3月20日(水) 23:49 Joas Schilling <notifications@github.com>:

**Comment by nickvergessen** [comment] 2019-04-09 08:53
So this is actually caused by the plugin for `@-mentions` we use.
So this might be solved when we migrate to Vue.JS as per #1347

**Comment by nickvergessen** [comment] 2019-04-10 09:08
Closing as duplcate of #1071

**Closed by nickvergessen** 2019-04-10 09:08 UTC
Labels: 0. Needs triage, bug
