### ISSUE TITLE
Conversation list should not be collapsed when no conversation is selected

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#4766] opened 2020-12-15 21:13 UTC
**Is your feature request related to a problem? Please describe.**
The conversation list is collapsed when the windows width is below 1024px. This makes sense when you're actually in a conversation, but not, when you need to select or start a new conversation.

**Describe the solution you'd like**
Only collapse the conversation menu when actually in a conversation.

**Additional context**
![image](https://user-images.githubusercontent.com/1580193/102273431-99ff1080-3f22-11eb-94a2-05616ed79ce5.png)

**Comment by nickvergessen** [comment] 2020-12-17 12:27
The sidebar is so difficult in it's handling. But yeah totally makes sense

**Comment by nickvergessen** [comment] 2021-01-13 14:32
Actually a duplicate of #1937

**Closed by nickvergessen** 2021-01-13 14:32 UTC
Labels: 1. to develop, bug, feature: frontend 🖌️
