### ISSUE TITLE
Link share discussions design

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3304] opened 2020-04-09 07:13 UTC
https://github.com/nextcloud/spreed/blob/9451b8078850ada2e424a4f2ed7ff0904b0a3194/lib/Settings/Admin/AdminSettings.php#L74

I think this doesn't cover most of our cases.
I just want to share a picture or a file, not discuss it, I'm pretty sure most of our users doesn't care about this.
I would also add that there is currently no way to prevent spamming so maybe anyone having the link can pollute and fill the db with messages without the user knowing about it :thinking: 

cc @jancborchardt

**Comment by nickvergessen** [comment] 2020-04-09 07:19
Additional to the global switch, I think we should also have something like mode where users can discuss the file when the owner allowed it.

**Comment by jancborchardt** [comment] 2020-07-07 15:15
@karlitschek @jospoortvliet @rullzer your input here?

My biggest issue is not that we have it (others have it too) but the way it is presented:
- There’s a step to "activate" it, "Join conversation". It’s not easy to do, you don’t want to really open a whole thing on it, you just want to leave a comment, show appreciation, give quick feedback.
- It will create a conversation in Talk, which doesn’t really make a lot of sense – instead of e.g. using comments which would show up at the relevant place in Files, also on mobile.
- When you do the "Join conversation" thing, the "Join call" button is very present, which is not really something you are likely to do at this step cause you are probably viewing the file asynchronously from the person who sent it to you.

Nextcloud step 1 | Nextcloud step 2 | Dropbox
-|-|-
![discuss before](https://user-images.githubusercontent.com/925062/86802338-38826e00-c075-11ea-901d-4e0193384404.png) | ![discuss after](https://user-images.githubusercontent.com/925062/86802336-37e9d780-c075-11ea-9364-8236c7290fbb.png) | ![Dropbox comments](https://user-images.githubusercontent.com/925062/86802324-36b8aa80-c075-11ea-90e6-bdff9f2c1edc.png)

**Comment by nickvergessen** [comment] 2020-07-08 13:24
Well the "activation" step is currently needed as otherwise your instance get's spamed with conversations easily.
Maybe we combine both problems into a solution:

On sharing you can have a checkbox to attach a talk conversation to it, which then is created automatically. When it is there, we automatically show it ("Nextcloud step 2") in the sidebar. If not, the feature is just not available.

> instead of e.g. using comments which would show up at the relevant place in Files, also on mobile.

Feel free to discuss comments for guests in https://github.com/nextcloud/server/issues/2019

**Comment by rullzer** [comment] 2020-07-09 06:52
Yeah I must admit 'm not a fan either. But I have no good solution.

* Showing something (be it talk or comments) prominently is not what I (and I think most) people need in 90% of the link shares. You just want to have a way that the person you give that to can fetch the file.
* Adding yet more options to sharing seems... well... you know... cluttering it even more
* Opening a talk room by default for each share is really a no go for me. That would spam everything unneeded. Esp since like I said most of these room will not have a single message

So like I said I have no solution. But the current situation is indeed not ideal.

**Comment by nickvergessen** [comment] 2021-03-25 10:08
Closing this as the initial report is a duplicate of https://github.com/nextcloud/spreed/issues/2284 and got a "global" setting in https://github.com/nextcloud/spreed/pull/2283

Then there is additionally https://github.com/nextcloud/server/issues/2019 for guest comments and no solution insight for the technical limitations as outlined above.

**Closed by nickvergessen** 2021-03-25 10:08 UTC
Labels: 1. to develop, enhancement, feature: talk-sidebar ⬅️
