### ISSUE TITLE
Organize attachments in talk folder on a per conversation basis

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#13375] opened 2024-09-23 11:23 UTC
**One conversation = one folder**

* Name already exists? Same behaviour as with same-name–folders and same-name-files
* Conversation gets deleted: folder persists
* Conversation gets renamed: folder gets renamed too
* Frequent "go to file" action on the message only opens the current conversation's folder, not all talk attachments

**Comment by nickvergessen** [comment] 2024-09-23 12:29
> Name already exists? Same behaviour as with same-name–folders and same-name-files

How would we know if you have 2 conversations "Meeting" which one already has an attachment folder for you …


- Duplicate of https://github.com/nextcloud/spreed/issues/4340

**Closed by nickvergessen** 2024-09-23 12:29 UTC
Labels: 0. Needs triage, enhancement
