### ISSUE TITLE
Allow to paste an image to chat

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#3003] opened 2020-02-25 14:50 UTC
Ref #2994 

It would be nice if not only drag and drop to chat would be supported, but also pasting an image from the clipboard. Github and WhatsApp (Web) support this already and I think it would be a nice and logical addition to Talk.

**Comment by nickvergessen** [comment] 2020-02-26 13:17
Duplicate of #2172

**Closed by nickvergessen** 2020-02-26 13:17 UTC
Labels: 0. Needs triage, enhancement
