### ISSUE TITLE
Hovering picture hide username

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/spreed#3464] opened 2020-05-05 19:44 UTC
![Capture d’écran_2020-05-05_21-44-26](https://user-images.githubusercontent.com/14975046/81108927-9ed5fd80-8f19-11ea-8221-8a8f04636a5f.png)

**Comment by nickvergessen** [comment] 2020-05-08 10:00
Duplicate of #3327

**Closed by nickvergessen** 2020-05-08 10:00 UTC
Labels: 1. to develop, bug, design, feature: frontend 🖌️, feature: upload & shares 📤
