### ISSUE TITLE
Feature: Possibility to have email notifications on all new messages

### ISSUE THREAD

**Issue by camoflash** [nextcloud/spreed#1236] opened 2018-10-03 07:55 UTC
## Steps to reproduce
1. Go to Settings
2. Click on Activity in left column
3. All user notifications possible are adjustable here

### Expected behaviour
All new messages are showing up in activity stream. But there is no option in Settings->Activity page to set email notifications on for new messages. This makes it a problem for some at our organization that are not using nextcloud every day to keep up with the messages.

### Actual behaviour
A checkbox in Settings->Activity page that user can tick to get email notifications on all new messages.

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Windows/Ubuntu/...

**Browser name:** Firefox/Chrome/...

**Browser version:** 50.1/55/...

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Spreed app

**Spreed app version:** (see apps admin page: `/index.php/settings/apps`)

**Custom TURN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

**Custom STUN server configured:** yes/no (see additional admin settings: `/index.php/settings/admin/additional`)

## Server configuration

**Operating system**: Ubuntu/RedHat/...

**Web server:** Apache/Nginx

**Database:** MySQL/Maria/SQLite/PostgreSQL

**PHP version:**

**Nextcloud Version:** (see admin page)

**List of activated apps:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

**Comment by nickvergessen** [comment] 2018-10-04 12:55
Duplicate of #1230

**Closed by nickvergessen** 2018-10-04 12:55 UTC
