### ISSUE TITLE
Clean up talk rooms: search instead of create

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#2150] opened 2019-09-02 17:52 UTC
**Problem description**
The list of chat rooms on the left grows quickly out of sight... At which point you often end up creating new rooms where an existing one would have sufficed, or you are looking everywhere for a chat log.

Multiple rooms with the same name is confusing and pointless, it seems, and why does the list have to show people when you already have chats open with them. I don't really know what to expect when I click them - do I create a NEW conversation with them? Or open the existing one? I don't really want to try to avoid creating pointless notifications...

**Solution**
Perhaps the input field on top shouldn't be for creating a new room, but primarily filter the existing rooms and only on the bottom of that list offer a 'create new room', of course with the name you just typed.

Use a big plus as icon...? @nextcloud/designers probably have input :D

Note that this:
* doesn't cost extra clicks (just like now: type a name, click on the room name with a plus in front to create the new room. You can set it to public later, though you could of course show a room with a link and plus icon for the public option right away
* would still allow you to create multiple rooms with the same name, if you really want (I don't, I give them names for a reason... to keep them apart)

**alternatives**
Alternative solutions include:
* auto-leaving rooms after some time
* creating a permanent 'personal' room where you invite people to easily. Only you can see the full chat history, people you just invite only see the chat log as long as they are in and once they leave/are kicked, the chat history won't be visible to them anymore if they re-join.

While both would help, I think they are more (too?) complicated to handle and understand. 

Meanwhile, I needed to get used to the way the current chat room creation work: I clicked there, and clicked on the 'type name for a new conversation' a few times... Then I typed a name and was a bit confused with the options - try 'engineering' and see two options on top, both the same, no idea what they are. One is written with a capital, the other isn't. What are they, and what do they mean? Does clicking one create a new room with that name? Or does it add everyone in the group engineering to a new room? Or do I join an existing room for engineering?

**Comment by nickvergessen** [comment] 2019-09-02 19:11
Ref or duplicate https://github.com/nextcloud/spreed/issues/1010

**Comment by jancborchardt** [comment] 2019-09-02 20:19
Yep, I’d say dupe of that. Also @jenniferpiperek has a nice mockup for fixing this, which is inspired by what Telegram does.

**Closed** 2019-09-02 20:37 UTC
Labels: 0. Needs triage, enhancement
