### ISSUE TITLE
Quote a person from who redirects a message

### ISSUE THREAD

**Issue by Dtrieb** [nextcloud/spreed#13457] opened 2024-10-02 16:03 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

If I redirect a message to another person it would me good to quote it automatically and add the person from which the message was.

**Comment by Antreesy** [comment] 2024-10-02 16:15
- Replies in the same conversation are started here: https://github.com/nextcloud/spreed/pull/13065
- Forwarding requires more complex handling: original could be edited / deleted / not available to receiver / e.t.c

**Comment by nickvergessen** [comment] 2024-10-02 17:45
Duplicate of #8472

**Closed** 2024-10-02 17:46 UTC
Labels: 0. Needs triage, enhancement
