### ISSUE TITLE
The search button does not bring messages containing the search criteria

### ISSUE THREAD

**Issue by vagner-dias** [nextcloud/spreed#13460] opened 2024-10-02 19:47 UTC
Hello,

I'm encountering an issue with the search functionality in the Talk app. When I use the search bar in the Talk app (top left), no chat results are displayed. However, using the search function in the NextCloud app (top right) does return messages.

It would be helpful if the Talk app could also display messages that match the search criteria directly within the app.

**Comment by SystemKeeper** [comment] 2024-10-02 19:49
Duplicate of https://github.com/nextcloud/spreed/issues/11130

**Closed by SystemKeeper** 2024-10-02 19:49 UTC
Labels: 0. Needs triage, bug
