### ISSUE TITLE
A tchat for a circle

### ISSUE THREAD

**Issue by livier** [nextcloud/spreed#5604] opened 2021-05-11 14:17 UTC
I want to open a tchat for a circle in my nextcloud talk app
When adding users, I find some circle, add it and the users of this circle are added on the tchat
That works but ....

I would like that members of the tchat are synchronised whith members off the circle.
If anyone quit the circle, he leave the corresponding Tchat too. 
If anyone come on the circle she can see the tchat an previous messages too.

On other words, the circle is member off the tchat.

Moderateurs off the circle could be moderators of the Tchat

Other ways that could help...
- A dedicated tchat could be accessible on the circle panel (as dedicated Tchat are accessible in a document panel)
- If a tchat is linked with a circle, a notification could say to the chat moderators that people has quit or joint the circle so it is easy to ajust the Tchat list of participants. 
- 

Would be nice ...

**Comment by nickvergessen** [comment] 2021-05-11 18:06
Duplicate of https://github.com/nextcloud/spreed/issues/2854

But in the meantime there was progress, ref https://github.com/nextcloud/spreed/pull/4810

**Closed by nickvergessen** 2021-05-11 18:06 UTC
Labels: 0. Needs triage, enhancement
