### ISSUE TITLE
Error accessing camera/video makes it impossible to chat or schedule calls

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/spreed#538] opened 2018-01-03 13:23 UTC
My browser frequently seems to somehow lose access to the webcam and microphone so I am regularly blocked from accessing spreed. restarting my browser solves it, but I tend to dislike doing that as I have 20+ browser windows spread over 6 desktops ;-)

The problem is that I can't see my list of calls, create a new public call or even participate by chat in an existing one. The 'no mic/cam' screen blocks EVERYTHING. That is really a bit over the top - I'd still like to chat even on a system with no mic/camera!
![screenshot_20180103_142253](https://user-images.githubusercontent.com/551757/34522145-9878b1a4-f091-11e7-860c-2c32ce41c801.png)

**Comment by nickvergessen** [comment] 2018-01-08 10:32
Yeah, the problem is how the app was build back then. WebRTC requires the media permission, until recently apart from calling there was not much possible.

The "bug" you see there, could also be that in any other browser window you have a tab open which requested your media already. In this case no other window can request it anymore and you see this error. When it happens again, try to check if the control LED of your camera is on (if you have one).


But yeah, totally agree and for 4.0 (Nextcloud 14) we should try to make to changes for the overall usage:
1. Require the permissions only when calling, so you can join a chat room on multiple instances at the same time.
2. Allow multiple chats in parallel (currently when you open a second room/call, you are kicked out of all existing stuff). This was okay so far, since for media it doesn't even work otherwise. But for chat multi-tab support sounds like a good feature.

**Comment by nickvergessen** [comment] 2018-03-22 15:03
Resolved with #619

**Closed by nickvergessen** 2018-03-22 15:03 UTC
Labels: enhancement, feature: signaling, feature: video call webrtc

**Comment by sunjam** [comment] 2018-04-13 22:08
I just tried using Talk for the first time on two different instances of Nextcloud Stable 13.0.1 in latest build of Safari 64-bit on MacOS Sierra (fully updated) and ran into this exact screen.
![6923ba91-54b4-4893-bdf1-48484e6ba414](https://user-images.githubusercontent.com/1787238/38759792-698abc22-3f2c-11e8-8cb6-a1c3aa13d330.jpeg)

**Comment by nickvergessen** [comment] 2018-04-13 23:30
Yeah we didnt release a new version yet
