### ISSUE TITLE
Manipulate video stream quality to decrease the needed bandwidth

### ISSUE THREAD

**Issue by bes1002t** [nextcloud/spreed#3177] opened 2020-03-27 09:41 UTC
In general video calls need a lot of bandwidth, especially if multiple people are sending and receiving signals. I think a feature to manipulate the quality of the video stream that is sent to me, would be cool. I don't want always 1080p video, maybe 720p would be enough, so other download or upload processes are not affected too much by my video call.

**Comment by samtygier** [comment] 2020-04-14 08:32
Also see  #504 . Maybe worth having multiple issues, for user control, admin set limits, and real time automatic adjustments.

**Comment by samtygier** [comment] 2020-04-17 08:47
I have started a bounty for this issue https://www.bountysource.com/issues/90659391-manipulate-video-stream-quality-to-decrease-the-needed-bandwidth

[![Bountysource](
https://api.bountysource.com/badge/issue?issue_id=90659391
)](
https://www.bountysource.com/issues/90659391
)

**Comment by nickvergessen** [comment] 2021-11-18 15:48
Duplicate of #504

**Closed by nickvergessen** 2021-11-18 15:48 UTC
Labels: 1. to develop, enhancement, feature: WebRTC 🚡, feature: call 👥

**Comment by bes1002t** [comment] 2021-12-13 12:31
@nickvergessen if you close this issue here, it would be great if you could post the bounty link to the other ticket, so everyone could notice and participate.

**Comment by nickvergessen** [comment] 2021-12-13 12:43
We stopped using bountysource a long time ago due to the moral issues/ToS on their side for the Nextcloud universe. If the author of the comment still had the money posted at the time we stopped, they got it refunded to their account iirc.

**Comment by bes1002t** [comment] 2021-12-13 13:12
Ok thanks for clarification! :)
