### ISSUE TITLE
Allow the same user from multiple devices

### ISSUE THREAD

**Issue by dimst23** [nextcloud/spreed#3805] opened 2020-06-13 18:23 UTC
**Is your feature request related to a problem? Please describe.**
The problem is when I am on my desktop connected in a call and then I want to use my mobile phone, with the Talk client, to handle the chatting of the call. Whenever I just enter the conversation in the mobile the desktop call freezes and I have to get out and in again.

**Describe the solution you'd like**
I would like to be able to use both mobile and desktop or any other device at the same time without disconnections, always for the same user. Ideally I would like to be able and have video feed from both devices, from the same user.

**Describe alternatives you've considered**
So far I changed the workflow to be able use the chat from the browser.

**Additional context**
Nothing to be added.

**Comment by nickvergessen** [comment] 2020-06-13 19:04
Duplicate of #1587

We are on the way to improve the current behavior by adding a warning that joining on device 2 will kill device one, until we managed to make sure session and participants are split

**Closed by nickvergessen** 2020-06-13 19:04 UTC
Labels: 0. Needs triage, enhancement
