### ISSUE TITLE
Moderators not able to post in "locked conversation"

### ISSUE THREAD

**Issue by Excpt0r** [nextcloud/spreed#6291] opened 2021-09-26 18:43 UTC
Not sure if it is a bug or feature request.
I use a chat-group to provide news to the users.
- Only text based chatting, no video calls, therefore "lobby" option is disabled and not helpful here
- I want only moderators to be allowed to write news

### Expected behaviour
When I set the option "conversation settings" -> "Lock conversation",
I expect that group moderators are still able to post messages.

### Actual behaviour
When the option is set, nobody can post messages anymore.

## Talk app

**Talk app version:** 12.1.1

**Custom Signaling server configured:** no

**Custom TURN server configured:** no

**Custom STUN server configured:** no (nextcloud default)

**Comment by nickvergessen** [comment] 2021-09-26 19:02
Duplicate of #3886

**Closed** 2021-09-26 19:02 UTC
Labels: 0. Needs triage, bug
