### ISSUE TITLE
screen drawing

### ISSUE THREAD

**Issue by techadmin-localbit** [nextcloud/spreed#5085] opened 2021-02-05 15:08 UTC
When someone shares his screen with the chat partners, is it dificult for the other chat members to navigate the screen owner to a specifiec point on his screen.  

One option would be to get the permission to take over the control of the shared screen.

My favorite solution would be a drawing function, to draw on the shared screen and highlight what we are talking about - Let others draw on your screen.

**Comment by nickvergessen** [comment] 2021-02-09 14:20
Duplicate of #449

**Closed by nickvergessen** 2021-02-09 14:20 UTC
Labels: 0. Needs triage, enhancement
