### ISSUE TITLE
Always requires login

### ISSUE THREAD

**Issue by rugk** [nextcloud/spreed#330] opened 2017-05-31 16:42 UTC
## Steps to reproduce
1. Create a new call.
2. Copy the link in the UI.
3. Access that link.

### Expected behaviour
The login page is shown.

### Actual behaviour
Allow guest to join without login.

## Browser

**Microphone available:** yes

**Camera available:** no

**Operating system:** Linux

**Browser name:** Firefox/Chrome/... all browsers

### Browser log

<details>
```
JQMIGRATE: Migrate is installed, version 1.4.0
```

</details>

## Spreed app

**Spreed app version:** 2.0.1 

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Server configuration

**Operating system**: Debian

**Web server:** Nginx

**Database:** MySQL/MariaDB

**PHP version:** 7

**Nextcloud Version:** 12.0

**Comment by Ivansss** [comment] 2017-05-31 16:54
Guests can only join public calls. How are you creating the call?

**Comment by rugk** [comment] 2017-05-31 16:55
Visit the app/site, click on the `…` button, choose "share as link" and copy the link. That's how it worked before.

**Comment by rugk** [comment] 2017-05-31 17:05
Ah, now I see. I think this was a call I had there from before upgrading or the last session or show, because after exiting the call I can choose the contacts and at the top there is "new public call".

**Comment by Ivansss** [comment] 2017-05-31 17:09
Can you reproduce the issue when you create a 'new public call' or after clicking 'share link' in a recently created call?

**Comment by rugk** [comment] 2017-05-31 17:11
No, actually I was not even presented with "new public call". I think this was, because of a previous call or so.

**Comment by Ivansss** [comment] 2017-05-31 17:14
Did you update the app through the app store? Or did you update it via git?

**Comment by rugk** [comment] 2017-05-31 17:14
Yes. App store.

**Comment by Ivansss** [comment] 2017-05-31 17:17
Ok. Interesting. Might be a caching issue.
Thanks for the report 😊  Closing this issue because it is not reproducible any more.

**Closed by Ivansss** 2017-05-31 17:17 UTC
