### ISSUE TITLE
user settings - only optional showing conversation on sharing objects

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/spreed#6106] opened 2021-08-12 06:41 UTC
Hallo,

on a lot of server Nextcloud Talk is installed but not really used for all users. An example is public sharing a file in my example an MP3. If the administrator allows using Nextcloud Talk for files (administrator settings) on every public share there is Nextcloud Talk info which confuses people who do not use Nextcloud and/or Nextcloud Talk.

Perhaps the administrator settings can expand to the user settings that all users can decide if they want to use Nextcloud Talk on sharing files.

**Screenshot with useless infos on the right side:**

![1](https://user-images.githubusercontent.com/58322182/129149396-ac74feaf-ce75-4869-8e7a-9e4c03600cbb.png)

**Administrator settings - perhaps can be expand to user settings:**

![2](https://user-images.githubusercontent.com/58322182/129149497-8e5abb1f-fc44-435a-997c-012845548841.png)

**Comment by nickvergessen** [comment] 2021-08-20 07:11
Duplicate of https://github.com/nextcloud/spreed/issues/2284

**Closed by nickvergessen** 2021-08-20 07:11 UTC
Labels: 0. Needs triage, enhancement
