### ISSUE TITLE
Show presenter video on the bottom right in screenshares

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#5025] opened 2021-01-26 12:37 UTC

**Comment by nickvergessen** [comment] 2021-01-26 13:57
that will be support confusing with your own video always being bottom right.
Maybe bottom left?

**Comment by PVince81** [comment] 2021-03-08 17:28
duplicate of https://github.com/nextcloud/spreed/issues/4478

**Closed by PVince81** 2021-03-08 17:28 UTC
Labels: 1. to develop, bug, feature: call 👥, feature: frontend 🖌️
